usdigitalresponse/usdr-gost

packages/client/src/components/Layout.vue, packages/client/src/components/Modals/EditTenant.vue, packages/client/src/router/index.js, packages/client/src/store/index.js, packages/client/src/store/modules/tenants.js, packages/client/src/views/Tenants.vue, packages/server/migrations/20220208185452_add_tenants.js, packages/server/seeds/dev/index.js, packages/server/seeds/dev/ref/tenants.js, packages/server/seeds/dev/ref/users.js, packages/server/src/configure.js, packages/server/src/db/constants.js, packages/server/src/db/index.js, packages/server/src/routes/tenants.js
This PR adds the tenant model to the database and the ability to edit the tenant's display name in the app.
Next steps: 
* Using tenant id instead of root agency in access helpers and as the organization id in the client 
* Restricting list of agencies to agencies in the user's tenant
Addresses #6
=> Adding tenant model and ability to edit display name

packages/client/src/views/Login.vue
Closes #9
This is simple enough it doesn't really need review but am waiting on the answer to a question on #9 about exactly which page to link to.
=> Add helptext on login page linking to contact form for new accounts

packages/server/__tests__/api/keywords.test.js, packages/server/__tests__/api/utils.js, packages/server/seeds/dev/ref/keywords.js, packages/server/seeds/dev/ref/users.js
Closes #15 by doing pretty much what the title says.
I had to make some changes to the keywords API test because it assumed the presence of the pre-seeded keywords. Now, the test creates its own keywords.
I also noticed that the test referred to a user that doesn't seem to exist in the users seed, `michael@nv.gov`. I replaced this with a new admin user under the same agency and added a better error log for when `getSessionCookie` is called with an invalid user. I noticed several other tests were failing locally for a similar reason, I've fixed those too, in a separate stacked PR: #63
=> Remove COVID-related seeded keywords (closes #15)

packages/server/__tests__/api/agencies.test.js, packages/server/__tests__/api/eligibilityCodes.test.js, packages/server/__tests__/api/grants.test.js, packages/server/__tests__/api/users.test.js
Depends on #62
As mentioned in #62's description, in the course of working on the PR I discovered some other tests failing locally because they referenced users that do not exist in the users seed. This fixes that for the other affected tests that were not directly related to what I was doing in #62.
I also found that two tests depended on a specific number of users that did not match what the seed creates and fixed that here too.
More broadly, I'm wondering if I'm misunderstanding the use case of these DB seeds -- I assumed they were intended just for local and test environments, but the existence of #15 implies they are used for creating agencies, keywords, etc. in production as well? It also seems that for the issues above to arise, the users seed would have needed to be modified after …
=> Fix other tests affected by invalid seed user

.gitignore, packages/client/src/components/Modals/GrantDetails.vue, packages/client/src/store/modules/users.js, packages/server/migrations/20220417025208_add-spoc-setting-to-tenants.js, packages/server/src/db/index.js
addresses #43 by adding `uses_spoc_process` column through migration and checks for the tenant `tenant.uses_spoc_process` to show/hide SPOC button in grants modal.
=> 43 add spoc button to tenants

packages/client/src/components/Modals/GrantDetails.vue, packages/server/seeds/dev/ref/users.js
easy fix added a check in the grants modal to only show delete button if the row's agency_id value matched the user's agency.id.
Closes #66
=> fix: added agency id check to remove agency button in agency table

packages/server/src/lib/email.js
There are currently two emails being sent that have state-specific verbiage. I updated both emails to have generic USDR details instead.
Closes #13
=> feat: changes passcode and welcome email verbiage to be generic

packages/client/src/components/GrantsTable.vue, packages/client/src/store/modules/grants.js, packages/client/src/views/MyGrants.vue, packages/server/src/db/index.js, packages/server/src/routes/grants.js
This branch adds the ability to show/hide rejected and interested grants by using a filtering system. On the grants tab, there is a drop down menu to filter by grants marked as positively interested and rejected. On the my grants tab, there is another tab added exclusively for rejected grants with the interested tab now only showing those grants marked with an interested code that indicates positive interest. These filters were added to the export csv functionality as well.
Drop down menu on grants tab
Multiple options can be selected
Or just one option can be selected
New rejected tab in my grants tab
In the grants tab, select some grants and mark as interested or rejected -> in the grants tab, use the review status drop down menu to test filtering options. -> switch to the my grants tab …
=> 50: Add way to show/hide rejected and interested grants

packages/server/src/db/index.js
Adds functionality to getTotalInterestedGrantsByAgencies() function used in the dashboard for filling in the agency activity table. Three more columns of data are available for each agency row: 
* Total value of award ceiling for all grants (both interested and rejected)
* Total value for interested grants
* Total value for rejected grants
These columns are represented by the keys "total_grant_money," "total_interested_grant_money," and "total_rejected_grant_money," respectively
Only contains backend changes, no visual features to demo.
For testing, the values in 'totalInterestedGrantsByAgencies' in Dashboard.vue can be looked at manually by logging or visualized by adding fields in the dashboard file's "groupByFields" that have keys matching those given above. It is helpful to pick an …
=> Issue 131 backend for agency activity table

packages/client/src/App.vue, packages/client/src/views/Dashboard.vue, packages/server/src/db/index.js
Issue #133 
Issue Solution: 
Created getClosestGrants() query to get 3 grants that have the closest close dates in comparison to the current date, returns the title and date of the of the grant since the Upcoming Closing Dates sections will only display those pieces of grant information. The API for getting the abbreviations of all agencies interested (to be placed under the grant name) already exists (used in the Grants Table "interested Agencies" column).
Screenshots:
Only backend API work and no frontend implementation
Testing:
Checking the grants date in the Grants Table using the sorting feature and comparing them to the query return value.
=> 133 upcoming grants table backend

packages/client/src/views/Dashboard.vue
The original dashboard had five grey cards of information. This removes two of them and rearranges the other three to match the new dashboard wireframe.
Cards before:
Cards after in context of entire dashboard:
Go to dashboard -> verify cards match the wireframe of the new dashboard layout.
=> 151 edit dashboard cards

README.md, package.json
Small PR to add a new step for creating and copying the `.env.example` to `.env`.
Also make use of existing `yarn scripts` while adding a new one for `yarn db:seed`.
=> Update README for clarity, update package.json to include yarn db:seed

packages/server/src/db/index.js
Fixes the duplicate entries found when applying interested/rejected filters.
Before
After
Mark the same grant as interested/rejected with multiple subagencies -> apply an interested or rejected filter in grants or my grants and check that there are no duplicates
=> 176 fix duplicates in interested/rejected

packages/client/src/router/index.js, packages/client/src/views/Dashboard.vue, packages/client/src/views/UpcomingClosingDates.vue
Added the see all upcoming button full page FRONT END functionality, once the changes for the backend functionality of the upcoming closing dates is finished they can be added right in the same way it was for issue #159 
https://user-images.githubusercontent.com/60362888/181604203-d24070a0-4025-45e9-b360-83151d7b3a2e.mov
Not much testing to be done since this is front end only, other than routing. I made sure the user could click on any of the other tabs from the full page display and it would route correctly
=> fix(157): added front end full page see all upcoming

packages/client/src/router/index.js, packages/client/src/store/modules/grants.js, packages/client/src/views/RecentActivity.vue, packages/server/src/db/index.js, packages/server/src/routes/grants.js
Adds the backend for bringing up the GrantDetails modal by clicking on entries in the dashboard feeds, implements the functionality with the full screen recent activity feed. The functionality will be added to both the feeds and the upcoming grants full screen view in the future.
From the activity feed click the see all button to bring up the full screen view -> click on an entry to test that the GrantDetails modal shows with the correct information -> test functionality for marking as interested/assigned
=> 155: add backend for GrantDetails from clickable entries in dashboard, implement with "show all" activity feed

packages/client/src/components/Modals/GrantDetails.vue
Adds the ability for a subagency to delete their interested status. 
Note/Question: It looks like unmarking a grant as interested is tied to the user id, so if multiple subagencies and the parent agency all have a grant marked as interesting and one of the agencies deletes their interested status, all of the associated agencies will have their status deleted too. Is this the expected behavior?
(logged in as usdrtest3)
Before: 
After
Mark a grant as interesting with a subagency and check that the status can be deleted correctly. Also test that it works with parent agencies.
=> 190 subagency can now delete their interested status

packages/client/src/store/modules/grants.js, packages/client/src/views/Dashboard.vue, packages/client/src/views/RecentActivity.vue, packages/server/src/db/index.js, packages/server/src/routes/grants.js
This PR limits the recent activity table on the dashboard to only display 4 grants using knex pagination and also adds pagination functionality to the full page display of the recent activity 
https://user-images.githubusercontent.com/60362888/182444239-34d09ed9-b088-4cad-b518-a2b43d4547b4.mov
Testing was done by jumping through all possible paged of the full recent activity view using the numbers and the next and prev, as well as refreshing the page at multiple points to make sure the API calls were still being executed correctly
=> fix(181): recent activity displays only 4 grants on dashboard and full page recent activity has pagination

packages/client/src/components/Modals/GrantDetails.vue, packages/server/src/db/index.js
* Parent agencies now have the option to unmark statuses for children
* Unmarking is available to other users in the same agency or a parent agency, it is no longer only available to the user who created the status
* Unmarking one agency/subagency as interested from a grant now only deletes that row or status and not every status for other agencies entered by the user for that grant
* Fixed a bug where the agencies list in GrantDetails was not updating when changing selected agency/subagency
* Note: This would be a good thing for multiple people to test together in staging to make sure it works with different users
With usdr3, a USDR subagency, selected:
With USDR selected, all child statuses are available to be deleted:
* Check that parent agencies can delete their own and their child …
=> 201 update unmark grant as interesting functionality

packages/client/src/views/UpcomingClosingDates.vue
updated full page view of upcoming closing dates to match dashboard
updated colors, bolded dates, aligned header
old:
new:
Still just a front end mock so no functionality to test for now
=> fix(214): updated full page view of upcoming closing dates to match dashboard

packages/client/src/views/Dashboard.vue, packages/client/src/views/RecentActivity.vue
Changes the activity feed on dashboard and full page to display full dates for entries added more than 7 days ago.
Before (dashboard):
After (dashboard):
Before (full screen):
After (full screen):
Add entries to recent activity feed, observe that those more than 7 days ago are showing full dates instead of "Today" or "x days ago" on both the dashboard feed and full screen feed.
=> 228 display full date on activity feed for entries more than 7 days ago

packages/client/src/components/GrantsTable.vue
The MyGrants view was being limited to grants marked as interested by the current user, when they should see all grants for an agency. 
I made it so that the showInterested flag did not filter by the user id on the grants_interested table, and made a new flag that could do that filtering.
One thing to bring up, which may be outside the scope of this fix, is that it looks like the grants_interested table has the user_id of the creator as a foreign key, that if the user got deleted would delete this linking record. 
https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/migrations/20201214213110_grants_interested.js#L13
If a user is deleted would we want the record of interest in a grant for the agency to also be deleted? Based on this bug my intuition says no, but I'm …
=> Fix 129: Interested and Rejected Grants views should be Agency-scoped, not User-scoped 

packages/client/src/store/modules/grants.js, packages/client/src/views/Dashboard.vue
Adds the ability to click on dashboard feed items to bring up the grant details modal
Go to dashboard -> click on a feed item in one of the two feeds -> make sure grant modal appears with correct grant and full functionality
=> 212 add clickable functionality to dashboard feeds

packages/client/src/views/Dashboard.vue, packages/server/__tests__/db/db.test.js
Issue #153 
#226  PR updated
Solution:
Added UX/UI to fit Upcoming Closing Grants table
Interested Agencies will only list under a grant if the grant has any, so having no abbreviations underneath means there are no agencies interested in that grant.
Changes do not include full page view
Screenshot:
1.) With the bold dates and font size changes
Testing:
Added interest in a given grant and saw it display underneath the correct grant name.
=> 153 updated

packages/server/src/db/index.js
Changes the upcoming grants feed to only show grants that have interested agencies.
Before
After 
In dashboard, make sure the grants in upcoming closing dates have interested agencies, ensure that the dates and interested list are correct.
=> 248 upcoming closing dates feed now only show grants that have interested agencies

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js, packages/server/src/routes/dashboard.js
Adjusts the getClosestsGrants query to only get the closest grants with interests from the currently selected agency or subagencies.
Before
After 
Mark grants as interest -> check the upcoming grants feed to see if grants have interested agencies and that those agencies are either the currently selected agency or subagencies of that agency
=> 248 make upcoming dates entries show only those interested by selected agency or subagencies

packages/client/src/views/Dashboard.vue
There seemed to be an issue where the upcoming closing dates feed would not display anything if there were less than three grants in the table. This should give a fix for it.
After fix:
Before fix:
Make a new subagency and select a grant or two that would appear in the upcoming closing dates feed -> verify that they show up in the feed.
=> 257 bug fix for upcoming closing dates

packages/server/src/db/index.js
The function markGrantsAsInterested in index.js was being passed a 0 as the interested code when "Not applicable ..." was selected but when the value was logged in the function it was displaying null. I fixed this by adding a unary plus to the interestedCode variable to convert null to the number 0 but not change anything for the other interested codes.
See issue #252 for demo of the bug
Fixed:
https://user-images.githubusercontent.com/60362888/184424550-144671e6-58e9-4c1a-8405-94af3f88f46b.mov
Tried selecting grants of all possible interested codes to ensure they all work as they should. Also tested trying to mark a grant as interested with no interested or rejection prompt to make sure that still did nothing because that technically counts as trying to make a grant with a null selected …
=> fix(252): fixed handling of interest code 0

packages/client/src/views/Dashboard.vue, packages/client/src/views/UpcomingClosingDates.vue, packages/server/src/db/index.js
Issue: #232 
Issue Solution:
Changed getClosestGrants query to list all grants that fit the requirements but still limiting it on the dashboard card.
Used b-pagination for easy table navigation.
Screenshots:
1.) Full Page view of Upcoming Closing Grants Table with 11 grants. Date colors are being fixed in a separate issue.
Testing:
Changed number of grants with interest to see how it would be displayed.
=> 232 closing grants full page

packages/client/src/store/modules/dashboard.js, packages/client/src/store/modules/grants.js, packages/client/src/views/Dashboard.vue, packages/client/src/views/UpcomingClosingDates.vue, packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js, packages/server/src/routes/dashboard.js, packages/server/src/routes/grants.js
Fixed a bug where interested lists on entries after the first page would not show on the upcoming grants full screen view. Also adds backend pagination to getClosestGrants and moves the closestGrants functionality from the dashboard route to the grants route to make passing perPage and currentPage a bit easier.
Before 
After (data in the table had changed at this point, but shows that the second page works, 00 indicates 2100)
Check the upcoming grants feed full page view, add enough grants to get more than one page, check that all functionality and info is present and correct on all pages.
=> 268 fix upcoming grants full screen bug, add backend pagination

packages/client/src/views/Dashboard.vue, packages/client/src/views/UpcomingClosingDates.vue
Upcoming closing dates was not working at times when certain grants were selected. These changes seem to make all information appear.
Before
After
Check upcoming closing dates, make sure all data is visible. Check that grants are visible when less than three are in the feed and when the grant titles are multiple lines long.
=> 272 upcoming closing dates feed fix

packages/server/__tests__/db/db.test.js, packages/server/__tests__/db/seeds/fixtures.js
Adds testing for the getSingleGrantDetails db function. Adds slight edits to some grants interested tests to account for adding the the user id value.
run yarn test:db, see expected output in screenshot above
=> 185 add getSingleGrantDetails tests

packages/client/package.json, yarn.lock
We also use Vue v2 in the arpa repo, but haven't had issues with Node 16.  I was curious what the bottleneck was in usdr-gost, so I poked around a little.
I think it might just be `node-sass` giving you headaches.
A couple years ago, `node-sass` (internally a distribution of the C implementation, libsass) [was deprecated](https://sass-lang.com/blog/libsass-is-deprecated) in favour of the more actively maintained `sass` (internally dart-sass) project.  Both are meant to have interchangeable node APIs, and sass-loader discovers whichever package you have installed.
I tried picking a version of `sass` from around the same time as the currently installed `node-sass`, and that seems to do the trick for me!
Now the repo runs in node 14 and 16, and I don't see any new sass warning or error …
=> chore: replace libsass with comparable dart-sass version

packages/client/src/views/Dashboard.vue
Adds back the ability to see the upcoming closing feed in dashboard. (no ticket since last minute fix)
On dashboard, verify that upcoming closing dates works correctly.
=> add back upcoming feed in dashboard

packages/client/src/views/Dashboard.vue
Adds back the ability for the upcoming closing dates feed to clear itself out when changing agencies so old values aren't left inside. (no ticket, last minute fix)
before  (with test22 selected)
after will just show the test related grant
change agencies when in dashboard -> make sure upcoming closing dates changes accordingly as well.
=> add back upcoming list clearing

packages/client/src/views/Dashboard.vue
Adds back the fix that stopped upcoming closing dates from not showing when there are less than 3 entries. (no ticket, last minute fix)
before (list not actually empty)
after will show the feed
select agency with less than 3 grants upcoming and verify that they show on the dashboard feed.
=> add back the fix for upcoming closing dates not showing when less than three items are in the list

packages/client/src/views/Dashboard.vue
Adds back some fixes for the upcoming dates feed colors from a PR by @anigonzales that were removed. (no ticket, last minute fix)
before (all red)
afterwards the bottom two grants will be gold
ensure closing date colors in the upcoming feed are correct based on the agency's threshold settings.
=> add back the color fix for dashboard upcoming feed that was removed

packages/server/.eslintrc.js
This was causing warnings on several PRs for things that are usually unnamed by convention and doesn't feel that useful anyway.
=> Disable func-names linter

packages/server/src/db/arpa_reporter_db_shims/agencies.js, packages/server/src/db/arpa_reporter_db_shims/users.js
These two files are intended as drop-in replacements for the ARPA Reporter's equivalent database accessor modules for the tables that will be shared. They will be designated as an import rewrite in my copy_and_rewrite script (see draft PR #297) The intent is to eventually remove these by updating callsites in ARPA Reporter to use the GOST database accessors directly.
This PR is a sister to https://github.com/usdigitalresponse/arpa-reporter/pull/505 in the arpa-reporter repo which modifies the usage of these tables there to more closely match their shape in GOST (particularly with respect to the `role`/`role_id` fields and joins to `agencies` in the `users` accessors.
This covers tables `users`, `roles`, and `agencies`. The `access_tokens` table will not be used directly in any ARPA …
=> ARPA integration: Database shims for ARPA Reporter code

.github/workflows/ci.yaml, packages/client/package.json, packages/server/__tests__/run_arpa_reporter_tests.sh, packages/server/package.json
This will accompany changes in the ARPA repo to make the ARPA Reporter unit tests that will eventually be copied in by the script in #297 possible to run in GOST (and automatically run by CI).
#308 (not for review) is a branch that includes these changes, the copied files, plus some ARPA-side changes that will shortly be put up in a sister PR, validating that the tests can run and pass on CI.
Without those other changes, the new test script added here no-ops.
=> ARPA Integration: GOST-side changes to allow running ARPA Reporter tests

packages/server/src/db/arpa_reporter_db_shims/agencies.js, packages/server/src/db/arpa_reporter_db_shims/users.js, packages/server/src/db/index.js
Various fixes to unbreak users/agencies tabs of ARPA when integrated into GOST:
- Correct return types on several of the DB shims
- Add defaults for required `parent`, `abbreviation`, `warning_threshold`, `danger_threshold` columns when creating agencies
- Correctly handle ARPA's role object format in DB shim when creating a user
- Return all columns (including crucially `tenant_id` in `getAgency`, called by a shim that assumed this was already the case)
- Fix column order in `createAgency` (broken in #296, oops); make sure this also returns the full row.
- Plus one fix in ARPA repo: https://github.com/usdigitalresponse/arpa-reporter/pull/520
=> ARPA integration: Bugbash fixes for user/agency creation

README.md, packages/server/knexfile.js
I was trying to set up a working GOST environment this evening, and was very confused that none of the variables I set in my .env file were respected.
Finally, I realized that this knexfile wasn't actually loading dotenv, and therefore the .env file is ignored.   I assume that's just an oversight?  Any reason not to remedy that here?
=> Load environment variables from .env in knexfile.js

packages/server/src/lib/annualReports/reportBuilder.js
270
Bug-fix.
Ingested workbooks have changed a tab name from 'Project Data' to 'Project Information'. Need the ARPA reporter to reflect the new tab name on the workbook so it can generate a report from the data on that tab.
=> fix: respect new tab name in workbook when generating report

packages/server/src/db/index.js, packages/server/src/scripts/import_arpa_reporter_dump.js
1. #309 changed the `getTenantAgencies` accessor and didn't fetch `code` column used by ARPA Reporter; now we fetch all columns (Fixes #364)
2. `reporting_periods.certified_by` (FK to `users.id`) was not listed in import_arpa_reporter_dump.js, causing import to fail if any reporting periods had been certified (somehow we didn't catch this in bugbash; I guess ARPA staging had no certified periods)
=> Misc fixes after ARPA Reporter merge

packages/client/src/components/GrantsTable.vue
https://github.com/usdigitalresponse/usdr-gost/issues/349
Add column to two grants lists. There will be another PR that addresses the fact that sort currently only sorts the visible rows, not all the rows.
Manual
=> feat: add column to grants lists

packages/client/src/components/GrantsTable.vue
- Rejected grants are currently not scoped to the agency. After this commit, users can only see rejected grants that are part of their agency.
https://www.loom.com/share/21ea1fd0f1be491aaf7cd8be8bfacbb9
- No unit-test coverage here. Adding Loom video.
=> 129 - fix: ensures rejected grants are filtered appropriately

packages/server/src/arpa_reporter/routes/users.js
https://github.com/usdigitalresponse/usdr-gost/issues/404
Currently the welcome email for all new users defaults to the ID tool. This PR ensures that when users are being created for the ARPA reporter tool-- then they receive an email redirecting them to the ARPA tool.
https://www.loom.com/share/35eb95346f1448c38919660de7c9f951
TODO: add unit test
=> feat: ensure arpa_reporter users are redirected to ARPA tool upon user creation

packages/server/src/index.js
In looking at [this](https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1664404901738039?thread_ts=1664404009.254059&cid=C0324KDQSCR) I incidentally noticed that this cron syntax seemed to be wrong:
- Grants scraper cron
- old: `* 30 * * * *` = every 1 second during minute 30 of every hour
- new: `30 * * * *` = [once per hour at minute 30](https://crontab.guru/#30_*_*_*_*)
- "Clean generated PDFs" cron
- old: `* 1 * * *` = [every 1 minute from 01:00 to 01:59](https://crontab.guru/#*_1_*_*_*)
- new: `0 1 * * *` = [once per day at 01:00](https://crontab.guru/#0_1_*_*_*)
=> Fix incorrect cron syntax for grants scraper and PDF cleaner

.gitignore, README.md, docker-compose.yml, docker/Dockerfile, docker/README.md, docker/postgres/docker-entrypoint-initdb.d/create_dbs.sql, docker/postgres/docker-entrypoint-preinitdb.d/example.sh, packages/client/vue.config.js
This PR adds support for using Docker to create and manage development environments. 
In particular, it includes the following changes:
- Defines container image build instructions for backend and frontend containers (see `docker/Dockerfile`)
- Defines container service dependencies for managing containerized development environments with Docker Compose (see `docker-compose.yml`)
- Adds automation for Postgres setup when using Docker Compose (see `docker/postgres/`, `docker-compose.yml`, and `.gitignore`)
- Add documentation for using Docker and Docker Compose for development (see `docker/README.md`)
- Conditionally sets Vue development server's config options at `devServer. allowedHosts` and `devServer.proxy['/api'].target` with values derived from `VUE_ALLOWED_HOSTS` and …
=> 426: Add tooling for docker-based development environments

packages/server/__tests__/api/grants.test.js, packages/server/src/db/index.js, packages/server/src/lib/access-helpers.js, packages/server/src/routes/grants.js
The markGrantUninterested action seems to be broken after the implementation of an isAuthorized check which requires a single integer value to be passed in rather than an array.
**Note** - this is a temporary fix that ensures we don't 500 in these requests. A more permanent fix requires us to change the client-side code and clean up what the server should be expecting for this request. I put this up so our users will have the functionality and will plan to revisit this again when I'm back.
- https://www.loom.com/share/92e6392256aa4c5980743e1d8ae64eae
- Adds a happy-path unit test
=> fix: temporary fix that allows grants to be marked uninterested

.github/workflows/dependabot-auto-approve.yml
This PR adds a new GitHub Actions workflow that automatically approves Dependabot PRs when the dependency bump is minor or patch.
Now that [auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#enabling-auto-merge) has been enabled on this repository, the net effect is that minor/patch dependency updates via Dependabot will be automatically merged as long as all other checks (such as tests) pass successfully.
=> 477: Add GitHub Actions workflow to auto-approve Dependabot PRs

.github/workflows/dependabot-auto-approve.yml
This PR updates the workflow added in #478 with an additional step that enables auto-merge on Dependabot pull requests. The same semantic versioning constraints (must be patch or minor) apply to this behavior.
=> Enable auto-merge for Dependabot PRs

.github/workflows/dependabot-auto-approve.yml
This PR modifies the "Dependabot auto-approve" workflow's triggering event to `pull_request_target` instead of `pull_request`. The TL;DR reason is that `pull_request_target` should provide sufficient access for the workflow to mark a PR as approved for auto-merge.
The differences between the two events are a bit nuanced; for those interested in the details, see [this article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) as well as the documentation for [pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) and [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target). Meanwhile, [here's the most succinct explanation I could …
=> 477: Run Dependabot auto-merge workflow on pull_request_target

.github/workflows/ci.yaml
The paambaati/codeclimate-action GithHub Actions workflow runner v3.1.0 suddenly broke (which maybe means that its maintainers are not pushing immutable tags?). From the README as of today:
> **Warning**
>
> Please upgrade to v3.1.1 (or higher) immediately. v3.1.0 was recently broken inadverdently, and the only fix is to upgrade your action to v3.1.1 or higher. Please see [#626](https://github.com/paambaati/codeclimate-action/issues/626) for more details.
This PR bumps the runner from the breaking v3.1.0 tag to v3.2.0 accordingly.
The new version will be tested once this PR is opened.
=> 508: Fix: Bump paambaati/codeclimate-action v3.1.0 -> v3.2.0

packages/server/src/arpa_reporter/services/validate-upload.js
#496 
#382 
This PR adds a bunch of new validations that have been requested by our partners. Most of them are added in a new "beta" mode, where the validation shows as a warning instead of an error. This is a low-risk way to introduce these new features without potentially accidentally blocking partners from finishing this quarter's reports on time.
One new validation is added as an actual error: If the uploaded workbook doesn't include any project records, it will now fail validation
The beta validations that have been added are:
- Warn if there are multiple projects with the same id within the file
- Warn if there are multiple subrecipients with the same UEI/TIN pair in the file
- Warn if there are multiple subwards with the same subward number
- Warn if a sub-award includes a project …
=> 496 and 382 feat: add new validations for empty file and ref ids

packages/server/src/arpa_reporter/services/validate-upload.js
https://github.com/usdigitalresponse/usdr-gost/issues/497
Partners have reported that some users have been subverting the workbook formatting to enter text explanations in some fields that are required to be currency amounts.
This change enforces that any field recorded in a 'Currency' type column that is read as a string must adhere to a proper currency format (some number of digits, with optional decimal point and following digits).
Partners provided me a workbook where they saw this bug. I can provide it for testing if anyone needs it.
=> #497: Validate that currency types are formatted as numbers

packages/server/src/db/index.js
In https://github.com/usdigitalresponse/usdr-gost/pull/470, we made changes to an endpoint where we updated a knex raw query to query based on a new column. However, in doing so, we used double quotations to designate column value whereas in postgres double quotations designate a column name instead.
This fix changes the quotations to the appropriate single quotations.
=> fix: Change double quotes to single quotes in knex query

packages/server/src/db/index.js
https://github.com/usdigitalresponse/usdr-gost/issues/456
I debated between:
- Adding yet another parameter (e.g., something like “ignoreAgencyCriteria”) to 
- packages/client/src/views/MyGrants.vue/MyGrants.vue (perhaps a hidden tab?)
- packages/client/src/components/GrantsTable.vue
- packages/client/src/store/modules/grants.js
- Etc…
- Or using the existing parameters to packages/server/src/db/index.js:myGrants() to figure out if the query came from the “My Grants” tab
I chose the second option because:
- The code in getGrants() in packages/server/src/db/index.js is somewhat complex since it has to deal with various combinations of the filter parameters passed in. I felt adding another parameter would make it even harder to understand (and possibly more brittle).
- I didn’t have to pass …
=> 456: use existing parameters to detect query from My Grants

packages/client/src/components/GrantsTable.vue, packages/server/src/routes/grants.js
See [Slack context](https://usdigitalresponse.slack.com/archives/C0473BJ7HGE/p1667434061485569?thread_ts=1667432845.972789&cid=C0473BJ7HGE).
Note: I have not investigated why/how grants rows get null `raw_body`, this is just a quick fix to stop CSV export from 500ing.
=> fix: don't throw in getAwardFloor if raw_body null

packages/client/tests/unit/arpa_reporter/server/lib/format.spec.js, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/lib/format.js
Restores #524
In addition to restoring the revert of the above, this change includes a fix such that the capitalizeFirstLetter helper is resilient to non-string values.
For context, I'm fairly certain I understand what happened now:
While editing an input spreadsheet, we restrict the editable cells to the columns relevant to your currently selected expenditure category.  However, we don't _erase_ cells if you start working on one category and then swap to another.
In this case, I think someone had an invalid value in one of the KPI columns relevant to EC codes 5.19–5.21.  Perhaps noticing that they were working in the wrong code, they swapped to a different EC code (within 5.x) and then continued to fill out the template.
Stray values like this are transparent to our validation, and will …
=> Restore KPI values in audit report

packages/server/src/arpa_reporter/services/records.js
Reads column IDs directly from the upload file.  This is effectively a revert of https://github.com/usdigitalresponse/arpa-reporter/commit/169e03cdaad4cbcaa1d8afc1264214c5ae7f5073.
There are a few things worth validating in this change:
1. Validation rules are keyed on treasury ID, so they should continue to function.  However, the column indexes are based on the generated validation rules, so they may mismatch with the latest upload template.  Is this okay?
2. If treasury IDs themselves have changed in the past, this may cause some issues when reading records out of old spreadsheets for (e.g.) audit report generation.
=> 585: Read column IDs directly from upload sheets

packages/server/src/db/index.js, packages/server/src/lib/grantscraper/index.js
https://github.com/usdigitalresponse/usdr-gost/issues/52
This doesn't actually fix the bug, but adds better logging. The better logging found https://github.com/usdigitalresponse/usdr-gost/issues/633
n/a
Example log output:  
```
gost-app  | 2022-11-23T16:31:13.654667401Z knex error when creating a new row with key 340880 in grants: error: insert into "grants" ("agency_code", "award_ceiling", "cfda_list", "close_date", "cost_sharing", "description", "eligibility_codes", "grant_id", "grant_number", "notes", "open_date", "opportunity_category", "opportunity_status", "raw_body", "reviewer_name", "search_terms", "status", "title") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) - value too long for type character varying(255)  
...  
gost-app  | …
```
=> 52 infra: improve server status and error logging

packages/server/src/lib/email/email-aws.js
I noticed that Staging render was not sending emails. Here's what I found in the logs:
```
Dec 2 11:54:42 AM  server: ::ffff:10.104.140.119 - - [02/Dec/2022:16:54:42 +0000] "GET /favicon.ico HTTP/1.1" 304 -
Dec 2 11:54:48 AM  server: generatePasscode for : asridhar@usdigitalresponse.org
Dec 2 11:54:48 AM  server: ::ffff:10.104.105.35 - - [02/Dec/2022:16:54:48 +0000] "POST /api/sessions HTTP/1.1" 200 91
Dec 2 11:54:48 AM  server: node:internal/process/promises:265
Dec 2 11:54:48 AM  server:             triggerUncaughtException(err, true /* fromPromise */);
Dec 2 11:54:48 AM  server:             ^
Dec 2 11:54:48 AM  server: UnexpectedParameter: Unexpected key 'Text' found in params.Message
Dec 2 11:54:48 AM  server:     at ParamValidator.fail …
```
=> fix: bug with sending text email body

packages/server/src/arpa_reporter/services/records.js
It looks like since the time this code was previously running and my re-introduction we introduced a blank column in the upload template.  My previous pull request didn't account for this, so the header and content ranges were one cell off from one another!
Before fix:
After fix:
I was able to reproduce this issue on a local ARPA report instance.  Applying the above fix restored meaningful validation feedback on the sample test report.
Steps I took to verify this change:
- Log into wisconsin reporter tenant
- Open details view for most recent upload
- Attempt to re-validate upload, observe errors
- Download upload .xlsm file
- Launch local usdr-gost service
- Attempt to upload .xlsm file, observe same validation errors
- Apply this fix, re-run validations
=> 656: Fix off-by-one error in header column index!

packages/server/__tests__/arpa_reporter/server/services/validation-rules.spec.js, packages/server/src/arpa_reporter/routes/audit-report.js, packages/server/src/arpa_reporter/services/records.js, packages/server/src/arpa_reporter/services/validation-rules.js
https://github.com/usdigitalresponse/usdr-gost/issues/680
Fix for a bug reported by RI saying they are unable to download the audit report currently.
I was able to repro the bug and saw an error message in the 500 response coming back from the audit_report endpoint:
I looked for anywhere in code that reads the persistentFormatters field in the audit report codepath, and made sure to handle null values more gracefully.
I also added logging to the endpoints error handing so that in addition to sending that error message, it will log the entire error (including the callstack) so that we can examine it more thoroughly.
I also cleaned up some issues with the formatter methods that were generating unnecessary logs that occurred when string methods were applied to values that were instead parsed …
=> #680 Fix null rules error that is blocking audit report generation

packages/client/src/components/Modals/ProfileSettings.vue, packages/server/__tests__/db/db.test.js, packages/server/__tests__/db/seeds/fixtures.js, packages/server/__tests__/email/email.test.js, packages/server/src/db/index.js, packages/server/src/index.js, packages/server/src/lib/email.js, packages/server/src/static/email_templates/_additional_grants_button.html, packages/server/src/static/email_templates/_content_spacer.html, packages/server/src/static/email_templates/_formatted_body.html, packages/server/src/static/email_templates/_grant_detail.html, packages/server/src/static/email_templates/base.html
This PR does a few things: 
1. Adds the grants digest email
2. Re-uses components across multiple emails
3. Ensures all emails have consistent styling
4. Ensures there's a placeholder for the notification management changes in the front-end
Demoed during show and tell
https://www.notion.so/usdr/Show-Tell-d4ba5e125d2b49df844eda046d298fd3
- Added unit tests and integration tests
=> feat: adds ability to serve a digest email

packages/client/src/components/Modals/AddKeyword.vue, packages/client/src/store/index.js, packages/client/src/store/modules/grants.js, packages/client/src/store/modules/keywords.js, packages/client/src/views/Keywords.vue
As we look to add new `anti-keywords` as a part of #413, I motion to separate the `keywords` store module from the larger `grants` module. While keywords themselves are intrinsically tied to grants - they assist in the grant name search process - I believe adding the new `anti-keywords` pattern could overload the `grants` module which already handles grants lookup and adding, agencies related to grants, marking grants as interested, exporting grant CSVs and more.
Also, the `keywords` functionality is more or less already distinct - the API endpoints are already namedspaced appropriately for keywords - and given how small of a task it is to separate the two, I choose to do so here.
=> 413: Separate Keywords Functionality from Grants Store

packages/server/src/arpa_reporter/services/records.js
None (reported by Dan in our Thursday meeting).
Turns out this PR (https://github.com/usdigitalresponse/usdr-gost/pull/687) was a little incomplete and only handled some cases where the rules didn't exist for a certain field id. 
In particular, totally new fields (like the country code) were not just null, but in fact undefined.
This change causes it to detect the undefined rules and skip them in the same way.
Repro of the bug reported by Dan:
State after this fix:
=> bugfix: Handle undefined in addition to null rules for unrecognized fields

packages/server/src/arpa_reporter/services/records.js
None (reported via email by Alysha)
Partners have reported errors where empty rows in their workbooks are failing validation because required fields are empty. An inveidtigation showed that this is being caused by a new Display Only data type that we are using to include additional contextual info in certain tabs (e.g. including the subrecipients legal name, as found in other tabs, next to the subrecipient UEI/TIN columns.).
This new Display Only feature is causing the parser to think that empty rows are not empty. This updates the parser to remove any Display_Only data, and then skip a row if it is empty.
Before the fix, we see over 3000 errors:
After the fix we're down to only the real 13 problems in the file:
=> fix: ignore rows with only display_only fields

packages/server/src/arpa_reporter/services/validate-upload.js
#732
Partners in today's meeting mentioned that the warning about changed values to subrecipients are not helpful, and actually detrimental because they occur in such volume that it causes users to start skipping all warnings all together.
This PR turns off those warnings.
Before the change, we see warning whenever the data in a workbook doesn't match up with the data already saved in the db for a subrecipient: 
After the change, those warnings are gone:
=> #732: Shut off warnings for changes to subrecipients

packages/server/src/arpa_reporter/services/validate-upload.js, packages/server/src/arpa_reporter/services/validation-rules.js
https://github.com/usdigitalresponse/usdr-gost/issues/378
Right now, the validator backend can only really handle fields that are either always required for the particular EC code, or always fully optional. This causes a problem because many fields are actually "conditional": They may be required depending on values added for other fields in the row.
The most common form of this condition is that many fields are not required if the project status is 'Not started', but otherwise must be entered.
This PR creates a system that lets us configure a list of field ids that should include this new check: If we see that the data for the field is empty, and then we see that this field is conditional, and then we see that the conditional check says the data is required, then it will add a validation …
=> #378: First pass at conditionally required fields in ARPA validator

packages/server/migrations/20230104150018_add_email_subscription.js, packages/server/src/lib/email/constants.js
- Adds a table to store subscription preferences for agencies and their email notifications.
- This is based on the following RFC: https://docs.google.com/document/d/1TImE6llR6E-9Z3IKeXJjIElQ5P94UJhQT1jMgwMtRac/edit#
Note: I have reduced the complexity in this PR by keeping all the data in a single table. Hence, the divergence from the RFC. As the feature develops, I'll add additional migrations.
- Tested the migrations up and down locally
=> feat: adds table to store subscription data

packages/server/__tests__/db/db.test.js
The getNewGrantsForAgency test was failing locally for machines with different timezones due to a hard-coded date string. This fixes date math by moving to use Date objects instead.
#785
See above - due to timezone differences, a hard-coded date string meant to represent one day ago was in fact two days ago for anything less than GMT. Using `Date` for the desired end-date as well resolves this. 
```
x  yarn test
getNewGrantsForAgency
✔ returns zero grants if no grants match criteria and opened yesterday
✔ returns a grant whose modification date is one day ago
```
Run `yarn test` with a locally-running setup, verify that `getNewGrantsForAgency` passes. Run `docker compose exec app yarn test` ensure that docker-run tests also still pass.
=> fix: getNewGrantsForAgency test fails when run locally (#785)

packages/client/src/components/Layout.vue, packages/client/src/router/index.js
https://github.com/usdigitalresponse/usdr-gost/issues/617
Reordering the navigation tabs based on feedback from the NV partners. More details on the ticket above
Run the repo and go to `http://localhost:8080`. You should be redirected to `http://localhost:8080/#/my-grants`
=> fix(client): reorder grants tabs (#617)

.github/workflows/build-api.yaml, docker/production-api.Dockerfile
This PR tweaks the Docker builds used for staging and eventually prod environments to include additional build-time metadata in the runtime environment variables. Specifically, it makes these environment variables available within the containers:
- `BUILD_GIT_COMMIT`
- The (long) commit sha for which the container was built.
- Example: `b3610f88f49bde9647b3151f59b8091541a7a3a5`
- `BUILD_GIT_REF`
- The ref/branch name where the commit was pushed when the build was triggered.
- Example: `refs/heads/_staging`
- `BUILD_TIMESTAMP`
- The timestamp (in UTC) when the build was triggered.
- Example: `2023-01-13T19:47:38.438Z`
You can test the workflow locally using [act](https://github.com/nektos/act) (warning: it's complicated) or build the docker image directly and check the resulting …
=> 609: Add git metadata to docker env

packages/client/src/components/Modals/ProfileSettings.vue, packages/server/__tests__/api/agencies.test.js, packages/server/__tests__/db/db.test.js, packages/server/__tests__/email/email.test.js, packages/server/src/db/index.js, packages/server/src/lib/email.js, packages/server/src/routes/agencies.js
PR does 3 things that will help with launching the Email notifications feature:
1. Ensures that we take into account a user's subscription preferences before sending an email to them.
2. Manual trigger for sending out the grants digest email for a USDR super-user.
3. Fixes a bug that did not allow a user to unsubscribe from a subscription in the email notifications management UI
N/A
- Unit tests for all features added
=> feat: take subscription status into account

.github/workflows/build-api.yaml, .github/workflows/build-website.yml
This PR modifies the `concurrency.group` (concurrency group identifier) settings for disparate GitHub Actions workflows so that website builds do not cancel API builds, and vice-versa. It accomplishes by changing the identifier from `github.ref` (which is ref-/branch-specific) to `github.workflow_ref` (which identifies the specific workflow file in addition to the ref).
Currently, both the ["Build Docker image for GOST API"](https://github.com/usdigitalresponse/usdr-gost/blob/2d17fa9f204c4cd0ef7ea9eb994195a09355e267/.github/workflows/build-api.yaml) and ["Build GOST Website"](https://github.com/usdigitalresponse/usdr-gost/blob/_staging/.github/workflows/build-website.yml) workflows have workflow-level concurrency group configurations that are meant to ensure only the most-recent revision …
=> 609: Fix conflicting concurrency groups for build workflows

packages/client/.editorconfig
Removes the max line restriction from editorconfig, which conflicts with the restriction set by `eslint` and applies more broadly / less intelligently than the `eslint` restriction.
#839 
(see above)
N/A
This PR itself should not trigger the line-length restriction
=> fix: Remove max_line_length restriction from editorconfig (839)

packages/server/src/arpa_reporter/routes/audit-report.js
A quick typo fix!  I'm not sure how long this typo has been lying around in code, but I managed to run into this code path today.
=> Fix a typo in audit report console logging

packages/client/src/arpa_reporter/components/DownloadFileButton.vue, packages/client/src/arpa_reporter/components/DownloadTemplateBtn.vue, packages/client/src/arpa_reporter/views/Home.vue
This PR updates the Vue templates for several buttons in the ARPA Reporter client that set their `href` to an API-destined (file) URL. Since these don't initiate a request to the API backend via a `fetch` operation, they were passed over when the `apiURL()` helper function was being incorporated. As a result, the download links on AWS deployments don't point to a valid target file on the backend, and the downloads fail (the exact nature of the failure is browser-specific).
=> Fix: ARPA downloads failing on aws

packages/client/src/arpa_reporter/components/DownloadFileButton.vue, packages/client/src/components/Uploader.vue, packages/client/src/store/modules/grants.js
This PR addresses a few places in the ARPA Reporter client where the `fetchApi.apiURL()` helper was not being used to format URLs intended to point to the API backend. In Render, where the client and backend share the same domain name, it's easy for this to go unnoticed because browsers default to the current domain. However, this causes issues in environments where the API is hosted on a different domain, such as AWS.
Additionally, this fixes a bug (likely introduced in #864 ) that caused the "Download file" button to stop appearing on the Uploads tab of the ARPA Reporter client.
=> Fixes for API URLs pointing the wrong domain

packages/client/src/arpa_reporter/components/DownloadFileButton.vue
I jumped the gun in the last PR- the `href` computed property was referring to an unknown `upload` object and should have instead been referring to the bound (`this.upload`) object. This PR fixes that issue and (confirmed) makes the button show up again.
=> Fix: Use bound upload object when computing href

packages/client/src/arpa_reporter/views/ReportingPeriods.vue
This PR addresses an issue where the "Certify Reporting Period" flow results in a 403 response for the POST request sent to `/api/reporting_periods/close`. The underlying issue is the same as [some](https://github.com/usdigitalresponse/usdr-gost/pull/871) [other](https://github.com/usdigitalresponse/usdr-gost/pull/864) recent PRs: the URL for the request targets the domain name where the client is hosted, rather than the domain of the API. Like those other instances, the fix is to call the `fetchApi.apiURL()` helper function when the URL is being generated, which will ensure that the request targets the correct hostname for the API associated with the deployment environment.
=> Fix: Ensure Certify Reporting Period requests target the correct API domain

packages/server/src/arpa_reporter/services/validate-upload.js
fixes #813
make validation messages more descriptive by adding name of reporting period that it is being checked against.
Manually with an upload. Please let me know if there are additional tests I should add.
=> 86: better validation messages for reporting periods

packages/client/src/arpa_reporter/views/Uploads.vue
Fix the filtering logic so that we disable the validated filter when switching to exported only results
Fixes #861
=> fix: filtering by both validated and exported now works

packages/server/src/arpa_reporter/routes/users.js, packages/server/src/arpa_reporter/services/validate-upload.js
Fixes #616 
Fixes error when agency_id is 0. Since 0 is falsy in JavaScript, we need to explicitly
check for null or undefined.
=> fix: validation error when agency is 0

.gitignore, packages/server/.gitignore, packages/server/__tests__/arpa_reporter/server/services/persist-upload.spec.js, packages/server/package.json, packages/server/src/arpa_reporter/environment.js, packages/server/src/arpa_reporter/services/persist-upload.js, packages/server/src/arpa_reporter/services/records.js, yarn.lock
Audit report generation has been getting progressively slower, as we need to process more and more upload workbooks to produce the desired report.
The motivating idea behind this approach is that the single slowest part of audit report generation is not the logic, formatting or even disk access.  It is the `XLSX.read` operation.
Short of digging into this third party code, a minimally invasive way to optimise this expensive step is to introduce a cache layer.
Each upload, parsed as JSON is about a megabyte in size.  Our production ARPA tool manages about 1000 uploads today.  That's a little more data than I think we should be comfortable holding in RAM.  We could persist this cached content in our database, but parsing and printing JSON into a database involves overhead and adds load to …
=> 832: Use a disk cache (TEMP_DIR) to optimize audit report generation

packages/server/src/arpa_reporter/lib/audit-report.js
#374 
Adds status of completion to the audit file summary tab
Ran "download audit report" and verified that field was present in summary tab
=> fix: [Partner submission] Add 'Status of Completion' to Audit File (374)

docker-compose.yml
#944 
Fixes a race condition in our docker compose setup, whereby the app can attempt to connect to the db before it has been fully initialized. This change sets us up to wait for the database to actually be ready before attempting to connect.
More about this approach [here](https://docs.docker.com/compose/compose-file/#long-syntax-1) and [here](https://www.postgresql.org/docs/current/app-pg-isready.html)
N/A
Ran regular tests
=> fix: ECONNREFUSED for app in docker compose (944)

packages/server/__tests__/email/email.test.js, packages/server/src/lib/email.js
The code was initially ignoring the first two grants and building the email for the remaining. However, the logic should have been to ignore any grant beyond the first 3.
This bug was caused by a mistake in array slicing.
N/A
- Added unit tests
=> 951 fix bug with empty emails when there are fewer than 2 new grants

packages/server/__tests__/arpa_reporter/server/db/uploads.spec.js, packages/server/__tests__/arpa_reporter/server/seeds/01_roles.js, packages/server/__tests__/arpa_reporter/server/services/validate-data/index.spec.js, packages/server/__tests__/arpa_reporter/server/services/validate-data/validate.spec.js
Hey @NatHillardUSDR I think I rooted out that last test bug you ran into!
In the knex seed file, I think it's important to return your promises.  If you don't, it's not guaranteed that the next seed file won't start executing before the first finishes.
After resolving that, I found a couple more typos in import statements to requireSrc, but that was super straightforward!
I didn't want to presume to push directly to your branch, so I just pushed a separate branch.  This pull request just merges the changes back into your branch.  🙏
=> 839 nathillardusdr linter ahyndman

packages/server/__tests__/db/db.test.js, packages/server/__tests__/email/email.test.js, packages/server/src/db/index.js
- When I opted to use a more efficient query, I did not take into account a user's email subscription preference. This has caused emails to go out erroneously to users that had previously unsubscribed.
N/A
- Added better unit test coverage
=> fix: bug with user preferences not being honored

.github/workflows/build-api.yml
A bug in the "Build Docker image for GOST API" workflow was introduced in #977. To prevent test runs from publishing Docker images, the "Build and push Docker image" job's conditional `if` check had been modified to always evaluate to `false`, which was not changed back prior to deployment.
To fix, this PR removes the part of the  expression that was added for debugging, which reenables the intended behavior of pushing Docker images unless the workflow was triggered by a pull request.
=> 609: Fix #977

terraform/staging.tfvars
This PR prepares the new staging environment for DNS cutover.
Background: The AWS staging environment created a few months ago is hosted at `staging.grants.usdigitalresponse.org`. In preparation for further (production) migrations, a new staging environment was created to test the migration path (in this case, from "old staging" to "new staging"). Until now, the new staging environment, which is already managed by terraform in this repository, has been hosted at `staging2.grants.usdigitalresponse.org`. The changes in this PR updates references to  API and website hostnames so that they reside under `staging.grants.usdigitalresponse.org`. 
The net result of merging this PR is that both old and new staging environments are configured to host resources under …
=> INFRA: Prep (new) staging for dns cutover

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
This PR updates the query to use a `LEFT JOIN` instead of a `JOIN` since there is a chance that a `email_subscription` record does not exist for the vast majority of users.
N/A
To test this manually
- Pull branch down locally
- Run the following queries on your database (Note you can do most of this on the dashboard as well. I have denoted those tasks that have a UI by putting a [UI] prefix on them.)
- [UI] Pick a user you want to send email to `select * from users;`
- [UI] `delete from email_subscriptions where user_id = <your_user_id>;`
- `select * from grants limit 5` and pick a grand you want to update.
- Delete all agency's keywords `delete from keywords where agency_id = <your_users_agency_id>;`
- Ensure there is one keyword setup`insert into keywords (search_term, agency_id, type) …
=> fix: ensure users without preferences are subscribed

terraform/main.tf, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR updates the configured subdomains for sandbox and staging environments. The new subdomains are:
- Sandbox: `sandbox.grants.usdr.dev`
- Staging: `staging.grants.usdr.dev`
=> Reconfigure domains for sandbox and staging

terraform/main.tf, terraform/modules/gost_api/task.tf, terraform/production.s3.tfbackend, terraform/production.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR is a follow-up to #1038. Once merged, it will enable CI/CD workflows to target our AWS environment.
=> Configure terraform for production environment (#1038)

.github/workflows/build-and-deploy.yml
This is a follow-up to #1042. The deployment job didn't actually run (likely related to https://github.com/actions/runner/issues/491#issuecomment-850884422). The solution seems to be to include an `always()` expression in the conditional evaluation for the deployment jobs.
=> Ensure deployments don't get skipped under certain conditions

packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/src/arpa_reporter/lib/format.js, packages/server/src/arpa_reporter/services/validate-upload.js
The backend is incorrectly accepting arbitrary strings as the value for fields that are supposed to be numeric only. This PR adds a validation that will throw an error in that case, while displaying the value that caused the error to help the uploader find the error.
The majority of the code in this PR is actually an expansion of the testing code so that we can more easily write testcases to check validations in the validateRecord method. I added a test for this non-numeric case, but also added a test that verifies that missing required fields will throw an error
Test workbook includes these values:
Before the change, the validations show no errors:
After the change, we have new errors:
=> #1044: Throw error for invalid non-numeric vals

packages/client/src/arpa_reporter/views/NewUpload.vue, packages/server/__tests__/arpa_reporter/server/services/persist-upload.spec.js, packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/src/arpa_reporter/services/persist-upload.js, packages/server/src/arpa_reporter/services/validate-upload.js
Backend change to allow setting agency and reporting period in uploads. Not yet populated on the frontend.
DRAFT until I can verify a few scenarios / have a few examples to work against
Adding a simple change to apply the logic from the original ticket when uploading values for agencyId and reportingPeriodId
N/A, backend only change
* Not yet possible to test this, as values are not being populated in the UI, but you should be able to upload workbooks as usual without side effects
=> feat: support explicitly setting agency and reporting period in the ARPA Reporter upload api (#895)

terraform/main.tf, terraform/modules/gost_api/task.tf, terraform/modules/gost_api/variables.tf, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR cherry-picks aaa3b3e9cc5d549f96546fb3fe03c7eac32f63cb into `main` so that our workflows will deploy the new environment variable to prod.
=> Tsh/enable grants digest in tf (#1061)

terraform/main.tf
This PR updates the outbox name of the email address used by API containers to send emails. Prior to this change, the value was configured as `notifications@<website-domain>`; the new value is `grants-notifications@<websitedomain>`.
To verify changes, inspect the `terraform plan` output in the (forthcoming) posted comment and ensure that the following changes are present:
- The ECS task definition's map of environment variables changes the `NOTIFICATIONS_EMAIL` value. On staging, the new value should be `grants-notifications@staging.grants.usdr.dev`.
- The `send-emails` IAM policy's `SendEmails` statement should reflect the new email address in its `conditions` array.
N/A
=> Send emails from grants-notifications@website_domain

packages/client/src/components/GrantsTable.vue, packages/client/src/views/Grants.vue
Hide certain columns if it's on the browse grants page. 
Hide the following: 
- Opportunity Number
- Status
- Opportunity Category
Browse Grants
My Grants
- Go to my grants page. All columns should remain. 
- Go to browse grants page. The following column/data should no longer be there:
- Opportunity Number
- Status
- Opportunity Category
=> 889-hide certain columns on browse grants

packages/client/.vscode/launch.json, packages/client/.vscode/tasks.json, packages/client/arpa_reporter/scss/index.scss, packages/client/package.json, packages/client/src/arpa_reporter/App.vue, packages/client/src/arpa_reporter/views/NewUpload.vue, packages/client/src/arpa_reporter/views/Upload.vue, packages/client/src/arpa_reporter/views/Uploads.vue, packages/client/src/main.js, packages/server/.vscode/launch.json, packages/server/src/arpa_reporter/db/uploads.js, yarn.lock
Adds a form to set reportingId, agencyId, and notes in addition to uploading a file, using Vue-Formulate
NOTE! This patch needs to be applied alongside https://github.com/usdigitalresponse/usdr-gost/pull/1035 for the functionality to work! 
Once that has been merged / this is made on top, you should be able to go to Uploads -> Submit Workbook and specify an agency and reporting period
(N/A - we do not yet have FE unit tests)
NOTE: Setting as DRAFT for now in case @ajhyndman has another patch in the works / is planning on a different fix! Currently coordinating in slack.
=> Support freeform text notes on uploads (896)

packages/client/src/arpa_reporter/App.vue
I had erroneously removed the bootstrap js import when resolving a merge commit. This puts it back.
See above
Open the Reporting Period menu at the top of the screen - it should now open
(N/A until we've got Cypress set up)
=> fix: reporting period dropdown does not expand (#1076)

packages/server/.eslintrc.js, packages/server/__tests__/arpa_reporter/server/db/uploads.spec.js, packages/server/__tests__/arpa_reporter/server/environment.spec.js, packages/server/__tests__/arpa_reporter/server/fixtures/add-dummy-data.js, packages/server/__tests__/arpa_reporter/server/mocha_init.js, packages/server/__tests__/arpa_reporter/server/seeds/01_roles.js, packages/server/__tests__/arpa_reporter/server/seeds/07_reporting_periods.js, packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js
This pull request removes ignore rules for the last remaining JavaScript and Vue files in the packages/server/__tests__ directory of this repository.
Note that all changes in this pull request were manually applied. Everything that could be resolved via eslint --fix was committed in https://github.com/usdigitalresponse/usdr-gost/pull/1036.
BEFORE
AFTER
Test these changes by running yarn lint in the packages/server directory.
- ~Added Unit tests~
- ~Provided adequate test coverage for all new code~
=> Fix remaining ESLint errors in server/__tests__ directory

packages/server/__tests__/arpa_reporter/server/services/validation-rules.spec.js, packages/server/src/arpa_reporter/services/validation-rules.js
This PR aims to improve how we can enforce conditionally-required fields in ARPA reporter data (that is, fields that are sometimes required and sometimes not, depending on your answers to other questions).
This feature already existed in a hard-coded way, where we had a list of field ids that we knew should be treated as optional if the project status was "Not started".
This PR starts by refactoring that hard-coded feature in a way that is easier to add new conditions for new fields in the future. It creates a new `CONDITIONAL_REQS_CONFIGS` list for these configurations, and uses that to enforce the optional-if-not-started rules.
Then, in the second commit, I show how it is easy to add a new configuration. Here I added a rule that enforces that if the project status is "Cancelled", then …
=> #378: Improve conditionally-required fields

packages/client/src/arpa_reporter/views/NewUpload.vue
Earlier screenshots had this field present, but partners gave the feedback that it should be removed. It is not actually used in the BE so we can safely remove.
See above 
(Note that until we merge https://github.com/usdigitalresponse/usdr-gost/pull/1079 , the Agency Code is still showing "name"). 
Go to http://localhost:8080/arpa_reporter/new_upload , and inspect fields. "Expenditure Code" should not be present.
(N/A for FE changes for now until cypress)
=> fix: remove expenditure code field from NewUpload 

packages/client/src/arpa_reporter/views/NewUpload.vue
I had previously used "name" as the value for the dropdown, assuming "code" was a numeric code. It's in fact a string, and should be shown in this dropdown.
See above
Old:
New:
Go to http://localhost:8080/arpa_reporter/new_upload , expand the "Agency Code" dropdown.
(N/A for now until we have cypress tests)
=> fix: agency dropdown shows name, not code (#1078)

packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/src/arpa_reporter/services/validate-upload.js
UEI is now required for entities of type "Contractor" and "Subrecipient". Update our validation logic to reflect this.
Updates our validation logic to reflect new treasury rules.
Coming soon post confirmation of logic over on https://github.com/usdigitalresponse/usdr-gost/issues/1027
Upload a sheet with a Subrecipient row that is missing a UEI but is of type "Subrecipient" - you should see a validation failure
I am not sure I did the logic correctly for the db update -- see questions over at https://github.com/usdigitalresponse/usdr-gost/issues/1027
=> feat: unique entity id requirement emphasis (#1027)

packages/server/migrations/20230219162719_migrate_varchar_columns_to_text.js
This PR fixes a slight issue with the original implementation of #877 in PR #988 that caused the database migration to fail when there are no columns of type `varchar` that can be migrated to `text`. In this condition, the dynamic `alter table ... alter column ...` statements produced for each existing `varchar` column would yield a null result, causing the execution to fail with `query string argument of EXECUTE is null`.
The solution provided by this PR modifies the `select` expression that aggregates the dynamic `alter table ... alter column ...` statements so that it coalesces to a "no-op" query (simply `select 1;`) that gets provided to the as the "dynamic" argument to the `execute` rather than a null value.
In other words, this:
```sql
EXECUTE (
SELECT 
string_agg( ... ) # …
```
=> Fix: #877 Coalesce to no-op statement for dynamic execute query

packages/client/src/arpa_reporter/views/NewUpload.vue
- There was a bug where uploaded documents had a `null` agencyId.
=> fix: Ensures zero-agency-id can upload documents correctly

docker/README.md, docs/setup-mac.md, packages/client/src/components/GrantsTable.vue, packages/client/src/components/Modals/GrantDetails.vue
Hide multiselect labels which aren't necessary and cause overlap issues on smaller screens for certain components.
fixes usdigitalresponse/usdr-gost#984
Open the various Multiselects (4 on main grants table, 1 on grant details) and observe that "Press enter to select" label is gone. 
I didn't write a unit test since there aren't existing tests for these components (right?), and I think the Cypress stuff is just getting started. But if anyone would prefer I'd include one here, I'm happy to do so.
=> Hide multiselect labels on grants table and grant details

packages/client/src/components/EmailSettingsBanner.vue, packages/client/src/components/Layout.vue
Banner for letting users know that they can easily change their email subscriptions
manual testing steps:
- banner should show up when running app
- dismissed x button on banner should close the app
- settings should link to email preferences page to change them
- toggle should change email preferences for both grants and arpa tool
=> email settings banner

terraform/modules/gost_api/main.tf, terraform/modules/gost_api/storage.tf, terraform/modules/gost_api/task.tf
- Adds an S3 bucket to store audit-report files
- Confirmed the terraform validate and and plan CI action is able to create the correct resources.
=> feat: adds an s3 bucket to store arpa reporting data

packages/server/.env.example, packages/server/src/arpa_reporter/lib/audit-report.js, terraform/modules/gost_api/main.tf, terraform/modules/gost_api/task.tf
- We are unable to access the S3 bucket in AWS because the name of the bucket is different in the code than in the hosted environment. This PR ensures that we can set this as an environment variable which makes it easy to change across hosted environments.
=> feat: adds bucket name as env var

terraform/modules/gost_website/storage.tf, terraform/modules/gost_website/variables.tf
@TylerHendrickson the simple route to resolve this would be to just flip the bool to `true` in the module but I'm going to propose exposing it as an input variable so that it can be flipped on/off per environment (if needed).
=> fix: enable versioning for the Website CDN logs S3 bucket

packages/client/src/arpa_reporter/views/Home.vue, packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js, packages/server/__tests__/arpa_reporter/server/routes/audit_report.spec.js, packages/server/__tests__/lib/access-helpers.test.js, packages/server/__tests__/lib/redirect_validation.test.js, packages/server/package.json, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/lib/aws-client.js, packages/server/src/arpa_reporter/routes/audit-report.js, packages/server/src/lib/access-helpers.js, packages/server/src/lib/redirect_validation.js
- Ensures that only logged-in users can receive a presigned S3 URL to the audit report
=> feat: adds masking and auth for audit reports

packages/server/__tests__/arpa_reporter/server/routes/audit_report.spec.js, packages/server/src/arpa_reporter/routes/audit-report.js
- File signing in Staging was not working the same as the local environment. It turns out that there is some inconsistent behavior in the `getSignedUrl` function.
SSH into the staging server and try to retrieve the URL for the file.
```
const aws = require('../lib/aws-client');
const Key = `1/6/audit-report-2023-04-03-xxxx-aa99-4389-8f79-002e69ad2afa.xlsx`;
const baseParams = { Bucket: process.env.AUDIT_REPORT_BUCKET, Key };
const signedUrl2 = await s3.getSignedUrl('getObject', { ...baseParams, Expires: 60 })
> signedUrl2
'https://s3.us-west-2.amazonaws.com/'
const signedUrl4 = await s3.getSignedUrlPromise('getObject', {...baseParams, Expires: 60})
> signedUrl4
'https://xxxx-xxxx-us-xxx-x-api.s3.us-west-2.amazonaws.com/1/6/audit-report-2023-04-03-xxxx-aa99-4389-8f79-002e69ad2afa.xlsx?..... …
```
=> fix: update to use synchronous s3 file signing

terraform/modules/gost_website/cdn.tf
@TylerHendrickson this is a break/fix for the WAF integration with the Cloudfront CDN. WAFv2 needs to be reference by the ARN instead of the ID (which is now considered standard for using their old WAF).  This *should* fix the broke deploy that just failed to staging.
=> fix: WAFv2 needs to be referenced by ARN instead of ID

packages/client/src/views/UpcomingClosingDates.vue
Closes #279
We want the `/UpcomingClosingDates` page to look similar to `/RecentActivity`. Because RecentActivity makes use of an icon that is left-aligned, and the left column on UpcomingClosingDates is text, we just adjust the `<td>` for the left-most title column to have less padding and align visually with the header.
The updated `/UpcomingClosingDates` page:
The `RecentActivity` page for comparison:
=> Fix left padding on UpcomingClosingDates

terraform/modules/gost_website/waf.tf
See title.  The module's default value was set to `REGIONAL` which is incompatible when using WAFv2 with Cloudfront.
=> fix: Cloudfront only accepts globally scoped ARNs for WAFv2

.github/workflows/build-api.yml, .github/workflows/terraform-ci.yml, terraform/main.tf, terraform/modules/gost_api/task.tf, terraform/modules/gost_api/variables.tf, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR configures unified service tagging to enable Datadog discovery and metrics correlation. The net code changes involved are simply configuring values for a new `var.env` terraform input variable for each deployment environment (`prod` / `staging` / `sandbox`) and defining a `default_tags` block on the AWS provider.
It's worth mentioning that the Terraform plan (and subsequent apply) for this PR will touch a _lot_ of resources (pretty much all of them) since the default tags will be applied to [every AWS resource type that supports tagging](https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html) in this project. Policy conditions that evaluate and allow/reject conditional tags have already been applied to the CI/CD roles we use, and no resources are tagged at …
=> Configure AWS provider default tags for unified service tagging

terraform/modules/gost_website/waf.tf
I missed that the `default_action` parameter is set to `block` in this particular module.  This PR sets it to `allow` traffic once rules have been processed.
=> fix: set WAF default action to allow traffic after processing rules

.adr-dir, README.md, docs/decisions/.markdownlint.yml, docs/decisions/0001-decision-record-process.md, docs/decisions/README.md, docs/decisions/templates/template.md
Meta-proposal to use github to document decision records going forward.
N/A
N/A
N/A
N/A
=> [DECISION] Use Github to track technical decisions

packages/client/src/components/Modals/EditAgency.vue, packages/client/src/store/modules/agencies.js, packages/server/__tests__/api/agencies.test.js, packages/server/src/routes/agencies.js
Fixes #1431 
This PR implements the [short-term fix](https://github.com/usdigitalresponse/usdr-gost/issues/1395#issuecomment-1561730199) recommended for #1395. As described in that issue, users cannot delete agencies while they have associated users or sub-agencies. While these restrictions are expected behavior, the API currently does not check for these conditions or handle errors thrown when attempting to delete an agency with associated users and/or sub-agencies, nor does it inform users that the delete operation failed. This PR addresses those issues in the following ways:
- In the API: Before attempting to delete an agency from the database, the endpoint handler checks whether there are currently associated users or sub-agencies. If these conditions are met, the API responds with a …
=> Fix: #1395 delete agencies (short term solution)

packages/client/src/arpa_reporter/views/Uploads.vue, packages/client/tests/unit/arpa_reporter/views/Uploads.spec.js
Ensure that uploads are automatically sorted by latest validated at the top (#1386)
* added default sorting order to the Uploads page
* added test case for checking the Upload validated at sort dependency
Updated the default sort order to sort by Validated At descending.
Ran manual tests as per the below instructions.
Also added a unit test case.
- Check the page
- Change sorting multiple times
- Click "Reset Filters"
- Check sort
- Click "Group by agency?"
- Check sort
- Click "Reset Filters"
- Click "Only exported to treasury?"
- Check sorting
=> fix: #1386 - Default Sort Validated Desc

packages/client/src/components/GrantsTable.vue, packages/client/src/components/Modals/SavedSearchPanel.vue
Saved search list drawer modal opens on click of "My Saved Searches" button. Closes on click of close buttons in header and footer. Currently displaying empty state content.
=> 1450 - Saved Search List Drawer

packages/server/__tests__/arpa_reporter/server/db/uploads.spec.js, packages/server/__tests__/arpa_reporter/server/fixtures/fixtures.js, packages/server/__tests__/arpa_reporter/server/routes/uploads.spec.js, packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/migrations/20230619215513_add_exclude_for_uploads.js, packages/server/src/arpa_reporter/db/uploads.js, packages/server/src/arpa_reporter/routes/uploads.js, packages/server/src/arpa_reporter/services/validate-upload.js
This is only the backend piece. This PR adds an invalidated_at and invalidated_by to the uploads table. These can then be excluded by various reporting, such as the audit report.
This is just the backend portion, but can be tested by manually setting the `invalidated_at` and `invalidated_by` column and running the audit report.
=> fix: #1268 

packages/client/src/arpa_reporter/views/Home.vue, packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js, packages/server/__tests__/arpa_reporter/server/routes/exports.spec.js, packages/server/__tests__/email/email.test.js, packages/server/src/arpa_reporter/db/settings.js, packages/server/src/arpa_reporter/db/uploads.js, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/routes/exports.js, packages/server/src/arpa_reporter/services/generate-arpa-report.js, packages/server/src/arpa_reporter/services/records.js, packages/server/src/lib/email.js
This PR does the following:
1. Makes treasury report generation async and sends the user a signed S3 URL via email. Note: this is behind a query-parameter feature flag for the time being.
2. Ensures that treasury report generation does not depend on having an express js request/response context. It can be called independently by passing in the needed `tenantId` or `periodId` via CloudShell or other services.
3. Ensures that we are not passing in an unlimited number promises to be executed simultaneously. Currently starting with a limit of 2.
https://www.loom.com/share/ff1d5449c53a4545b1295e06229a5bbc
- Go to http://localhost:8080/arpa_reports?async_treasury_report=true
- Hit the "Send Treasury Report By Email" button
- Navigate to your local SES temp storage and identify the latest sent …
=> Treasury Exports - Implements async report generation

packages/client/.env.example, packages/client/public/deploy-config.js.example, packages/client/src/components/EmailSettingsBanner.vue, packages/client/src/components/GrantsTable.vue, packages/client/src/components/GrantsTableNext.vue, packages/client/src/components/SearchFilter.vue, packages/client/src/views/Grants.vue, packages/client/src/views/MyGrants.vue, terraform/modules/gost_website/runtime_config.tf, terraform/modules/gost_website/storage.tf, terraform/modules/gost_website/tpl/deploy-config.js, terraform/modules/gost_website/variables.tf
- Adds a new SearchFilter component which will display the chips for a current filter
- Until the state is handled in the parent, the component will remove by clicking close X or "clear all". This should probably be an emit later down the road.
- Per discussion at standup, I also split out the new search functionality into a copy of the `GrantsTable` component. The new one will display when `NODE_ENV='development'` (which should already be the case for us locally). 
Closes #1394 
https://github.com/usdigitalresponse/usdr-gost/assets/624510/b1e5cf43-9c70-46da-95c0-30ed280ef098
- With `NODE_ENV='development'`, confirm the filter chips display on the My Grants and Grants pages.
- Add/remove data from the `searchFilters`  variable in `GrantsTableNext.vue`. Observe display on the page.
**I …
=> Search chips

packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/src/arpa_reporter/services/validate-upload.js
Currently, there is no validation check for the Subaward City column for inclusion of the "." character. If the entries for this column contains a period, the portal kicks back an error in this field. In this PR, we're adding a check to make sure we catch this error before submission.
* Filled out a worksheet where `Primary Place of Performance City Name` under `Awards > 5000` contains a period:
* Sees validation error that the column contains a period:
- Unit test
- End to end testing
1. Fill out a worksheet where `Primary Place of Performance City Name` under `Awards > 5000` contains a period.
2. Upload worksheet.
3. Sees validation error that the column contains a period.
=> fix(server): add validation check for subaward city column

terraform/modules/gost_website/waf.tf
Reverts usdigitalresponse/usdr-gost#1613
See [this comment](https://github.com/usdigitalresponse/usdr-gost/pull/1613#issuecomment-1632924004) on the above issue, and [this bug report](https://github.com/cloudposse/terraform-aws-waf/issues/46) filed in the source repository for `cloudposse/waf/aws`.
=> Revert "chore(deps): bump cloudposse/waf/aws from 0.3.0 to 0.4.0 in /terraform/modules/gost_website"

.github/workflows/build-api.yml
This PR fixes an issue with the interpolation syntax in the `Build Docker image for GOST API` GitHub actions workflow. Instead of the `org.opencontainers.image.version` docker label being set to an identifier based on the build date/time, images are being built with the label set to a literal value of `"{{date 'YYYYMMDD.HHmm'}}"`.
As an discrete example, running `docker inspect` against the [current image tagged with `latest`](https://github.com/usdigitalresponse/usdr-gost/pkgs/container/usdr-gost-api/109462027?tag=latest) produces the following output (the last line in the JSON output is the important part):
```cli
$ docker inspect ghcr.io/usdigitalresponse/usdr-gost-api:latest|jq '.[0].Config.Labels'
{
"com.datadoghq.tags.service": "gost",
"com.datadoghq.tags.version": …
```
=> Fix: org.opencontainers.image.version docker label

terraform/staging.tfvars
This PR completely disables scraping in the Staging environment. Now that the grants-ingest pipeline is fully rolled out in this environment, any newly-scraped data is already being overwritten, so the net result for the Finder tool should be minimal/nil. The change here simply removes the daily-scheduled ECS task that starts the scraping process, which runs to completion (or fatal error).
In lieu of a screenshot, observe the resulting terraform plan that will be posted in the PR comments once the Terraform CI job runs. You should see the behavior that's described in item 1 in the **Testing** section of this PR.
Testing is simple: in a LocalStack environment, run `terraform apply` with `-var api_enable_grants_scraper=false` (or set the same in the relevant `.tfvars` file). Then, observe …
=> Disable grants scraper in staging environment

packages/client/src/arpa_reporter/views/Home.vue
- Enables the feature flag to open async treasury download more widely to all partners by default
- Allows ability to synchronously download treasury report if needed via query parameter.
Ran server locally and point to `localhost:8080/arpa_reporter`
=> feat: enable async treasury download by default

packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/services/records.js
This PR groups the report records by project and explodes the following columns by the reporting period:
- Total Aggregate Expenditures
- Total Aggregate Obligations
- Total Expenditures for Awards Greater or Equal to $50k
- Total Obligations for Awards Greater or Equal to $50k
This means, in the new project summary sheets, we are grouping records by project and creating a new column for every reporting period associated for that project.
1. Local DB has the following two records:
```
const records = [
{
type: 'ec5',
subcategory: "5.19-Broadband: 'Last Mile' projects",
upload: {
filename: '2023-06-22-Michelle_Testing.xlsm',
created_at: '2023-06-23T02:43:11.625Z',
reporting_period_id: 43,
user_id: 17,
agency_id: 0,
validated_at: '2023-06-23T02:43:12.277Z',
validated_by: 17,
ec_code: …
```
=> feat(1303): creating new project summary sheets

packages/server/src/arpa_reporter/lib/audit-report.js
When constructing the new summaries report for records grouped by project, we originally added the values from the record without checking whether it's null or not (as this check is not done in the [original audit report generation](https://github.com/usdigitalresponse/usdr-gost/blob/_staging/packages/server/src/arpa_reporter/lib/audit-report.js#L86)). As a result, this causes the summation to result in NaN, which throws an error when opening the report. [See slack thread for context.](https://usdigitalresponse.slack.com/archives/C031R1Y49KL/p1689792789275749)
This PR resolves any null values to 0 if the value we're adding doesn't exist.
[See slack thread for demo of the issue.](https://usdigitalresponse.slack.com/archives/C031R1Y49KL/p1689792789275749)
* Before the fix - Downloaded the …
=> fix(server): default to zero for null values in columns for new reports

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
- Ensures we always send the most recent saved search first in the backend.
http://ocalhost:8080/api/organizations/0/grants/grants_saved_searches
=> fix: make sorting most recent

.github/workflows/build-and-deploy.yml
This PR fixes a mis-named SSM parameter path used for configuring ECS deployment targets. It should fix issues where deploying new Docker images to the `consume-grants` ECS service is failing ([for example](https://github.com/usdigitalresponse/usdr-gost/actions/runs/5648626496/job/15301382164)).
=> BUG: Fix SSM deployment param path typo

packages/server/src/arpa_reporter/lib/audit-report.js
This PR adds a new column for `Capital Expenditure Amount` in the new project summary sheets, where records are grouped by project. To calculate the column we sum the records associated with the project by its `Total_Cost_Capital_Expenditure__c` value.
Additional changes involve adding the value from the records we're iterating and not the same record over and over for total obligations and total expenditures columns.
1. Local DB has the following two records:
```
const records = [
{
type: 'ec5',
subcategory: "5.19-Broadband: 'Last Mile' projects",
upload: {
filename: '2023-06-22-Michelle_Testing.xlsm',
created_at: '2023-06-23T02:43:11.625Z',
reporting_period_id: 43,
user_id: 17,
agency_id: 0,
validated_at: '2023-06-23T02:43:12.277Z',
validated_by: 17,
ec_code: '5.19',
tenant_id: 1,
id: …
```
=> feat(1303): add capital expenditure amount column to new project summary sheets

packages/client/src/components/GrantsTableNext.vue, packages/client/src/components/Modals/SavedSearchPanel.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/components/SearchFilter.vue, packages/client/src/helpers/filters.js, packages/client/src/store/modules/grants.js
Closes #1406, others
Multiple updates post demo
- Search form fills in when clicking edit from saved search panel
- Search form also fills in when clicking edit from table, if in a saved search
- Search criteria applies when clicking on a row in the saved search view
- Labels for saved search are formatted a little bit
- Fixed save button text
- Placeholder hover effect on saved search panel
https://github.com/usdigitalresponse/usdr-gost/assets/624510/b269436c-0034-4d2e-890b-bdd257eeffbd
1. Create a saved search or two
2. Open Saved Searches. Clicking on a search should apply its criteria to the current view.
3. Open Saved Search. Clicking kebab menu-> edit should open the criteria in the search panel. 
4. With a search open, you should be able to edit/save.
- The Saved Searches view …
=> Post-demo updates to saved search and search panel integration

packages/server/package.json, yarn.lock
Bumps the dd-trace library to 4.11.1.  This should enable support for the “Code Hotspots” feature.
=> Bump dd-trace to 4.x branch

terraform/main.tf, terraform/modules/gost_api/task.tf, terraform/modules/gost_api/variables.tf, terraform/modules/gost_consume_grants/compute.tf, terraform/modules/gost_consume_grants/datadog.tf, terraform/modules/gost_consume_grants/variables.tf, terraform/prod.tfvars, terraform/production.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR is a companion to @ajhyndman's #1756, which updated the `dd-trace` library to a version that has more debugging features.
This change sets a `DD_PROFILING_ENABLED` environment variable to `"true"` in Staging and Production environments, which is a requirement for [enabling the Node.js profiler](https://docs.datadoghq.com/profiler/enabling/nodejs/?tab=environmentvariables).
_Mostly_ unrelated, but this PR also moves the `POSTGRES_URL` env var in the `consume_grants` container definition out of plaintext and into a mapped secret env var. This is 99% unnecessary, but since the `postgres_username` input variable in terraform is marked as sensitive, including it in the plaintext env var mapping causes terraform plan output to hide all env var modifications, which isn't particularly …
=> Enable Datadog profiling in ECS

terraform/modules/gost_api/variables.tf, terraform/modules/gost_consume_grants/compute.tf, terraform/modules/gost_consume_grants/variables.tf, terraform/modules/gost_postgres/outputs.tf
This PR provides a fix for the issue that is causing the deployment for #1763's [commit to `_staging`](https://github.com/usdigitalresponse/usdr-gost/commit/f5892afb3d4f1339af604098ded8012e6dd801b6) to [fail when running `terraform apply`](https://github.com/usdigitalresponse/usdr-gost/actions/runs/5804332306/job/15733742321). 
**Problem:** In #1763, the `POSTGRES_URL` environment variable definition in the `gost_consume_grants` module was moved from the main container definition's `map_environment` setting to `map_secrets`. This was intended to be a shortcut to getting Terraform plan output to stop masking changes to nonsensitive environment variables, but was ultimately short-sighted, as the `map_secrets` map is intended to reference secret resources (SSM parameters or Secrets Manager …
=> FIX: PR 1763

packages/client/src/components/GrantsTableNext.vue, packages/client/src/components/SearchFilter.vue, packages/client/src/views/MyGrants.vue
Fixes #1757
- Remove tab border on My Grants, add underline style on hover
- Add more space between My Grants tabs and app tabs
- Match left and right margin
- Align Export CSV vertically with title/controls
- Remove pagination total at top of table
- Standardize title styles between My Grants and Grants
https://github.com/usdigitalresponse/usdr-gost/assets/624510/454198ec-eb6c-46fd-8efc-af53d293db6e
All visual updates to grants table in Grants and My Grants
=> Design feedback round 2

terraform/staging.tfvars
- Turns off the new search experience by default in staging. This ensures the old search experience still works.
- Since the new search experience removes two tabs, turning on the feature-flag does not bring back the keywords and eligibility tabs.
- By keeping this flag turned off in staging, we can see the old tabs and still interact with the old flow.
=> fix: turn off new table by default in staging

packages/client/src/views/Keywords.vue
Fix: Change Keywords heading in GOST frontend from `h3` to `h2`, to be consistent with other table headings.
| Before             |  After |
:-------------------------:|:-------------------------:
- [N/A] Added Unit tests
- [N/A] Added steps to test feature/functionality manually
- [N/A] Provided testing information
- [N/A] Provided adequate test coverage for all new code
=> fix: change Keywords heading from h3 to h2

terraform/modules/gost_api/task.tf, terraform/modules/gost_consume_grants/compute.tf, terraform/modules/sqs_consumer_task/compute.tf
This PR modifies a few container definitions to explicitly declare [dependencies](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDependency.html) on datadog containers, implementing a [suggestion](https://github.com/usdigitalresponse/usdr-gost/pull/1771#discussion_r1299267868) from @jakekreider in #1771. The ultimate change is to ensure that the datadog container has started before other containers that rely on the Datadog agent are allowed to start – this helps ensure that the agent can be reached by processes that need to send traces and metrics to it.
Summary of changes:
- `terraform/modules/sqs_consumer_task`: 
- Add a main task container dependency so that ECS waits for the datadog container to reach `START` status before the main container starts.
- Change …
=> Enhancement: Declare explicit Datadog container dependencies

packages/server/src/arpa_reporter/lib/audit-report.js
Adding logic to generate a new KPI sheets in the ARPA Audit Report. This sheet is similar to existing `Project Summaries V2` sheet [see previous PR](https://github.com/usdigitalresponse/usdr-gost/pull/1650) where we are grouping records by project except that we are displaying different columns.
In order to avoid making additional calls to generate this sheets, we have expanded the existing logic to create `Project Summaries V2` to also generate the rows for `KPI` (since both sheets are essentially using the same dataset).
1. Uploaded file and checked out exported report (screenshot above)
2. Able to see the KPI tab (and existing `Project Summaries V2`). Both tabs/sheets loaded without issues.
=> feat(1303): generate kpi sheets in arpa audit report

packages/client/src/arpa_reporter/store/index.js
Sets the `credentials: include` option when calling the `/api/sessions/logout` endpoint from the ARPA tool.
Without setting this options, fetch doesn't send the session cookie and express cannot tell the browser to clear the cookie, so the user stays logged in.
=> Include cookies in logout request to API endpoint

packages/client/src/components/GrantsTableNext.vue, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/db/index.js, packages/server/src/routes/grants.js
- Makes query accuracy improvements
- Also fixes the arpa audit report which is broken due to a mislabeled variable
=> fix: pagination and audit report

packages/server/src/arpa_reporter/lib/audit-report.js
Quick typo fix that I overlooked in #1732!
This function was missing a return statement.
=> Fix another typo that snuck into audit report generation

packages/server/src/arpa_reporter/services/persist-upload.js, packages/server/src/arpa_reporter/services/records.js
We shouldn't actually need to preserve any formula or HTML formatting when loading an upload from disk.  We can skip this parsing to save processing time, memory and disk space (when caching uploads to JSON).
This change also adds two new tracing spans, breaking down `jsonForUpload` into disk reading and JSON parsing components.  It also adds a file size tag to the `fs.readFile` span.
When testing locally, cached JSON file sizes shrink by 2–300 kB with these options set.
https://app.datadoghq.com/apm/trace/755985303388168448?colorBy=service&env=sandbox&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=755985303388168448&spanViewType=metadata&timeHint=1693184401669.03
1. Install and start up gost service locally and log in
2. Upload at least one [valid test …
=> feat(arpa): skip parsing of formulae and html

packages/client/src/components/Modals/SearchPanel.vue
To enable the save button we check that no values have been entered into the search form by checking looking at whether they are null or empty. The 'costSharing' field defaulted to false, which meant all searches start as save-able even before the radio button is clicked.
=> fix: ensure save button disabled for new saved searches

packages/server/src/db/index.js, packages/server/src/routes/grants.js
```sql
/* Query for retrieving all the data. The thing to note here is that it has not changed for the given set of parameters. */
SELECT DISTINCT "grants".*
FROM            "grants"
CROSS JOIN      To_tsquery('english', '(health) & !(fire)') AS tsq
WHERE           (
"tsq" @@ title_ts
OR              "tsq" @@ description_ts)
AND             (
"eligibility_codes" ~ '00|01'
AND             "grants"."opportunity_status" IN ('posted'))
ORDER BY        "open_date" DESC limit 50
/* New query that retrieves the totals. Note: it now counts the number of distinct grant_ids rather than  all columns.*/
SELECT DISTINCT Count("grant_id") AS "total_grants"
FROM            "grants"
CROSS JOIN      To_tsquery('english', '(health) & !(fire)') AS tsq
WHERE           (
"tsq" @@ title_ts
OR …
```
=> Fix: reduce query complexity for getting total grants

packages/server/src/db/index.js
```sql
SELECT     Count(DISTINCT "grants"."grant_id") AS "total_grants"
FROM       "grants"
CROSS JOIN To_tsquery('english', '(health) & !(fire)') AS tsq
WHERE      (
"tsq" @@ title_ts
OR         "tsq" @@ description_ts)
AND        (
"eligibility_codes" ~ '00|01'
AND        "grants"."opportunity_status" IN ('posted'))
```
=> fix: correctly apply distinct and resolve ambiguous column

packages/client/src/components/Modals/SavedSearchPanel.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/components/SearchFilter.vue, packages/client/src/store/modules/grants.js, packages/server/src/routes/grantsSavedSearch.js
- Ensure update operation is complete before fetching saved searches
- Stop click event on delete from propagating to parent row
- Return JSON from delete endpoint
- Ensure delete operation completed before fetching searches
- Add simple toast notification when deleting a search
- Always show "Clear" button if filters displayed
Delete toast
https://github.com/usdigitalresponse/usdr-gost/assets/624510/c0277caf-b695-4505-ab3c-15a230c926db
See bug tests and/or [Search QA for Demo](https://docs.google.com/document/d/1FXj7E8aA9pAMyWE6SSpupD-leMXznrBhOa7B_12HnjM/edit#heading=h.s7nbrmr29osw)
=> Saved search UI bug fixes

packages/client/src/components/GrantsTableNext.vue
- Reduces max-height of the grants-table by 150px. See: https://bootstrap-vue.org/docs/components/table#sticky-headers
- Goal here is to make sure the table renders with the pagination options on a 13" laptop
=> fix: resizes contents of grants table

packages/client/src/components/Modals/SavedSearchPanel.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/store/modules/grants.js
Adds a backdrop to each sidebar, which adds a dark backdrop to the rest of the page, and most importantly, closes the sidebar when the user clicks outside. 
https://github.com/usdigitalresponse/usdr-gost/assets/624510/db9af24e-ea36-4886-ad85-acde6f457902
Open/close both side bars through different means
=> Sidebar backdrop for grants search and saved search

packages/client/src/components/Modals/SearchPanel.vue, packages/server/__tests__/api/grantsSavedSearch.test.js, packages/server/src/routes/grantsSavedSearch.js
Shows a toast with red text when a user makes a second search with the same title.
[Screencast from 09-03-2023 06:15:08 PM.webm](https://github.com/usdigitalresponse/usdr-gost/assets/64168322/00ec1839-418c-413e-b24e-4b199cf525e4)
=> feat: display error message when search title already exists

packages/client/src/components/Modals/SearchPanel.vue
The issue I was able to reproduce on staging looks like a regression of the issue fixed in #1850 - the `await` was removed when the error message was added. 
Unless that was causing some other issue and this needs to be done async for some reason? 
Ensure saved searches refresh when editing.
=> Ensure saved search persisted before refreshing data

packages/client/src/components/GrantsTableNext.vue, packages/client/src/store/modules/grants.js, packages/server/__tests__/api/grants.test.js, packages/server/src/routes/grants.js
Migrating export To CSV to the new grants endpoint. Also ensures we are able to export the first 300 rows of any search criteria
=> Move export csv to grants next

packages/server/migrations/20230912195046_add-grants-opportunity-status-index.js
- Adds a partial index for non-archived grants.
```
usdr_grants=# SELECT indexdef FROM pg_indexes WHERE indexname = 'idx_grants_opportunity_status';
indexdef                                                                   
---------------------------------------------------------------------------------------------------------------------------------------------
CREATE INDEX idx_grants_opportunity_status ON public.grants USING btree (opportunity_status) WHERE (opportunity_status <> 'archived'::text)
(1 row)
usdr_grants=# reset work_mem;
RESET
usdr_grants=# explain analyze select distinct "grants".* from "grants" where ("grants"."opportunity_status" <> 'archived') order by "open_date" desc limit 50;
QUERY PLAN …
```
=> feat: adds index to opportunity_status field

packages/server/src/lib/email.js, packages/server/src/static/email_templates/_grant_detail.html
- Removes the per-grant "View All grants" button
=> fix: removes view all grants button from digest

packages/client/src/components/GrantsTable.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/store/modules/grants.js
- Search panel defaults to selecting Posted and Forecasted
- Search panel consolidates Closed and Archived
- Old search defaults to Posted and Forecasted
=> fix: ignore closed and archived grants by default

packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/services/records.js
In January, we ran into some performance bottlenecks in ARPA report generation.  At the time, the biggest issue was that XLSX parsing was both synchronous and the primary bottleneck, which could cause the server's main thread to lock up for the duration of report generation — preventing other requests from being served.
This issue was successfully mitigated by the introduction of `asyncBatch` with #834.  This improved on the situation by forcing the server to batch XLSX parsing jobs and "come up for air" between batches so that the server had the chance to handle additional requests before continuing report generation.
Following up on this initial mitigation, we introduced a filesystem cache layer for XLSX parsing (#942).
We are still seeing performance issues, but the situation is …
=> Parallelize Audit Report generation

packages/server/src/lib/grants-ingest.js
most grants have a pre-determined archive date and having this be behind a filter that enforces the date has to be <= today eliminates any ability of us to capture these dates
=> fix: ensure archive_date is captured always

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
- Fixes a parentheses issue within the `where` clause. This was causing the query to return all users even if only one user was passed into the function.
```sql
SELECT "grants_saved_searches"."id"              AS "id",
"grants_saved_searches"."created_by"      AS "created_by",
"grants_saved_searches"."criteria"        AS "criteria",
"grants_saved_searches"."name"            AS "name",
"email_subscriptions"."status"            AS "status",
"email_subscriptions"."notification_type" AS "notification_type",
"users"."tenant_id"                       AS "tenant_id",
"users"."email"                           AS "email"
FROM   "grants_saved_searches"
INNER JOIN "users"
ON "grants_saved_searches"."created_by" = "users"."id"
LEFT JOIN "email_subscriptions"
ON "grants_saved_searches"."created_by" = …
```
=> fix: emails being sent to all users

packages/server/__tests__/db/db.test.js, packages/server/__tests__/db/seeds/fixtures.js, packages/server/__tests__/email/email.test.js, packages/server/seeds/dev/ref/grantsSavedSearches.js, packages/server/seeds/dev/ref/users.js, packages/server/src/db/index.js, packages/server/src/lib/email.js
- The reason for wrong emails being sent is because the email service is passing in the raw `criteria` from the `grants_saved_search`. This PR ensures that: 
1. The email-service is formatting the input-filters correctly prior to sending it to `getGrantsNew` function.
2. The `getGrantsNew` function validates all input filters being passed in and sends back an appropriate error message. Note: the lack of a clear error message was the reason for a longer debug time for these issues.
To manually test:
Sample test URL:
http://localhost:8080/api/organizations/0/users/enter-your-local-user-id/sendDigestEmail?date=2021-08-05
=> fix: email notifications not sending the correct grants-set

packages/client/src/arpa_reporter/store/index.js
In #1838 I accidentally introduced a redundant call to `apiURL`.  I missed the detail that the `get` helper actually already injects the apiURL host for us!
=> Remove redundant apiUrl helper call

packages/client/src/arpa_reporter/views/Home.vue, terraform/modules/gost_api/task.tf
If tests from #1958 are not successful, we can use this as a PR to turn off audit report generation and mitigate risk for search  redesign launch.
=> chore: add service-down page for report generation

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
It looks like the total interested & rejected values were swapped (and had been for some time?). 
I didn't look into this, but it looks like the total count is maybe off too? Shouldn't  it be the sum of interested & rejected? I don't know the data model well enough to say so I left it alone. 
Assign and reject various grants, go to Dashboard. Total $'s should add up correctly.
=> Fix swap of interested and rejected totals

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
- 'Earmark' category was returning 500 errors this will fix it.
=> fix: adds earmark as valid option

packages/server/src/arpa_reporter/lib/audit-report.js
This PR is a follow-up to #1976. The results from the test run following deployment of #1976 were minimal; the program crashed after printing the following (abbreviated) log, emitted from [this line](https://github.com/usdigitalresponse/usdr-gost/blob/main/packages/server/src/arpa_reporter/lib/audit-report.js#L238):
<details>
<summary>Log output</summary>
```json
{
"id": "AgAAAYrUFNlsTK3RoQAAAAAAAAAYAAAAAEFZclVGT2piQUFDczdJaU1xQlRXQVFBSwAAACQAAAAAMDE4YWQ0MTQtZjFhOC00ZWQ2LWE5ZDEtNzYxNDUzYzY1YTVl",
"content": {
"timestamp": "2023-09-27T00:40:50.796Z",
"message": "generating sheets",
"attributes": {
"level": "debug",
"usage": "ARPA investigation",
"extra": {
"periodId": 175,
"domain": "https://grants.usdigitalresponse.org/arpa_reporter",
"tenantId": 9
},
"processStats": {
"memory": { …
```
=> ARPA audit report investigation: Round 2

terraform/main.tf, terraform/modules/sqs_consumer_task/variables.tf
This PR fixes an issue in #1992 where resources were being named incorrectly.
=> Fix: Namespace issue in `module.arpa_audit_report`

terraform/modules/sqs_consumer_task/compute.tf
Fix – just like it says on the tin...
=> Fix: Shorten arpa_audit_report role name to avoid character limit

terraform/main.tf, terraform/modules/gost_api/outputs.tf, terraform/modules/sqs_consumer_task/README.md
This PR adds a missing permission to the ECS task role defined in the `api` Terraform module, which allows publishing of SQS messages to the queue defined by the `arpa_audit_report` module. Although the `arpa_audit_report` module configures the SQS queue policy to accept messages from API tasks, we still need to give the task's role permission to publish SQS messages. Although it seems redundant (IMO) it makes sense to think of the SQS resource policy as an ingress rule (i.e. defines the allowed principals from which messages may originate) and the task role policy as an egress rule (i.e. defines what the task is allowed to do).
In other words:
- Problem:
- Bob is allowed to have friends over after school. _Bob is the SQS queue._
- Alice doesn't have permission to go to a friend's house. …
=> Allow API tasks to send messages to the `arpa_audit_report` SQS queue

packages/server/src/arpa_reporter/services/records.js
This PR allows the `recordsForUpload()` function in `packages/server/src/arpa_reporter/services/records.js` to gracefully fall back to a cache-less implementation when no request is active. Generally, the `useRequest()` function helps `recordsForUpload()` implement request-scoped memoization (specifically, for avoiding multiple reads of the same file in the same request), but it causes workflows that are not triggered by a request to fail when `recordsForUpload()` is called.
With these changes, when `recordsForUpload()` is called outside the scope of a request, it falls back to a function-local, empty object (which will be GC'd after the function returns). This is admittedly a bit of a hack, but I think it's worth the tradeoffs. If it turns out that, even in a task-based environment, …
=> Gracefully disable `useRequest()` cache when no request is active

packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js, packages/server/package.json, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/services/records.js, packages/server/src/scripts/arpaAuditReport.js, terraform/main.tf, yarn.lock
This PR contains a few minor changes related to ARPA audit report tasks:
- Additional logging to help debug outstanding task failures
- Set `VERBOSE=true` env var in audit report tasks for enabling additional log output
- Modify `generateAndSendEmail()` so that errors resulting from uploading to S3 and/or sending emails can be caught be callers. The previous behavior was for `generateAndSendEmail()` to catch and log these errors, but that prevents callers from being able to understand whether the operation was successful.
=> ARPA Audit Report tweaks: Round 1

packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/services/records.js, terraform/main.tf
This PR is a continuation of work started in #2011 and contains the following modifications:
- Removes some of the extra-verbose debug log output that is no longer needed.
- Fixes a usage `recordsForUpload()` as a callback for `Array.map()` in `packages/server/src/arpa_reporter/services/records.js`
- Ensures that tasks wait for `generateAndSendEmail()` to finish before returning (missing `await`)
=> ARPA Audit Report tweaks: Round 2

terraform/main.tf, terraform/modules/gost_api/outputs.tf
Third round of changes for fixing ARPA audit reports. In this PR, we're ensuring two environment variables are defined in consumer tasks:
- `API_DOMAIN`: Used to create download links for emails
- `AUDIT_REPORT_BUCKET`: Used to store generated audit reports
=> ARPA Audit Report tweaks: Round 3

packages/client/src/components/GrantsTableNext.vue, packages/client/src/components/Modals/SavedSearchPanel.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/components/SearchFilter.vue
Prevents clicking on buttons and links that would change a search already in progress.
=> fix: prevent changing search when results are loading

packages/server/src/arpa_reporter/services/persist-upload.js
This PR addresses an [issue](https://app.datadoghq.com/logs?query=host%3Agost-prod-arpa_audit_report-20230929025001186300000006%20service%3Acloudwatch%20%40aws.awslogs.logGroup%3Agost-prod-arpa_audit_report-20230929025001186300000006%20&agg_q=status%2Cservice&cols=host%2Cservice&context_event=AYr3AeoBAACEuU9IUhmOdwAD&event=&index=%2A&messageDisplay=inline&refresh_mode=paused&sort_m=%2C&sort_t=%2C&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAYr3AwJ-Jb8czwAAAAAAAAAYAAAAAEFZcjNBd29XQUFCc1N5Ylk3S0RCY0FBQQAAACQAAAAAMDE4YWY3MGUtYWEwMC00Yzc5LWJkZmQtOGQ4ZGIyNzBlNjFh&top_n=10%2C10&top_o=top%2Ctop&viz=&x_missing=true%2Ctrue&from_ts=1696360908775&to_ts=1696361284223&live=false) where the `persistJson()` function in `packages/server/src/arpa_reporter/services/persist-upload.js` throws an error …
=> Allow `persistJson()` to overwrite files

terraform/datadog_monitors.tf
One of our Datadog monitors is named incorrectly. Although it has been manually updated in Datadog, but since the monitor resource is managed by Terraform, it will eventually get overwritten. This PR resolves the issue by ensuring that the monitor is named correctly by Terraform.
=> Fix monitor name: "ARPA audit report job failed"

packages/server/__tests__/api/grants.test.js, packages/server/src/db/index.js
Creating an empty search from the client can cause a 500 if we try to order by a non-existent column.
=> fix: prevent empty search causing 500s

packages/server/src/arpa_reporter/lib/audit-report.js
This PR is a one-line change to ensure all arguments are provided to `createReportsGroupedByProject()` during ARPA audit report generation. The previous PR introduced this issue as a result of adding a new optional argument to `createReportsGroupedByProject()`, and passing that value during the call. However, I neglected to realize that the caller was relying on the previously-last argument's default, so this happened:
- Before #2036:
- Function signature: 
```js
async function createReportsGroupedByProject(periodId, tenantId, dateFormat = REPORTING_DATE_FORMAT) {
```
- Call (relies on the default `REPORTING_DATE_FORMAT`): 
```js
createReportsGroupedByProject(periodId, tenantId)
```
- After #2036:
- Function signature (new optional argument):
```js
async function …
```
=> Fix: Provide missing argument to `createReportsGroupedByProject()`

docker-compose.yml
Fix: Workaround for issue where Docker can't find the right image for an Apple Silicon Mac. Making this change will provide consistency for all contributors, ensuring everyone is working against the same emulated environment.
=> Fix: Set consistent arch for postgres to avoid Docker issue on Apple Silicon Macs

packages/server/__tests__/arpa_reporter/server/routes/audit_report.spec.js, packages/server/__tests__/arpa_reporter/server/routes/exports.spec.js, packages/server/__tests__/email/email.test.js, packages/server/__tests__/lib/grants-ingest.test.js, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/services/records.js, packages/server/src/lib/gost-aws.js
This PR provides further performance/reliability optimizations (and a few other tweaks) for the ARPA audit report. 
Summary of changes:
- Refactor the `createProjectSummaries()` function to only use a single Postgres query in order to build the report.
- Although the number of queries emitted over building this spreadsheet were not contributing to performance issues on the Postgres side, the number of queries executed in-parallel were maxing out the available number of (local) connections maintained by Knex. 
- The previous query patterns were to execute several deeply-nested queries:
- To find the current reporting period
- To find all previous (non-current) reporting periods
- For each identified reporting period, at least one query to find all uploads associated with the reporting …
=> ARPA audit report tuning: Round 2

terraform/main.tf
Just like it says – this PR enables debug-level logs for audit report tasks by setting the `LOG_LEVEL=debug` in the task's environment variables.
`LOG_SRC_ENABLED=false` is also set for good measure.
=> Enable debug logs for audit report tasks

packages/server/src/arpa_reporter/lib/audit-report.js
This PR fixes a bug introduced by #2060 by neglecting to enforce type-consistency for `Project ID` values in the `Project Summaries` spreadsheet for ARPA audit reports, which resulted in certain projects being represented more than once in that sheet.
**The problem**
Certain (possibly older?) uploads provide `Project ID` values as numbers, while others provide them as strings. Since we only want to include data from the _latest_ record pertaining to each individual project in the `Project Summaries` sheet, we need to ensure that `Project ID` values are unique. Prior to #2060, this was handled in an `Array.reduce()` operation that accumulated records into a plain JavaScript `Object` container, which implicitly treats all keys as strings. However, #2060 changed the way record data is used …
=> Ensure Project IDs are treated as strings

packages/client/src/components/GrantsTableNext.vue, packages/client/src/components/Modals/SavedSearchPanel.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/components/SearchFilter.vue
Prevents clicking on buttons and links that would change a search already in progress.
[Screencast from 10-06-2023 12:25:30 PM.webm](https://github.com/usdigitalresponse/usdr-gost/assets/64168322/02bb3b9e-9665-416c-9747-e4b189c20407)
=> fix: disable components while loading search results

packages/client/src/components/Modals/SearchPanel.vue
The b-form-checkbox-group doesn't always reflect the correct selection state when an option value is specified as an array instead of a string. This change adds the 'archived' when 'closed' is selected, and maintains that separately for the saved searches vs. the checkbox component.
[Screencast from 10-07-2023 06:40:10 PM.webm](https://github.com/usdigitalresponse/usdr-gost/assets/64168322/8489b288-9585-4c3e-bf24-336f62808ebe)
=> fix: inconsistent checkbox state for opp status

packages/server/src/arpa_reporter/services/records.js
- Fix project summary v2 tab by including missing sheets. The missing sheets caused some 0's for awards and expenditures. By adding back the sheets, the data is filled in.
Ran a version of the audit report and checked the Project Summary V2 tab.
=> fix: #1894 - Fix Project Summary V2 By Filtering Less Records

packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
Grants containing an include keyword without any exclude keywords in the title would be included in search results even if the exclude keyword appeared in the description and vice versa.
=> fix: exclude keyword not working with title and description

packages/client/src/components/GrantsTableNext.vue
Remove fixed attribute from grants table. 
Table cell content was overlapping when the window got smaller.  Remove fixed attribute so the table width can fit the content. When the window is wide enough, the table will fill the viewport width. When the window is too narrow, horizontal scrolling will be needed. This matches how the table on grants.gov works.
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/c4d716f6-b2b6-479d-8c1c-8034aab567ae
Tested grants view manually with a few saved searches.
=> fix: #2065 Results Table Horizontal Responsiveness Updates

packages/client/src/store/modules/users.js, packages/server/__tests__/api/users.test.js, packages/server/seeds/dev/ref/users.js, packages/server/src/lib/access-helpers.js, packages/server/src/routes/keywords.js, packages/server/src/routes/users.js
This PR adds a check to `/users` POST, PATCH, and DELETE to ensure the requesting user has access to the agency. 
This is done by checking that the agency is equal to the user's agency or is a sub-agency of the user's agency, preventing action against an agency above the user's agency in the hierarchy.
On the client, when a delete request fails, the error message is displayed.
Can be tested by deleting or adding a user in/from the parent agency of the logged in user.
=> 2134 admin access users outside allowed agencies

terraform/modules/gost_api/storage.tf, terraform/modules/gost_website/storage.tf
Fixes issue #1808 
- Update the terraform for S3 buckets arpa_audit_reports_bucket and logs_bucket to use the correct noncurrent_days parameter rather than days.
- Add new lifecycle rules for the origin S3 bucket to expire noncurrent versions after 7 days, and not expire or transition objects otherwise.
This replaces PR #2170 since that is in a forked repository that doesn't have AWS credentials so the terraform validation can't be run on it.
=> Add and fix configuration to expire non-current s3 objects

packages/client/src/components/GrantsTable.vue, packages/client/src/components/GrantsTableNext.vue, packages/server/__tests__/api/grants.test.js, packages/server/src/db/index.js, packages/server/src/routes/grants.js
Resolves the problem that sorting grants by 'Viewed By' and 'Interested Agencies' throws API errors.
On the frontend, the Viewed By and Interested Agencies columns are no longer sortable.
On the server, tightened up the input validation such that any values for `orderBy` other than `award_ceiling|open_date|close_date` are ignored completely.
Navigate to My Grants and Browse Grants and confirm that sorting is unavailable for Viewed By and Interested Agencies columns.
=> fix: remove sorting grants, Viewed By and Interested Agencies #1396

CONTRIBUTING.md
Update 'master' to '_staging' in Contributing documentation
=> fix: update 'master' to '_staging'

packages/client/src/views/RecentActivity.vue
Reverts usdigitalresponse/usdr-gost#2097
Change didn't have the intended effect, and more definition is needed about what we want this UI to represent.
=> Revert "fix: #949 update interested grants count labels"

packages/client/src/components/GrantsTableNext.vue
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/fb5ade1a-0dbf-4f2e-bd7c-5767136614a3
Test on mobile and with different window sizes
- [x ] Provided ticket and description
- [ x] Provided screenshots/demo
- [x ] Provided testing information
- [x ] Added PR reviewers
=> fix: #2273 use stacked table layout for narrow windows

.github/workflows/terraform-apply.yml, terraform/outputs.tf
(This PR is pretty much the same thing as https://github.com/usdigitalresponse/cpf-reporter/pull/40.)
This PR adds a step to the "Terraform Apply" workflow that invalidates the CloudFront distribution cache automatically after a successful deployment, which helps ensure that the latest-deployed version of the web app is being served.
A new Terraform output provides the ID of the CloudFront distribution. Once terraform apply is run successfully from the GHA deployment workflow, the next step in the job (which is conditional, but enabled by default) retrieves the output and runs the AWS CLI command to create a new CloudFront invalidation.
=> feat: Automatically invalidate CDN cache after deployment

packages/client/package.json, packages/client/src/arpa_reporter/main.js, packages/client/src/main.js, service.datadog.yaml, terraform/main.tf, terraform/modules/gost_api/gateway.tf, terraform/modules/gost_website/runtime_config.tf, terraform/modules/gost_website/tpl/deploy-config.js, terraform/modules/gost_website/variables.tf, terraform/prod.tfvars, terraform/staging.tfvars, terraform/variables.tf, yarn.lock
This PR adds Datadog RUM to the GOST website (both Finder and ARPA apps) and allows it to be conditionally enabled based on runtime configuration parameters, which is managed by Terraform. These changes will allow better observability for client-side behaviors and enable correlation of client-side API requests to server-side traces. Of particular note, this enables the ability to record and monitor (redacted/masked) user sessions, which should be beneficial for debugging as well as UX research.
Note that sampling rates for Staging are quite low, especially for replayable sessions (20% and 1%, respectively). In Production, 80% of sessions will be sampled and 20% of sessions will be available for replay.
Summary of changes:
- Add the Datadog RUM library as a client-side dependency
- …
=> Add Datadog RUM to client (issue #2067)

terraform/modules/gost_website/tpl/deploy-config.js
This PR removes an unnecessary call to `JSON.parse()` in the `deploy-config.js` Terraform template, which is currently preventing proper initialization of Datadog RUM in Staging.
=> fix: remove unnecessary JSON.parse() call in RUM config template

packages/client/public/deploy-config.js, packages/client/src/components/Modals/GrantDetailsLegacy.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/helpers/featureFlags/index.js, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars
Adds a feature flag for the new "Category of Funding Activity" search field, since there will be a delay in populating that field for all grants (see [Slack](https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1702502826238319?thread_ts=1702499999.626319&cid=C0324KDQSCR)) which is likely to cause confusion if users start using the search field. The flag will be enabled once we get all the data loaded.
The flag hides the "Category of Funding Activity" select input on the search panel and the same field on the legacy/current Grant Details page (the new in-progress Grant Details page doesn't have this field yet). Existing searches already created with this new search parameter will not be cleaned up but that shouldn't be a problem since no production users have had a chance to create …
=> feat: add feature flag for category of funding activity search field

packages/client/src/router/index.js
First step to match the design. Moving GrantDetails to be a child of Layout, so you get the header
Turn on the feature flag, and click to load a grant
- [x ] Provided ticket and description
- [x ] Provided testing information
- [x ] Added PR reviewers
=> fix: make new GrantDetails page a child of Layout

packages/client/src/views/Dashboard.vue
Fixes a console warning that occurs upon navigating to `Dashboard.vue`.
The PR just deletes unreachable code. It should have no effect on functionality.
=> fix: eliminate "property not defined on instance" error in Dashboard.vue

packages/client/src/views/Dashboard.vue
Use "team" property in Dashboard.vue where it had replaced "agency"
Use "team" property where it had replaced "agency"
Test Dashboard and RecentActivity
=> fix: #2312 agency Name not appearing on Recent Activity on Dashboard

.github/workflows/deploy-production.yml
Just like the title says, this PR addresses invalid argument order in a call to the [`startsWith()` GHA expression](https://docs.github.com/en/actions/learn-github-actions/expressions#startswith) used to determine whether a release needs to be updated following a Production deployment. The `startsWith()` function signature is `(searchString, searchValue)`, which is the opposite of our current usage, meaning the step will always be skipped.
The net result of this change should be that the "Update Release" job in the "Deploy to Production" workflow runs as long as the job was executed in the context of a release tag (which should pretty much always be the case).
This change is difficult to test outside of actually running it, which only happens when deploying to Production. However, this …
=> Fix `startsWith()` call in update-release condition

packages/server/src/lib/email.js, terraform/main.tf, terraform/modules/gost_api/task.tf, terraform/modules/gost_api/variables.tf, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
See ticket for description. This was a simple change except that it required adding a new server-side feature flag, named `api_enable_my_profile` in Terraform.
Steps to test:
1. Enable the server-side feature flag by adding `ENABLE_MY_PROFILE=true` to the .env file under packages/server.
2. Start up the app.
3. Log in as a user whose email you can receive.
4. Go to "My Profile" and make sure that the "Grants Assignment" toggle is on.
5. Assign a grant to your own organization.
6. Check your email for a "Grant Assigned" email.
7. Find the "Change Notification Preferences" link at the bottom of the email and verify that the link URL is "http://localhost:8080/my-profile" (or whatever website domain you have set).
Triggering a Grants Digest email is more complicated but feel free to check …
=> feat: update preferences link in emails to point to the new profile page 

terraform/prod.tfvars
This PR is a simple adjustment to the sampling rates configured for Datadog RUM in Production. Initial sampling rates were intentionally a bit conservative; after reviewing costs based on actual usage, it seems worthwhile to sample a bit more aggressively.
The new rates will sample all sessions in Production and make 80% of them available for replay analysis.
=> Adjust RUM sample rates in Production

packages/server/__tests__/lib/access-helpers.test.js, packages/server/__tests__/lib/grants-ingest.test.js, packages/server/src/lib/access-helpers.js, packages/server/src/routes/sessions.js
This PR adds the following:
1. Increases the number of clicks of the passcode link that will allow the user to login.
2. Ignores any requests originating from Microsoft Safe Links
=> fix: ensure we ignore microsoft safe links requests

.github/release-drafter.yml
This PR is a follow-up to #2433 and #2432. It removes the need to maintain a hard-coded year in the `.github/release-drafter.yml` config file.
Additionally, this PR adds a `# NOTES:` comment to the same file, which hopefully clarifies how the `release-drafter` action incorporates our precomputed `YYYY.inc` into the resulting release name and tag.
...at least, I think that's what these changes should do – it's awfully hard to test! 🤞
=> Update release-drafter config

packages/server/migrations/20240105223338_add_raw_body_jsonb_column_to_grants.js, packages/server/seeds/dev/01_main.js, packages/server/seeds/dev/ref/grants.js
During the grants ingestion process, we receive a JSON object representing a grant and pull it apart to populate various columns in the `grants` db table. We also store the raw JSON object in the column `grants.raw_body`, but we store it as `text` rather than as JSON which makes it less useful than it could be. This PR creates a migration that adds a column `grants.raw_body_json` of type `jsonb` and populates it from the `grants.raw_body` column.
Note that this PR doesn't fix the ticket by itself. A second PR will be required that either:
1. Runs a migration that populates `funding_activity_category_codes` from `raw_body_json` using the function described in the implementation notes for this ticket (but slightly simpler since we won't have to worry about the cast to json failing).
2. …
=> Add jsonb column to store raw body in grants table

packages/server/src/lib/access-helpers.js
This PR adds logging to capture request headers if we identify a request originating from Microsoft. The goal is to get an understanding of the volume of these requests and see if we are able to accurately intercept these requests purely based on the data present in the headers. Once we confirm that we are logging these requests appropriately, we can reduce the number of `MAX_ACCESS_TOKEN_USES` back down to 1.
N/A
N/A
=> chore: add logging around safe links requests

.github/dependabot.yml
This PR is simply a quality-of-life enhancement, which explicitly sets a time-of-day for Dependabot to run. Currently, Dependabot likes to run sometime during the afternoon. Since this is an active time for (human) developers, things end up getting slowed down when attempting to merge approved PRs, as frequent changes to `main` need to get merged into the PR branch, which re-runs CI workflows, etc. 
This PR schedules Dependabot runs for 3am Eastern (`America/New_York`), which will hopefully result in the bulk of automated updates completing during off-hours rather than in the middle of the day.
=> Set time-of-day for Dependabot schedules

packages/client/src/helpers/gtag.js, packages/client/src/main.js, packages/client/tests/unit/helpers/gtag.spec.js
I can't tell whether we're planning to drop Google Analytics in favor of Datadog RUM but, in case we're not, here's a feature that @jsandlund asked for. Any GA events recorded during a logged in session will now be associated with:
- an organization_name: this is the tenant name
- a team_name: this is the agency name
- a user_id: this is the database id, in accordance with the Google Analytics Terms of Service
> This includes avoiding the use of impermissible personally identifiable information, and providing appropriate notice of your use of identifiers in your Privacy Policy. Your user ID must not contain information that a third party could use to determine a user's identity.
Although I don't know whether we're obeying this part:
> providing appropriate notice of your use of …
=> feat: add user_id and user_properties to GA events

packages/server/src/arpa_reporter/db/arpa-subrecipients.js
=> ARPA subrecipients — invert null check typo

packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/services/records.js
- added awards < 50k for filtering records
- added two aggregate columns for awards < 50k on the audit report
We do not have testing setup for the audit report. It's a lot of mocking out data.
I tested this manually by running the audit report and checking the V2 tab.
=> fix: #2105 - audit report enhancements

packages/.gitattributes
`packages/server/src/static/forms/nevada_spoc.pdf` keeps showing up as modified, even though I haven't touched it, and I've gotten this warning:
> warning: in the working copy of 'packages/server/src/static/forms/nevada_spoc.pdf', CRLF will be replaced by LF the next time Git touches it
=> Add pdf to list of binary file types in .gitattributes.

packages/server/src/lib/email.js, packages/server/src/static/email_templates/_grant_detail.html, packages/server/src/static/email_templates/base.html
Added UTM tags to the URLs associated with the "View My Grants" button within an assigned grant email and the "Change notification preferences" link. 
Saved grant assigned emails in an HTML file format and could see the UTM parameters within the links associated with the elements.
=> Add UTM tags to Grant Email URLs

packages/server/.gitignore
Quick change to .gitignore rules to ensure that only the root `/data` directory in the server package.
=> Only .gitignore the root data folder in the server package

packages/client/src/arpa_reporter/main.js, packages/client/src/main.js
Added a call to Datadog's `setGlobalContextProperty` after initialization. Set grant finder tool context as 'finder' and arpa reporter context as 'arpa-reporter'. This enables us to easily distinguish the tools in analysis.
Global context is shown accordingly in the debug console as events are sent to Datadog.
=> Add app global context

packages/client/src/components/Modals/GrantDetailsLegacy.vue, packages/client/src/views/GrantDetails.vue, packages/server/src/lib/email.js, packages/server/src/routes/grants.js
=> fix: grants.gov url change

packages/server/__tests__/api/agencies.test.js, packages/server/__tests__/api/grants.test.js, packages/server/__tests__/api/grantsSavedSearch.test.js, packages/server/__tests__/api/keywords.test.js, packages/server/seeds/dev/ref/users.js
While working on https://github.com/usdigitalresponse/usdr-gost/pull/2540, we discovered it was easy to accidentally send real emails (if you've set up email following the doc here: https://github.com/usdigitalresponse/usdr-gost/blob/main/docs/setup-gmail.md). To make it even harder to accidentally send real emails externally, this PR removes all external email domains from the user seed data. 
We might eventually want to remove these NV users entirely from the seed data, since it seems the feature they relate to is deprecated and unused. However, they're currently used in various tests, so it seemed least disruptive to just change the domain.
Based on my searching, it doesn't appear these NV emails are part of any other processes besides these tests, but if they're in use somewhere I'm …
=> Update nv.gov emails to prevent accidental external emails being sent

.github/workflows/build.yml, .github/workflows/deploy-production.yml, .github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
Upgrades Github workflows to use v4 of `actions/upload-artifact` and `actions/download-artifact`. These have a few performance improvements, but primarily have longer-term support since they're running on node v20. 
I've configured all artifact uploads with `overwrite: true` since v4 makes artifacts immutable. In general use, I don't think this would be an issue for our setup (all artifacts have the git commit hash in their filename), but I believe it would break if you manually re-ran a workflow, which would cause the same filename to get uploaded again. In this case, I believe the overwrite behavior of removing the file, then re-uploading it, should work for us. 
I've so far been unable to test these changes. Maybe someone with a deeper understanding of GH workflows can help point me in …
=> Upgrade GHA usages of actions/upload-artifact and actions/download-artifact

docker/README.md, docs/setup-gmail.md, packages/server/__tests__/api/agencies.test.js, packages/server/__tests__/api/users.test.js, packages/server/seeds/dev/ref/users.js, packages/server/src/lib/email.js
Improves the new developer experience my making the standard login flow a bit clearer. It does this by: 
1. Creating generic admin and staff users in the DB seed script
2. Making the logs for the generated login URL stand out more
3. Update the docker setup documentation to walk through standard login flow in dev
4. Update the gmail setup documentation with a warning that you generally shouldn't need it
(This PR is based on the discussion here: https://github.com/usdigitalresponse/usdr-gost/pull/2524/files#r1470332892)
Manually ran the DB seed script and login flow for the admin and staff users
=> Clarify local development login flow

packages/client/src/views/GrantDetails.vue
Updates the new grant details page design, spacing, etc. to more closely match the [figma design spec](https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?type=design&node-id=1284-2779&mode=design&t=8cjFJ4wLmfpZBgQL-0). Specifically: 
- Two-column layout with right column fixed width
- Headline size and spacing
- Table data sizing and colors
- Update button design/spacing in right column
- Update agency status and assign grants section spacing and sizing
Note for reviewer: I had to re-indent and re-organize a lot of code in this PR, so the overall diff might be tough to read. I recommend reviewing commit by commit, which I've tried to keep pretty atomic and readable. 
Note that I tried to find the best compromise between the core components/tools bootstrap gives us vs the …
=> Grant details page design updates

packages/client/src/components/Layout.vue
Clicking top level nav bar items from grant details page doesn't work
Use named routes for the top level nav bar items
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/34b2ed41-5cd4-4bf1-b757-7db026f0478b
Enable grant details page feature flag. Click on a grant. Click on the Federal Grant Finder text at the top, verify you get to Browse Grants. Click back. Click on the My Profile link, verify you get to the My Profile page.
=> Clicking top level nav bar items from grant details page doesn't work

.github/dependabot.yml
This PR updates the repository's [Dependabot](https://docs.github.com/en/code-security/dependabot) configuration so that GitHub Actions dependencies (i.e. third-party actions) are kept up-to-date. Updates for this new ecosystem occur according the same daily-at-3am (America/New_York timezone) schedule as all other Dependabot runs.
Additionally, this PR includes a tweak to Dependabot behavior for all package ecosystems, which is simply to include the name of the ecosystem as a prefix for Dependabot commit messages. Currently, all Dependabot commits (and their corresponding PR titles) are prefixed with `chore (deps):` or `chore(deps-dev)` (the latter case is for NPM dev dependencies). Updating the prefix to include the ecosystem related to the changes (e.g. `Chore [deps:npm]`, `Chore …
=> feat: Add github-actions ecosystem to dependabot

packages/client/src/assets/adjust-vue-select.css, packages/client/src/views/GrantDetails.vue
Update dropdowns to be single-selection vue-selects. Add functionality to not require removing Team Status first when updating.
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/9dfd091b-1bd4-474e-9bbe-587bf6d8ecb5
Enable Grant Details Page feature flag. Make sure you can assign multiple teams to a grant. Make sure you can add, remove and update team statuses.
=> 2569 dropdown display for assign grant and team status

packages/client/src/components/Layout.vue, packages/client/src/router/index.js
This pull request addresses the issue related to updating the behavior of the Finder app as outlined in Issue #2585.
- When root path it will redirect to '/grants' instead of '/my-grants'
=> [issue-2585] Make Grants tab the default tab

packages/server/migrations/20240221163647_add_close_date_explanation.js
Step 1 of introducing close date explanations (for missing close dates) on the Grant Details page. (See https://github.com/usdigitalresponse/usdr-gost/pull/2647 for this step in context of the full plan.) 
Adds a db migration to add a `close_date_explanation` text field. (This will be populated in the upcoming steps, which will come as PRs to be deployed separately.)
Ran the migration locally forward and backward on a staging db dump, and verified the results in a psql shell
=> Grant details close date explanation, step 1

packages/client/src/arpa_reporter/views/Home.vue, packages/client/src/assets/adjust-vue-select.css, packages/client/tests/unit/arpa_reporter/views/Home.spec.js, packages/server/__tests__/arpa_reporter/server/routes/audit_report.spec.js, packages/server/src/arpa_reporter/db/reporting-periods.js, packages/server/src/arpa_reporter/lib/audit-report.js, packages/server/src/arpa_reporter/routes/audit-report.js, packages/server/src/arpa_reporter/routes/exports.js, packages/server/src/arpa_reporter/services/records.js
* periodId added as optional argument to backend reporting functions
* report download buttons available on closed reporting periods
* test cases added
This is a follow up from https://github.com/usdigitalresponse/usdr-gost/pull/2282
The last branch was too old, so I recreated it off of main.
See other PR
Run the application, run reports, choose different reporting periods, run more reports
=> fix: #1801 - closed period reporting

packages/server/__tests__/lib/grants-ingest.test.js, packages/server/src/lib/grants-ingest.js
**NOTE: This PR must deploy after #2648** 
Step 2 of introducing close date explanations (for missing close dates) on the Grant Details page. (See https://github.com/usdigitalresponse/usdr-gost/pull/2647 for this step in context of the full plan.) 
Updates the `mapSourceDataToGrant` method to pull `close_date_explanation` out of the milestones data for grants-ingest messages. 
Added unit tests for the new field
=> Grant details close date explanation, step 2

packages/server/migrations/20240221164356_populate_close_date_explanation.js
**NOTE: This PR must deploy after #2648** 
Step 3 of introducing close date explanations (for missing close dates) on the Grant Details page. (See https://github.com/usdigitalresponse/usdr-gost/pull/2647 for this step in context of the full plan.) 
Adds a backfill migration to populate the `close_date_explanation` column in the DB for all grants in the database. 
Ran the migration locally forward and backward on a staging db dump, and verified the results in a psql shell
=> Grant details close date explanation, step 3

packages/client/src/views/GrantDetails.vue
**Note: After a bit more thinking, this PR should be able to deploy in any order with respect to the other steps. It's resilient to even the DB column not existing yet; it'll simply display "Not available" for far-future close dates until we create and backfill the column. That's probably better than showing 2100 anyway, but it'll also only show up behind the grant detail page feature flag. All in all, should be safe to merge whenever!**
Step 4 of introducing close date explanations (for missing close dates) on the Grant Details page. (See https://github.com/usdigitalresponse/usdr-gost/pull/2647 for this step in context of the full plan.) 
Updates the grant detail page frontend to display better information when a grant has a far-future close date. If `close_date_explanation` is …
=> Grant details close date explanation, step 4

.gitignore, docker/README.md
Instructions for using docker compose override for anyone who wants to permanently enable db persistence in their dev environment.
=> Make it easier to enable Postgres persistence in dev.

packages/client/public/deploy-config.js
Given the new Grant Details page is nearly feature-complete and developers predominantly want the flag on in development (per discussion in this week's planning meeting), this PR flips the flag (in development only) to be on by default. 
Manually tested "Browse Grants" and "My Grants" grant tables all point to the new detail page.
=> Flip grant detail page flag on in development

packages/client/.eslintrc.js
Github PRs show outstanding check failures on every single PR's diff page, even though the failures are global and unrelated to the change. This is added noise that devs shouldn't have to think about. 
This PR should eliminate the eslint-based warning noise by aligning the eslint rules across all environments. (Previously, `yarn lint` and `yarn pre-commit` would run eslint with the "development" env, whereas `yarn build` would run eslint with the "production" env. This caused the warnings in CI that Github would display on PRs, even though they're not displayed in the course of the standard development workflow.)
Example of eslint warnings from a different PR: 
Screenshot of the warnings from this PR after CI ran — note it's only tflint warnings, but eslint warnings have been eliminated: …
=> Align eslint rules across environments

packages/client/src/views/GrantDetails.vue
Updates the Grant Detail page overall layout so page components align as described in the figma: https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?type=design&node-id=2017-27875&mode=design&t=T7gArjh1H06DndRw-4
**Review note:** The diff appears larger than the real change here. If you [ignore whitespace changes](https://github.blog/2018-05-01-ignore-white-space-in-code-review/) it should make the diff more readable.
=> Update grant details page overall layout

packages/client/src/views/GrantDetails.vue
Adds an email link for interested agency listings on the grant details page. 
Manually tested link shows up for assigned agencies, and that clicking opens an email compose in your default email client.
=> Add email user link to grant detail page

packages/client/src/components/Layout.vue, packages/client/src/components/Modals/EditUser.vue, packages/client/src/components/UserAvatar.vue, packages/client/src/helpers/constants.js, packages/client/src/views/GrantDetails.vue, packages/client/src/views/MyProfile.vue, packages/server/src/db/index.js
Adds the user avatar alongside the interested grant listings on the grant details page. In order to achieve this, the PR also does some refactoring/cleanup of the `UserAvatar` component and usage sites: 
- Remove the editable flag and color picker input from the `UserAvatar` component, and instead make that part of the EditUser modal component. (This is a better separation of concerns, and also helps decouple the current logged in user from the user displayed in `UserAvatar`.)
- Update the existing "call sites" using `UserAvatar` (`Layout` for the page header, and `MyProfile` where it shows your current user settings) to pass in the `loggedInUser` data to display. 
- Add `avatar_color` to the properties queried and returned by the API for interested agencies, so it gets returned alongside …
=> Add user avatar to grant details page

packages/client/public/deploy-config.js, packages/client/src/helpers/gtag.js, packages/client/tests/unit/helpers/gtag.spec.js, terraform/prod.tfvars, terraform/staging.tfvars
This PR accompanies the creation of a new Google Analytics property dedicated for non-Production usage. The motivation (wisely suggested by @sanason) is to provide a safe default for development use, which will hopefully discourage folks from using the Production property in non-Production environments (which would risk skewing its data).
Not much to see here.
1. Update `packages/client/public/deploy-config.js` so that `window.APP_CONFIG.GOOGLE_TAG_ID` is set to the property ID provided by the preceding line's comment.
2. You may also need to enable third-party cookies in your browser (or use a private/incognito browsing window).
3. Navigate to the Grant Finder client app in your browser and perform some actions.
4. Observe that network requests are being made to …
=> Add GA4 property configuration for non-Production environments

packages/client/package.json, packages/client/src/components/ActivityTable.vue, packages/client/src/components/ClosingDatesTable.vue, packages/client/src/components/GrantsTable.vue, packages/client/src/helpers/constants.js, packages/client/src/helpers/dates.js, packages/client/src/store/modules/grants.js, packages/client/src/views/Dashboard.vue, packages/client/src/views/RecentActivity.vue, packages/client/src/views/UpcomingClosingDates.vue, packages/client/tests/unit/helpers/dates.spec.js, packages/client/tests/unit/views/Dashboard.spec.js, packages/server/__tests__/db/seeds/fixtures.js, packages/server/src/db/index.js, packages/server/src/routes/grants.js, yarn.lock
This PR fixes a few problems with the Dashboard tab and its associated pages.
The pagination controls on both the `/RecentActivity` and `/UpcomingClosingDates` pages were weird looking:
- They were not horizontally aligned with the table.
- They had a strange button-looking but non-button box with some mysterious numbers displayed inside it.
These issues were fixed. Now the pagination controls look like the ones on the "Browse Grants" page. Also, I added the page number to the URL for `/RecentActivity` and `/UpcomingClosingDates`, so that clicking on a grant and then clicking "Back" takes the user to the most recently viewed page of results.
The Recent Activity table displayed the occasional strange looking row, consisting of just a grant name and a date. These occurred because there was …
=> Refactor and fix bugs in Recent Activity and Upcoming Closing Dates tables.

.github/release-drafter.yml
This PR updates the auto-generated release notes config so that PRs with the https://github.com/usdigitalresponse/usdr-gost/labels/database-changes label are grouped under a common heading. This should make it easier for releasers to check whether any Knex migrations are part of a release, which is necessary until we have an automated migration process.
Sneak preview ahead of #2750:
=> Flag DB migrations in release notes

packages/server/migrations/20240308203616_drop_grants_raw_body_column.js
This is a code clean-up PR. It contains a migration to drop the now redundant column `grants.raw_body`.
In https://github.com/usdigitalresponse/usdr-gost/pull/2435, we added a jsonb column grants.raw_body_json and populated it from the text column grants.raw_body. In https://github.com/usdigitalresponse/usdr-gost/pull/2454, we updated the grant ingestor to write to raw_body_json instead of to raw_body. In https://github.com/usdigitalresponse/usdr-gost/pull/2720, we deleted all code references to raw_body. It should be safe to drop the column now.
N/A
Run the migration, start up the app, click around and check that nothing is broken.
=> Drop the column grants.raw_body.

packages/server/__tests__/api/agencies.test.js, packages/server/__tests__/db/db.test.js, packages/server/__tests__/email/email.test.js, packages/server/__tests__/scripts/sendGrantDigestEmail.test.js, packages/server/src/db/index.js, packages/server/src/index.js, packages/server/src/lib/email.js, packages/server/src/routes/agencies.js, packages/server/src/scripts/sendGrantDigestEmail.js, terraform/main.tf, terraform/modules/gost_api/task.tf, terraform/modules/gost_api/variables.tf, terraform/modules/gost_consume_grants/compute.tf, terraform/modules/sqs_consumer_task/compute.tf, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
Grant Finder introduced user managed saved searches in https://github.com/usdigitalresponse/usdr-gost/issues/1370. Once this feature was in place, we started sending users grant digest emails based on their individual saved searches. Prior to this feature, Grant Finder was sending a different type of grant digest email, based on keywords and criteria set at the agency/team level. These agency-level digest emails are controlled by the `ENABLE_GRANTS_DIGEST` flag and have been disabled since Sept 2023. This PR deletes the feature flag and cleans up its backing code.
N/A
Check that sending grant digest emails still works:
1. In `packages/server/.env`, add
```
ENABLE_GRANT_DIGEST_SCHEDULED_TASK=true
ENABLE_SAVED_SEARCH_GRANTS_DIGEST=true
```
2. Do `docker compose up -d`.
3. Execute `docker …
=> Delete code for the old grants digest.

packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/src/arpa_reporter/services/validate-upload.js
* updated validation rules as per ticket 2944 for contractor / beneficienary / subrecipient
* exact logic is in the original ticket
Uploaded sample file and checked for validation breaks
=> fix: #2944 - updated contractor uei validation

terraform/main.tf, terraform/modules/gost_api/ecs_exec.tf, terraform/modules/gost_api/email.tf, terraform/modules/gost_api/logs.tf, terraform/modules/gost_api/postgres.tf, terraform/modules/gost_api/secrets.tf, terraform/modules/gost_api/storage.tf, terraform/modules/gost_website/storage.tf
While working on #2879 , I've been experimenting with using my own AWS account as a sandbox environment in which to test Terraform code. I [saw in Slack](https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1699478946709889) that @dysmento had tried this earlier. I've run into a couple of issues that I expect only occur when building the infrastructure from scratch. I don't know that it actually matters that we can build from scratch, but this PR tries to fix them because why not?
**Error 1:**
I received these error messages while running `terraform plan`.
```
│ Error: reading ECS Cluster (gost-sandbox): INACTIVE
│
│   with module.consume_grants.data.aws_ecs_cluster.default,
│   on modules/gost_consume_grants/main.tf line 23, in data "aws_ecs_cluster" "default":
│   23: data …
```
=> Tweak Terraform code to work when run against blank environment.

packages/client/package.json, packages/client/src/components/Modals/AddOrganization.vue, packages/client/src/components/Modals/AddTeam.vue, packages/client/src/components/Modals/AddUser.vue, packages/client/src/components/Modals/EditTeam.vue, packages/client/src/components/Modals/EditUser.vue, packages/client/src/components/Modals/SavedSearchPanel.vue, packages/client/src/components/Modals/SearchPanel.vue, packages/client/src/main.js, packages/client/tests/unit/components/Modals/AddOrganization.spec.js, packages/client/tests/unit/components/Modals/AddTeam.spec.js, packages/client/tests/unit/components/Modals/EditOrganization.spec.js, packages/client/tests/unit/components/Modals/EditTeam.spec.js, yarn.lock
Upgrades Vuelidate from 0.x to 2.x. This upgrade unlocks vite and/or vue3 upgrades, in addition to just plain keeping up with package upgrades. There should be no behavior changes introduced by this PR, but follows the [Vuelidate migration guide](https://vuelidate-next.netlify.app/migration_guide.html) to update our integration: 
1. Updates the installed packages
2. Removes vuelidate as a `Vue.use(...)` global plugin (it's now applied on a per-component basis)
3. Updates components to new usage patterns: 
- Each component has a `setup()` method to call `useVuelidate()`, which applies vuelidate behavior to the component.
- Vuelidate core and Vuelidate's built-in validators are now separate packages, so we update the imports accordingly. 
- We now call the vuelidate helper object `v$` …
=> Upgrade vuelidate

packages/client/.eslintrc.js, packages/client/babel.config.js, packages/client/src/arpa_reporter/views/ReportingPeriodsView.vue, packages/client/src/components/RecordUploader.vue, packages/client/src/helpers/constants.js, packages/client/src/helpers/fetchApi.js, packages/client/src/main.js, packages/client/src/mixin/resizableTable.js, packages/client/src/store/modules/agencies.js, packages/client/src/store/modules/dashboard.js, packages/client/src/store/modules/grants.js, packages/client/src/store/modules/roles.js, packages/client/src/store/modules/tenants.js, packages/client/src/store/modules/users.js, packages/client/vue.config.js
Migrates client codebase the final bit from CommonJS (`require(...)` and `module.exports`) to ES6 (`import` and `export`) style, and enforces this going forward in eslint. 
**Steps taken:**
1. Add a lint rule to disallow CJS style (and add ignore comments to project root config files that get executed in a CJS environment).
2. Replace remaining `require` and `module.exports` references with `import`/`export`.
3. Fix a circular dependency between `fetchApi` and `store` code. 
**Details on the circular dependency:**
Many of our store modules understandably rely on `fetchApi` to pull data from the server; meanwhile, the `fetchApi` code had a helper that automatically replaced `:organizationId` with the appropriate value from the store, based on the logged-in user. This caused a circular …
=> Migrate client code entirely to ES6 import style

packages/client/package.json, packages/client/src/arpa_reporter/views/LoginView.vue, packages/client/src/views/LoginView.vue, yarn.lock
Both login pages (Grants and ARPA) did ad-hoc validation of the login email field using the `lodash-checkit` library. This was undesirable for a couple reasons: 
1. The `checkit` library is intended to run in node environments, not browser environments, and it relies on e.g. `global` for some functions, which isn't present in the browser. Specifically, this becomes a blocker for switching to vite, in addition to being a bit dangerous in case someone eventually reaches for whatever checkit method actually references `global`. 
2. Ideally, it'd be great to eventually remove the lodash dependency from the frontend code to improve the bundle size, anyway. 
Since we're already pretty reliant on vuelidate for form validation, it seemed appropriate to migrate these forms to use that library for …
=> Replace lodash-checkit usage with vuelidate

packages/client/package.json, packages/server/package.json, yarn.lock
I noted a few unused dependencies in our client `package.json`, confirmed they are indeed unused, and removed them to ensure we're not building up codebase cruft. Specifically: 
- [core-js](https://www.npmjs.com/package/core-js) (library of polyfills for modern JS features in browsers)
- Added in the PR migrating ARPA into the GOST codebase: https://github.com/usdigitalresponse/usdr-gost/pull/302
- We’re only targeting evergreen browsers that pretty much support all modern JS, and regardless the library was never imported anywhere in our code, which means the polyfills were never actually used
- [vue2-filters](https://www.npmjs.com/package/vue2-filters) (collection of helpful Vue filters)
- Introduced in commit https://github.com/usdigitalresponse/usdr-gost/commit/bbe11d4a0b035a72f1f2ef8f2 …
=> Remove unused dependencies

packages/server/src/arpa_reporter/lib/audit-report.js
The audit report should source metadata for each project from the most recent project record, not the oldest project record.
=> audit report: source project metadata from most recent record

packages/server/__tests__/email/email.test.js, packages/server/src/lib/gost-aws.js, terraform/email.tf, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR does as the ticket describes. However, since we haven't fixed the problem noted in #2996 yet, this PR also adds a feature flag that disables all of the email tracking functionality that the configuration set is supposed to bring us. My plan is:
1. Merge this PR which should not break anything.
2. Enable email tracking in staging in the PR for #2996 and use staging to test that all of our emails still work correctly and that we are receiving email events in Datadog.
3. Enable email tracking in prod in a separate PR.
In [this PR comment thread](https://github.com/usdigitalresponse/usdr-gost/pull/2924#discussion_r1573065817), we discussed a different way of setting the configuration set used to send emails. My main takeaway from that conversation was that the different way was not an …
=> Send emails via SES using a configuration set.

packages/server/__tests__/email/email.test.js, packages/server/src/lib/gost-aws.js
Previous PR https://github.com/usdigitalresponse/usdr-gost/pull/2974 broke email sending on staging. Looking at logs in Datadog, the error is:
> AccessDenied: User `arn:aws:sts::357150818708:assumed-role/gost-staging-api-ECSTask-2023021701041477300000000a/b364e64fadbe43adba07741023661cc3' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:us-west-2:357150818708:configuration-set/gost-staging-default'
This PR undoes the code that adds the configuration set to emails, so as to fix email sending until the permissions issue can be addressed.
N/A
Once merged to staging, test that email sending is working:
1. Have a login passcode email sent from staging. Check that it was sent and that you received it.
=> Stop setting configuration set when sending emails.

packages/client/src/main.js
We noticed that the vue-select widgets were no longer rendering on staging, and the error was showing in console: 
After investigation, it looks like switching to `type: "module"` in `package.json` in #3089 changed how `vue-select` got imported, so this PR fixes our usage to register the component properly in this context.  
Verified the console error is now gone and the widgets render and function correctly on my devbox.
=> Fix vue-select component registration

packages/server/src/arpa_reporter/lib/audit-report.js
Fixes a bug in which project descriptions and expenditure category group could sometimes be missing from the audit report's "Project Summaries V2" tab.
While implementing the previous version of this feature, it slipped my mind that not all "records" generated from an upload are rows from the EC tabs.  Instead of blindly selecting the last record associated with a project and hoping that it is from an EC tab, this change filters for EC tab records explicitly and selects the last of those.
To test locally, upload the following input spreadsheet to your local instance and generate the audit report.
https://staging.grants.usdr.dev/arpa_reporter/uploads/ca1e3747-03fd-4477-9baf-aab9a911702c
BEFORE
AFTER
=> fix: project summaries v2 tab pulls metadata from last *EC* record

packages/server/src/arpa_reporter/db/uploads.js
Another attempt to fix #3088.
I think I worked out my mistake the first time around:
In the very first iteration of this audit report we used a WITH clause in our SQL query to try to select only the latest upload for each EC category + reporting period + agency.  In most cases this is sufficient to ensure that the audit report only reads the latest instance of each project and there is no conflict about which project details will be written into the audit report.
However, if the EC code that a project is written into changes, then that project may appear more than once in the set of "latest" uploads that we pull from the database.
In my last change, #3116, I attempted to correct for this by ensuring we always used the "last" upload with matching project info from the list returned by the …
=> fix: ensure uploads are sorted when fetched from DB

.github/workflows/code-scanning.yml
This PR fixes an issue introduced by the recent `actions/dependency-review-action` upgrade to [v4.3.3](https://github.com/actions/dependency-review-action/releases/tag/v4.3.3) in #3135. New API endpoints are now being called by this action, and those domains were missing from our `dependency-review` job's egress policy. This PR adds the following allowed endpoints:
- `api.deps.dev:443`
- `api.securityscorecards.dev:443`
See also https://github.com/actions/dependency-review-action/issues/736.
=> Fix failing `dependency-review-action` jobs

packages/client/src/views/MyProfileView.spec.js, packages/client/src/views/MyProfileView.vue
This change is part of the Assign-to-Share project. We want the copy within the Email Notifications settings to change if the feature flag `shareTerminologyEnabled` is set to true.
"Assign" copy:
"Share" copy:
I verified this change locally. `MyProfileView.vue` doesn't seem to have a corresponding test file yet. I've been on engineering teams where the process in this case would be to create a separate chore to write tests for `MyProfileView.vue` (especially since the change made in this PR is small). But if the process here is to commit a test without exception, then I may ask to pair briefly with someone on a unit test for this code (I'm not super familiar with Vue.js, and I hit my timebox for getting a test working on my own).
Manual steps for reviewer:
Navigate to `My Profile -> Email …
=> feat: update email preferences copy

terraform/prod.tfvars, terraform/staging.tfvars
This PR registers the client-side `shareTerminologyEnabled` feature flag in Staging and Production environments. By default, it is enabled in Staging and disabled in Production.
=> Deploy client-side `shareTerminologyEnabled` feature flag

packages/client/src/components/ActivityTable.spec.js, packages/client/src/components/ActivityTable.vue, packages/server/__tests__/db/db.test.js, packages/server/src/db/index.js
The Recent Activity log includes information about interested grants, rejected grants, assigned grants, etc. This change updates the language around assigned grants and includes the name of the user who shared the grant.
Last item in the Recent Activity table shows that a user shared a grant.
Navigate to the Recent Activity log (`/dashboard`). In order for an assigned grant to show up, the record in the `assigned_grants_agency` table must have a non-null `assigned_by` value.
=> Include assignee name in Recent Activity view

packages/client/src/views/GrantDetailsView.vue, usdr-gost.code-workspace
Update the Grant Details page main actions buttons to match expected state in the [Figma designs](https://www.figma.com/design/L2gfVMBH0x1daOlOe50sJl/Follow-%2F-Leave-a-Note?node-id=1101-13791&t=Co6m063mfZx7NQ1c-0)  
Moved to the right column, updated text and icons, updated "copy" and "print" to be links. 
Tested various window widths in local dev env
=> Grant Details Page - move grants.gov, copy, print buttons 

packages/server/migrations/20240622205204_add-grant-notes-table.js
Add a knex migration for issue #3200. 
Checked the table schemas in postgres CLI.
=> Issue #3200 Add grant_notes and grant_notes_revisions table migration

packages/server/__tests__/email/email.test.js, packages/server/src/lib/email.js, packages/server/src/static/email_templates/_grant_assigned_body.html
Update email templates for assign-to-share terminology
Added a new test with the SHARE_TERMINOLOGY_ENABLED environment variable set. Test covers that the new terminology is used.
=> Assign-to-Share: Update email templates

terraform/modules/gost_postgres/main.tf
This is done to resolve the various downgrading problems experienced when deploying to staging. For some reason currently unknown the postgres version in AWS is 12 rather than 8.
Since there is no configuration in terraform that is currently compatible with version 12 this PR bumps it to version 13 instead.
https://github.com/usdigitalresponse/usdr-gost/actions/runs/9767620685/job/27000430430
```
##[debug]Set output stdout = module.postgres.module.db.aws_rds_cluster.this[0]: Modifying... [id=gost-staging-postgres-20230217010405040800000006]
##[debug]module.api.aws_ecs_task_definition.default[0]: Creating...
##[debug]module.api.aws_ecs_task_definition.default[0]: Creation complete after 1s [id=gost-staging-api]
##[debug]module.api.module.grant_digest_scheduled_task.data.aws_iam_policy_docum …
```
=> bump: terraform version from 13.8 to 13.13

packages/client/src/components/Modals/SearchPanel.vue
With the Vue 3 migration PR merged (#3190) it seems submission behavior for bootstrap-vue's form is changed. It automatically counts an "enter" key while focused on the form to trigger the submit event. We had previously been handling both events individually, which thus started double-submitting that form, returning an error for a duplicate DB row. 
- Repro'd the issue without the fix (two requests in the network tab, with the second erroring)
- Introduced the fix and saw the desired behavior (only one request in the network tab, and no errors)
=> Fix issue with double-submission of new search

terraform/main.tf, terraform/modules/gost_postgres/main.tf, terraform/modules/gost_postgres/variables.tf, terraform/prod.tfvars, terraform/sandbox.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR adds explicit configuration for setting the SSL/TLS certificate for RDS Aurora Postgres in Terraform and sets values for the new config in each environment. Deploying this change to the Staging environment will trigger rotation of the current `rds-ca-2019` certificate to the new `rds-ca-rsa2048-g1` certificate. It will NOT affect the certificate on Production.
Note that #3273 updated the CA bundle file used to verify SSL/TLS connections. Previously, the bundle was only compatible with the `rds-ca-2019` certificate; the new bundle file is compatible with both `rds-ca-2019` and `rds-ca-rsa-2048-g1` certificates.
Per-environment configuration:
- Sandbox: 
- Certificate identifier: `rds-ca-rsa-2048-g1` 
- Effect: The certificate in this environment has already been manually rotated, …
=> Upgrade RDS certificate on Staging

terraform/prod.tfvars, terraform/variables.tf
This PR adjusts the configuration for the RDS Aurora SSL/TLS certificate in the Production environment. It also configures the `postgres_ca_cert_identifier` Terraform input variable with a default value of `rds-ca-rsa-2048-g1`, since that value is now shared by all targeted environments.
Note that #3273 updated the CA bundle file used to verify SSL/TLS connections, and #3286 applied the same configuration change in Staging. Now that we have successfully rotated the Staging environment certificate from `rds-ca-2019` to `rds-ca-rsa-2048-g1` without any problems or downtime, we should be able to safely apply the same upgrade operation while targeting Production. 
As with #3286, changes from this pull request will not take effect immediately. Rather, the upgrade will be a pending action for …
=> Upgrade RDS certificate on Production

packages/server/__tests__/db/db.test.js, packages/server/__tests__/lib/access-helpers.test.js, packages/server/__tests__/lib/grants-collaboration.test.js, packages/server/__tests__/lib/test-global-setup.js, packages/server/package.json, packages/server/src/lib/grantsCollaboration/index.js, packages/server/src/lib/grantsCollaboration/notes.js
Created the `saveNoteRevision` and `getOrganizationNotesForGrant` funcs as described in the ticket. Added some tests in `packages/server/__tests__/lib/grants-collaboration.test.js`. Was having some issues w/ the `knex` connection in a new file - the issue was that after 1 file destroyed the shared knex connection (`access-helpers.test.js`), it wasn't available to use in the next test file. To remediate this, I moved the before and after hooks into a util file, and called this file from the actual script in `package.json`. 
Technically I don't think this knex connection was ever even used in `access-helpers.test.js`, so I could probably have just gotten rid of the before and after hooks in this file, but I thought it might be better just to have these hooks in a global file so no one else …
=> feat(grants-collaboration): create library

packages/server/__tests__/email/email.test.js, packages/server/src/lib/email.js
Adding DataDog trace and span ids to email tags. Updated `email.test.js` to set default values for the tags.
=> Adding trace ids to email tags

packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/src/arpa_reporter/lib/arpa-ec-codes.js, packages/server/src/arpa_reporter/services/generate-arpa-report.js, packages/server/src/arpa_reporter/services/validate-upload.js
This addresses a few validation issues that were not resolved in #3371.
- declare ec code 7.3
- map ec code 7.3 to project baseline template in treasury exports
- add unit test coverage for new column IAA_Basic_Conditions__c
- validate commas in multiselect values after normalization
=> fix: support validation of projects with ec code 7.3

terraform/datadog_email_activity.tf, terraform/staging.tfvars, terraform/variables.tf
This PR fixes an issue introduced in 34c97ce83be83b70fd11f54eb3f6db6e654116ad. Terraform documentation [states](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/logs_custom_pipeline#target_format) that for `processor.attribute_remapper` blocks, the `target_format` may not be specified when `target_type = "tag"`. Currently, we specify `target_format = "string"` for all steps which convert a log attribute to a tag, so this PR fixes those usages by omitting usages of `target_format`.
Additionally, this PR modifies the creation of Datadog logs-to-metrics infrastructure for SES events so that they are only managed in Staging, which is necessary to avoid errors due to duplicate Datadog infrastructure.
=> Fix: Invalid `target_format` in SES logs-to-metrics pipeline

terraform/datadog_email_activity.tf
Follow-up to #3415 to fix a remaining stray usage of `target_format`, which I missed in the previous PR.
=> Fix: Invalid `target_format` in SES logs-to-metrics pipeline (again)

terraform/datadog_email_activity.tf
This PR fixes a typo in Terraform code that defines the source log attributes from which trace IDs and span IDs are remapped in the Datadog logs pipeline for SES email events. Previously the source attributes were defined as a single, comma-separated string value; they should each be separate member values of the `sources` list.
=> Fix: Typo in `trace_id_remapper.sources` list

terraform/datadog_email_activity.tf
This PR addresses two issues affecting Datadog logs-to-metrics infrastructure defined in Terraform:
1. Single quotes were being used, which apparently the Datadog API accepts literally. Now we are using escaped double quotes.
2. Incorrectly targeting `source:ses` instead of `source:sns`. This isn't particularly straightforward, but since these log events are delivered to Datadog via an SNS topic, Datadog considers that as the source of these logs.
=> Fix: Pipeline filter query

terraform/datadog_email_activity.tf
This PR modifies the Terraform infrastructure responsible for generating SES email event metrics in the following ways:
1. The pipeline has been updated to associate Trace IDs with log entries in a nondestructive manner. Since the [Trace ID remapper](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#trace-remapper) processor type always removes the source attribute, we first duplicate the trace ID at `mail.tags.dd_trace_id` to a (temporary) attribute, which is then removed by the Trace ID remapper.
2. Pipeline processing steps that were failing to execute have been fixed so that tags are remapped from the 0th index of the source attribute. This is necessary because SES tags are key/value pairs where the value is always an array; however, arrays (even when single-item) …
=> Add unified service tags to email metrics generated from logs

docker/production-api.Dockerfile
This PR fixes a Dockerfile casing issue (see [`FromAsCasing` build check](https://docs.docker.com/reference/build-checks/from-as-casing/)) that regularly surfaces as a PR check warning ([example](https://github.com/usdigitalresponse/usdr-gost/pull/3470/files#annotation_25988010942)).
=> Fix `FromAsCasing` build check error

packages/client/src/router/index.js, packages/client/src/store/modules/grants.js, packages/client/src/views/GrantDetailsView.spec.js, packages/client/src/views/GrantDetailsView.vue
- We were able to replicate this issue as a race condition from multiple grant tabs sharing a list of grants. 
- Resolutions for bugs on My Grants tab:
1. Race condition for tabs sharing same grants fetching API endpoint.
2. Duplicate route(s) causing match for first tab of `MyGrantsView` page and redirecting to page component without proper data (`tabNames`)
3. Direct mutation of vuex state outside of commit/mutation calls
- Steps to replicate: This issue can be reproduced by switching quickly between tabs on My Grants section where one return set is much larger than another (and returns from the server w/ delay).
=> Bug fix: My Grants showing all grants

packages/server/__tests__/arpa_reporter/server/db/arpa-subrecipients.spec.js, packages/server/__tests__/arpa_reporter/server/helpers/with-tenant-id.js, packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js, packages/server/migrations/20240918183745_drop_constraints_to_arpa_subrecipients.js, packages/server/migrations/20240918183915_add_name_to_arpa_subrecipients.js, packages/server/src/arpa_reporter/db/arpa-subrecipients.js, packages/server/src/arpa_reporter/services/validate-upload.js
This PR adds support for the new IAA subrecipient field. The goal here is to ensure that we can add subrecipients that do not have either a UEI or TIN value. In order to do this the PR does the following:
1. Adds a new `name` field to `arpa_subrecipients` table and a corresponding `unique index` that ensures that when both `uei` and `tin` are missing, that we do not create duplicate subrecipients with the same `name`.
2. Adds application-layer validation when `createSubrecipient` function is called.
3. Removes `unique` constraint on `uei` and `tin` fields and replaces with a `unique` index that only applies when these fields are `NOT NULL`.
```
usdr_grants=# \d arpa_subrecipients
Table "public.arpa_subrecipients"
Column       |           Type           | Collation | Nullable | …
```
=> 3372 - adds database changes to support managing IAA subrecipients

packages/client/src/views/MyProfileView.spec.js, packages/client/src/views/MyProfileView.vue, packages/server/migrations/20241004230649_add_grant_activity_to_email_subscriptions_notification_type.js, packages/server/src/lib/email/constants.js
On a users My Profile page, a Grant Activity toggle will be available and it will save the GRANT_ACTIVITY email preference
- [ X ] Added Unit tests
=> Feature: Grant Activity digest notification preference

packages/client/src/views/MyProfileView.spec.js, packages/client/src/views/MyProfileView.vue
Put Grant Activity preference in profile behind Follow Notes feature flag
=> fix: 3570 - feature flag in front of grant activity preference

terraform/modules/gost_api/task.tf
Fix for: <img width="339" alt="image" src="https://github.com/user-attachments/assets/69f23e87-bd00-489c-9469-c379beb02f36">
We received numerous reports of the reporter tool and finder tool not being accessible and returning a "Service Unavailable" error. Upon digging further there was no clear indication as to why these errors were caused and the current hypothesis is that it is due to the container running out of memory.
This change bumps up the memory of the container with the hope that there is a lesser chance of this happening again.
Note: the correct fix for this issue is likely the combination of these two tickets but they will be implemented separately:
#3622 
#3621 
N/A
N/A
No unit tests for terraform code.
=> chore: bump up the container memory and cpu temporarily to handle large volume of requests

packages/server/src/arpa_reporter/services/persist-upload.js, packages/server/src/lib/access-helpers.js
This PR instruments spans that identify various function calls within the route handler that accepts ARPA uploads. It also annotates traces for authenticated requests with certain (non-identifying) user data to more easily correlate observed request behavior with tenants and agencies.
These changes are all part of the `dd-trace` library, so should be no-op when Datadog isn't actuve.
=> Add tracing instrumentation for ARPA `POST /api/uploads` handler

terraform/main.tf, terraform/prod.tfvars, terraform/staging.tfvars, terraform/variables.tf
This PR sets the environment variable `DD_RUNTIME_METRICS_ENABLED = true` in Staging and Production environments, which enables [runtime metrics](https://docs.datadoghq.com/tracing/metrics/runtime_metrics/nodejs/?tab=environmentvariables) in Datadog APM. Typically, we observe metrics related to CPU and memory usage (as well as others) at the container level; collecting runtime metrics from the tracer itself should allow more granular inspection at the Node process level, and should make it easier to identify specific trace spans that contribute to high resource usage.
Additionally, this PR provides a new Terraform input variable, `default_datadog_environment_variables`, which helps consolidate Datadog configuration options that are generally common to all ECS tasks. Although it is useful …
=> Enable container runtime metrics

packages/client/src/views/LoginView.spec.js, packages/client/src/views/LoginView.vue
Update the bottom registration section to match Figma 
Approval from UX
[Slack request post](https://usdigitalresponse.slack.com/archives/C04UU76HR9D/p1728428403367969)
[Slack approval](https://usdigitalresponse.slack.com/archives/C04UU76HR9D/p1728435087330769)
Test Coverage 
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
**Before**
LoginView.vue |   34.61 |    33.33 |   22.22 |      36 | 1,22,57,109-136
**After**
LoginView.vue |   59.25 |    38.88 |   44.44 |   61.53 | 23,136-158
App
Ticket
New Jersey
href="https://forms.office.com/pages/responsepage.aspx?id=0cN2UAI4n0uzauCkG9ZCp7ITdp07WUhBmfHGHVfxwctUNVFJNFNPUllWSTBQNFZCQlMyMjlWWU5NUiQlQCN0PWcu&amp;route=shorturl" 
Nevada
href="https://forms.office.com/pages/responsepage.aspx?id=5kCj5J64aE6OqhVE0nA5gB …
=> feat(grants): login screen - update registration section text and links

packages/client/src/components/GrantActivity.vue, packages/client/src/store/modules/grants.js
- Adjust user/grant followers data fetching flow to remove unneeded api call
=> Bug: refine data fetching flow

packages/server/src/arpa_reporter/services/validate-upload.js
Picklist values were not being formatted correctly prior to comparison as part of a bug that was introduced in #3398  . This PR fixes it.
1. Download test file here: https://staging.grants.usdr.dev/arpa_reporter/uploads/0eb8c65d-76e2-47fa-8d05-369144772d7a
2. Try uploading and validating the file in `main` branch and see that the validation error shows up.
3. Go to the same upload after switching branches and click the "Validate" button and notice that no error shows up.
=> fix: ensure picklist values are formatted correctly prior to comparison

packages/server/migrations/20241118203005_cascade-delete-grant-notes-for-user.js, packages/server/migrations/20241118203302_cascade-delete-followed-grants-for-user.js
Adds `ON DELETE CASCADE` to FK references so that when a user is deleted, associated rows in `grant_notes` and `grant_followers` tables are also deleted.
=> Fix: cascade delete `users` to grant notes and follows

.github/dependabot.yml, .github/workflows/code-scanning.yml
This PR reduces noise from DevOps automations. Specifically:
1. Disables Dependabot upgrades for certain Terraform dependencies (`cloudposse/*` and `terraform-aws-modules/*`). Given that upgrading the Terraform AWS provider is a prerequisite for upgrading these dependencies, we should ignore individual updates until that work is complete. 
See also: #2379.
2. Disables CodeQL errors related to rate-limiting detection in `packages/api` JS code. We handle this at the infrastructure level rather than in runtime code, so these errors are not useful.
=> Reduce automation noise

docs/decisions/0011-use-testing-library-vue.md, packages/client/package.json, packages/client/src/arpa_reporter/views/HomeView.spec.js, packages/client/vitest.setup.ts, yarn.lock
Add support for testing-library/vue to be able to use accessible queries and update vitest package version.  
From [Testing Library Docs on queries](https://testing-library.com/docs/queries/about/#priority) 
>  Based on [the Guiding Principles](https://testing-library.com/docs/guiding-principles), your test should resemble how users interact with your code (component, page, etc.) as much as possible. With this in mind, we recommend this order of priority:
Queries Accessible to Everyone Queries that reflect the experience of visual/mouse users as well as those that use assistive technology.
Note:
Opened this PR to add support for accessible queries using the embedded version of testing-library from vitest
[PR #3635 - Update vitest and add support for browser tests …
=> chore(gost): update vitest version and add testing-library for accessible queries

package.json, packages/server/package.json
This no-op PR is a long-overdue tweak that updates our `package.json` files to reflect the actual state of the world. Specifically, it removes `author` and `repository` fields. Both of the previous values in both files were inaccurate, and furthermore are unnecessary in projects that do not provide distributable software (i.e. libraries).
=> Address outdated package.json files

packages/server/src/routes/grants.js
This PR attempts to fix the issue described in #3856, which is causing CSV export requests for Grants search results to result in a 500 response (only in Staging environment).
The issue is captured in Datadog [here](https://app.datadoghq.com/error-tracking/issue/ae08c734-cc4e-11ef-b282-da7ad0900002?query=env%3Astaging%20service%3Agost&from_ts=1736107423790&to_ts=1736193823789&live=true), with a specific error trace of:
```
TypeError: Cannot read properties of undefined (reading 'map')
at /app/src/routes/grants.js:151:14
at Array.map (<anonymous>)
at /app/src/routes/grants.js:137:32
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
The above error indicates that `grant.followed_by_agencies` is `undefined` rather than an empty array. This is because the …
=> Guard inclusion of `grant.followed_by_agencies` array data during CSV generation

packages/server/src/arpa_reporter/lib/audit-report.js
I'm not able to reproduce the staging bug locally but these guard clauses will ensure that the value defaults to zero when the project has missing/insufficient data. The rest of the testing instructions supplied below are to generally test to make sure the feature works which still works.
The latest value of $35,000 is being picked.
The KPI tab is returning the summation of two values $100,000 and $35,000 to return $135,000.
1. Retrieve the two uploads needed to test from this directory here: https://drive.google.com/drive/folders/1YCnXLi-j3k8m3qktKrt9MRf20B5YsUDD
2. Upload both workbooks in the order `FIRST_UPLOAD` then `SECOND_UPLOAD` into the app through the Submit Workbook Flow. http://localhost:8080/arpa_reporter/new_upload
3. Verify that both uploads are validated.
4. In a separate …
=> fix: ensure there is guard clause to catch issues when projects are missing EC records

packages/server/src/arpa_reporter/services/generate-arpa-report.js
Upon investigating partner complaints of missing data in the treasury report for `Personnel_Estimated_Expended` field. I noticed that they were missing from the mapping entirely.
=> fix: ensure all the fields of subawardBulkUpload.csv are being populated

terraform/main.tf
Fixes an issue where the gost API tasks in ECS fargate don't have permission to publish to the `arpa_exporter` SQS queue, which prevents them from kicking off full file export tasks.
[Example error log in datadog.](https://app.datadoghq.com/logs?query=status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZUqVCI5zZEghAAAABhBWlVxVkRJMEFBQnpwbGdaZkxKRUZBQUQAAAAkMDE5NTJhNTQtNDNlMy00YzYyLWJjNWMtM2Q5MGE5ZjczZGU0AAAABw&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1740171040691&to_ts=1740171940691&live=true)
=> Fix: Allow API tasks to publish to arpa_exporter queue

.github/workflows/deploy-staging.yml
This PR fixes the following error
```
Stopped reason
CannotPullContainerError: pull image manifest has been retried 1 time(s): failed to resolve ref ghcr.io/usdigitalresponse/usdr-gost-arpa-exporter:9f3f04ba74d338f28372c252c68e0e2eb8a65185@sha256:cca4a767de7ae6d33db8dcc9bb0452db96d042327c37a85515fe8612881477f7: ghcr.io/usdigitalresponse/usdr-gost-arpa-exporter:9f3f04ba74d338f28372c252c68e0e2eb8a65185@sha256:cca4a767de7ae6d33db8dcc9bb0452db96d042327c37a85515fe8612881477f7: not found
Stopped: 22 minutes ago
```
=> fix: ensure that we are using the correct digest for the arpa exporter image url

terraform/main.tf
This PR reverts 166f981f4fa5a31aa78f3d7c3c5af79e54a0398a and adjusts the `arpa_audit_report_rw_reports_bucket` policy document to add `HeadObject` permissions for the audit report bucket. This is intended to fix a permissions issue encountered by FFE tasks:
```
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```
=> Fix: allow `HeadObject` to report bucket on ARPA tasks

terraform/main.tf
This PR adds `ListBucket` permissions on the audit report bucket to FFE tasks. It's intended (along with the previous addition of `HeadObject` permissions in #4040) to fix the "Forbidden" error that these tasks are getting when running `download_fileobj()`.
=> Allow ARPA Exporter tasks to ListBucket

arpa-exporter/src/worker.py, terraform/main.tf
- The data directory is supposed to be `/var/data/uploads` however, the task was looking for files within `/var/data` instead.
- This PR updates this `DATA_DIR` variable definition.
=> fix: upload file path definition

arpa-exporter/src/worker.py
Fixes error:
```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:sts::357150818708:assumed-role/gost-staging-arpa_exporter-Task-20250221195902062300000003/c2595ec184cb4eb19b3ccb00f671b778 is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::gost-staging-arpaauditreports-357150818708-us-west-2-api/full-file-export/org_13/archive.zip" with an explicit deny in a resource-based policy
```
=> fix: ensure s3 put-object has the correct encryption specified

packages/server/__tests__/arpa_reporter/server/routes/exports.spec.js, packages/server/__tests__/arpa_reporter/server/services/full-file-export.spec.js, packages/server/src/arpa_reporter/routes/exports.js, packages/server/src/arpa_reporter/services/full-file-export.js
- The s3-key used by the endpoint to get signed URL is using a different key than the one used by the python-task.
- This PR ensures that all keys are consistent.
=> fix: ensure that the file-export keys are consistent

.github/workflows/deploy-production.yml, terraform/datadog_monitors.tf
- Full File export is not getting kicked-off in production due to the following error:
```
Stopped reason
InternalError: failed to create container model: failed to normalize image reference "ghcr.io/usdigitalresponse/usdr-gost-arpa-exporter:". Launch a new task to retry.
Stopped: 37 minutes ago
```
The issue is the image reference is incorrect. This PR updates that reference.
=> fix: add arpa-exporter-image details to prod

.github/workflows/deploy-production.yml
This issue fixes a bug that is [currently](https://github.com/usdigitalresponse/usdr-gost/actions/runs/13571210991/job/37937042995) causing our [Deploy to Production](https://github.com/usdigitalresponse/usdr-gost/actions/workflows/deploy-production.yml) workflows to fail during the "Update release" job. Although the deployment is successful, this final step (which uploads and associates artifacts with the GitHub release) fails because the base names of the artifacts are not unique (although they are located in unique directories in the GitHub Actions runner, so the naming clash is only related to the upload). The bug was introduced in #4049 due to the inclusion of artifacts for `usdr-gost-arpa-exporter` Docker images, which currently have the same filenames as the `usdr-gost-api` …
=> Fix: Ensure release artifacts have unique filenames

.github/release-drafter.yml
This PR fixes the regression introduced in https://github.com/release-drafter/release-drafter v6.1.0. See [this issue](https://github.com/release-drafter/release-drafter/issues/1425) for more information on the nature of the problem.
Specifically, this PR resolves the problems we've been having with duplicate draft pre-releases being created when commits are pushed to `main`.
=> Fix regression in release-drafter

arpa-exporter/src/lib/logging.py, arpa-exporter/src/worker.py, arpa-exporter/tests/conftest.py, arpa-exporter/tests/src/test_worker.py, packages/server/__tests__/arpa_reporter/server/services/full-file-export.spec.js, packages/server/src/arpa_reporter/services/full-file-export.js
This PR fixes a bug that is currently resulting in duplicate entries being created in FFE zipfiles produced by `arpa-exporter`. Currently, we attempt to avoid writing duplicate files by checking for the presence of the zip path (from CSV metadata's `path_in_zip` value) in the existing contents of the zipfile. However, Python performs some amount of normalization to these values when writing entries, so files that require normalization (i.e. are not zip-compatible) are considered missing. Since zip files allow for duplicate entries, one current problem is that subsequent runs of `arpa-exporter` will (at minimum) duplicate the size of the zip file.
In our case, this problem is manifesting because we check for absolute paths in the zipfile, but zipfiles normalize absolute paths to relative …
=> Fix duplicate entries in FFE zipfiles

arpa-exporter/src/lib/email.py, arpa-exporter/src/worker.py, arpa-exporter/tests/conftest.py, arpa-exporter/tests/src/lib/test_email.py
This PR makes a few minor improvements to Full File Export email notifications sent by `arpa-exporter` task workers, mostly aimed at bringing parity to emails sent by other (Node.js) parts of gost:
1. It adds a configurable display name to the `From` header on emails so that modern inboxes display the sender as (default) `USDR ARPA Reporter`, which matches other ARPA-related emails sent by gost.
2. SES emails are sent under the configuration set named by the `SES_CONFIGURATION_SET_DEFAULT` env varPrimarily, this ensures that SES email events for Full File Export are propagated to Datadog logs and metrics, which is also the behavior for other gost emails. 
3. SES emails are tagged so that logs and metrics can be used to debug and analyze FFE email behavior, which also allowing these them …
=> FFE: Add tags and use SES config set when sending emails

packages/server/__tests__/arpa_reporter/server/services/full-file-export.spec.js, packages/server/src/arpa_reporter/services/full-file-export.js, terraform/modules/gost_api/storage.tf
This PR does the following:
1. It attempts to test out the new S3 IAM policy configuration to see if it fixes the 403 error issue.
2. It doesn't block the rest of the process of creating the file-export in the event that S3 throws an exception. The reason for this is to unblock testing the rest of the functionality while we're debugging the permissions issue.
=> Fix: updates the IAM permissions as well as report generation functionality to handle S3ServiceException

packages/server/__tests__/arpa_reporter/server/services/full-file-export.spec.js, packages/server/src/arpa_reporter/services/full-file-export.js
- Users notified us of not being able to see uploads that were missing an agency code. When looking into the code it looks like the query to pull-in uploads from the database has a hard-requirement for this to exist. This PR removes the requirement and handles the scenario when EC code and Agency values are missing gracefully.
=> fix: allow to pull-in uploads without an agency code

packages/server/src/lib/email.js
This PR introduces two API server environment variables, `ENABLED_EMAIL_TYPES` and `DISABLE_ALL_EMAILS`, which allows emails to be selectively enabled or else entirely prevented from being sent. This behavior manifests as a module level constant array, `ENABLED_EMAIL_TYPES`, which will contain some subset of values from the `tags.emailTypes` object in `packages/server/src/lib/email/constants.js`.
- `DISABLE_ALL_EMAILS` env var: When set to a non-empty value, no emails will be sent, regardless of other environment configuration.
- `ENABLED_EMAIL_TYPES` env var: When set, is expected to provide a comma-separated string of zero or more email types (per the types defined in `packages/server/src/lib/email/constants.js`):
- When the environment variable is unset or an empty string, all email …
=> Use environment variables to configure allowed email types

packages/client/public/deploy-config.js, packages/client/src/arpa_reporter/views/LoginView.vue, packages/client/src/helpers/featureFlags/index.js, packages/client/src/views/LoginView.spec.js, packages/client/src/views/LoginView.vue, terraform/prod.tfvars, terraform/staging.tfvars
This PR adds four feature flags:
* grantsTransitionMessageEnabled
* arpaTransitionMessageEnabled
* grantsLoginEnabled
* arpaLoginEnabled
and associated behavior:
* showing a message on each login page encouraging users to go to the Nava instances
* disabling the input elements for each login page
This PR also enables the messages in all environments, and disables login for ARPA in all environments.
Here is what this looks like with message on and input disabled:
I have enabled/disabled the flags locally and they behave as I expect, using the `deploy-config.js` mechanism.
=> feat: add flags for nava transition to disable login/add a banner

terraform/prod.tfvars, terraform/staging.tfvars
This PR toggles the `grantsLoginEnabled` flag in Staging and Production environments in order to disable the form on the Grant Finder login page. Users will (still) be presented with a banner message that directs them to access the tool hosted by Nava PBC. 
This also toggles the `disable_all_emails` flag in both environments so that no emails will be sent. Since this flag supersedes the `enabled_email_types` flag, the latter has been left in its current configuration in order to allow for minimal code changes in case the flag changes needs to be reverted in a particular environment.
=> Disable Finder login and all emails

.github/dependabot.yml
This PR modifies our Dependabot config so that all updates for the `github-actions` ecosystem will be grouped into pull requests based on whether they are `applies-to: security-updates` or `applies-to: version-updates` (i.e. all security updates go into one PR group and all version updates go into another PR group).
Grouping updates for this ecosystem will cut down on PRs for this ecosystem, hopefully making review a bit easier. We have limited QA checks (mostly related to linting) for this ecosystem, so it's unlikely that this change would result in CI workloads failing for one bad update.
Note that this change only affects PRs with `minor` and `patch` semantic versioning changes; any dependency with a major version change will still get its own pull request.
=> Create GHA version-updates and security-updates groups

.github/workflows/qa.yml
This resets the `tj-actions/changed-files` third party action to [v46.0.3](https://github.com/tj-actions/changed-files/releases/tag/v46.0.3).  The current commit hash points to the head commit of the `main` branch for that repo and the associated version comment is incorrect/out of date.
Not sure if this was a Dependabot issue or due to a typo when this action was first introduced into the QA workflow. Discussions related to a recent [security issue](https://github.com/tj-actions/changed-files/issues/2464) for this action suggest that some of the tags may have been affected, so that may be related.
=> Realign commit hash and version tag for tj-actions/changed-files
