- README.md
- packages/server/.env.example
Renaming the database to not include cares for this fork of the grants work
> New database name

- README.md
- usdr-gost.code-workspace
Pulling CARES name out, updating README
Resolves #5
> Minor workspace updates

- packages/client/src/components/Layout.vue
addresses #49 by changing text on tab bar.
> chore: changed grants tab language to browse grants

- packages/server/src/lib/grantsgov.js
Reverts usdigitalresponse/usdr-gost#75
> Revert "fix: ensure eligibility code searches include forecasted grants"

- packages/server/src/lib/grantsgov.js
Reverts usdigitalresponse/usdr-gost#76
> Revert "Revert "fix: ensure eligibility code searches include forecasted grants""

- packages/client/src/components/Modals/EditAgency.vue
- packages/client/src/store/modules/agencies.js
- packages/client/src/views/Agencies.vue
- packages/server/src/db/index.js
- packages/server/src/routes/agencies.js
Issue #85 
Issue Solution:
Added "name," "abbreviation" and "parent agency" input fields to allow the agency to be updated.
Added "admin delete agency" that only allows users to delete the agency. Confirmation shows up after clicking. If the user is not an admin, then it will be greyed out and show a tooltip on hover. 
Screenshots:
1.) The new fields and button for the edit agency modal
2.) Input in one field will update the agency for that field only
3.) Agencies table reflects changes after form submission. (The column for the name is so long because I have all of the agencies on the table, so it adjusts the column size to the length of the longest name).
4.) If the user is "admin," then the button will not be greyed out and will be clickable. After clicking it, a popup appears to …
> #85 Edit/Delete Agency Functionality

- packages/client/public/index.html
Add basic analytics to website
Data being tracked: (you can see the one user in the last 30 minutes which was me)
Here is the google analytics ID and code to be put in the index.html file which matches the changes being commited
Tested on my local by opening multiple instances of the website in incognito tabs which all tracked as separate users visiting the website
> issue 47 - add analytics 

- packages/client/src/views/Dashboard.vue
Reverts usdigitalresponse/usdr-gost#134
> Revert "111 template agency table"

- packages/client/src/views/Dashboard.vue
Completes the integration of the front and backends for the agency activity table. A formatter function to format the values as currency has been added.
See monetary values formatted with commas and two fractional digits.
mark grants as interested -> check dashboard tab to make sure values update and are formatted correctly in the agency activity table
> 143 Integrate agency activity table front and backend

- packages/client/src/components/GrantsTable.vue
- packages/client/src/views/Dashboard.vue
- packages/server/src/db/index.js
Some bug fixes for the staging branch, worked with @cavukovic 
Activity feed:
Currency formatting:
Test the activity feed in the top left of the dashboard, try marking some agencies as interested. Also observe the currency formatting in the grants table and verify that columns are still sortable.
> 169 activity feed, currency filter, and style definition duplicate fixes

- packages/client/src/router/index.js
- packages/client/src/views/Dashboard.vue
- packages/client/src/views/RecentActivity.vue
Created frontend and backend functionality for a new full-size page to open when the see all activity button is clicked on the dashboard.
https://user-images.githubusercontent.com/60362888/181597916-806b1e42-a4e5-4e6a-847a-4806688691ac.mov
tested similar to how I tested the recent activity feed on the dashboard to make sure the feed was populating correctly then tested that the new page would load on a refresh and that any of the tabs at the top could be clicked on from that page to make sure routing was correct.
All automatic tests also passed
> 159: added full page see all recent activity

- packages/client/src/router/index.js
this pull request is fixing[ this](https://github.com/usdigitalresponse/usdr-gost/pull/179) pull request's indentation issues
> fix(157) fixed indentation

- packages/server/src/configure.js
- packages/server/src/routes/sessions.js
- packages/server/static/login_redirect.html
> Add a clientside redirect to better handle email systems that may prefetch login link

- README.md
> Update email setup steps.

- packages/client/src/views/Dashboard.vue
updated dashboard with feedback from UX designer
OLD:
NEW:
Fixed: aligned titles of recent activity and upcoming closing dates as well as the see all buttons, bolded the rejected and interested as well as UCD table dates, reduced the padding on the check and x icon col, unbolded the total, interested, and rejections col data, right aligned the the columns containing currency values and updated all necessary colors on the page 
not much to test, all front end stuff, just made sure it all matched the figma requests and made sure nothing on the backend broke
> fix(164): updated dashboard with feedback from UX designer

- README.md
- packages/server/src/lib/annualReports/doc-builder.js
- packages/server/src/lib/annualReports/reportBuilder.js
This updates the Annual Reporter logic to adjust for changes to the expected template and accounts for Tulsa's custom template which is slightly different.
> Update annual report logic for new template and Tulsa template

- packages/client/src/views/Dashboard.vue
- packages/client/src/views/RecentActivity.vue
fixed bold so that only the word assigned is bold
> fixed bold

- packages/client/src/views/Dashboard.vue
The changes to the dashboard that made it so assigned agencies would show up in the recent activity feed was reverted in a pull request so this Pr is to re-add those changes 
- [] Provided ticket and description
> re added changes to the dashboard for assigned agencies

- packages/client/src/components/Modals/EditAgency.vue
fixed missing data on agency edit
BEFORE:
AFTER:
>  #85: fixed missing data on edit

- README.md
> Add note about Windows install.

- packages/client/src/components/Modals/EditAgency.vue
> 85: Use Agency object, not id.

- packages/server/migrations/20220909024149_multitenant_agency_name_unique.js
> Migration to adjust UNIQUE constraint on agencies.name for multitenancy

- packages/server/__tests__/email/email.test.js
In dev environment, this test was failing because the default `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` from `.env.example` are blank. In CI, we set fake values for them, so I did the same thing here.
I also reorganized the `process.env` modifications in the test to make the cleanup a bit cleaner (using Mocha `beforeEach` and `afterEach` hooks).
> Fix email.test.js for dev

- package.json
- packages/server/package.json
> Add debug target

- packages/client/src/components/Layout.vue
Fix minor linting issue introduced in #343
> Fix linting issue

- packages/client/src/components/Layout.vue
Minor linting issue was introduced in #343, this PR corrects it to unblock deploys
> Fix linting issue introduced in #343

- packages/client/src/views/ArpaAnnualPerformanceReporter.vue
#208 
In-progress spinner for 'generate report' button (prevents re-click until report is ready)
https://user-images.githubusercontent.com/648605/191398847-ef96f5d4-7087-4e83-aadc-cdaf7bdfb601.mov
> feature:loading spinner on arpa generate report action

- packages/client/src/views/EligibilityCodes.vue
- packages/client/src/views/Keywords.vue
- packages/server/__tests__/api/eligibilityCodes.test.js
- packages/server/__tests__/api/keywords.test.js
- packages/server/src/routes/eligibilityCodes.js
- packages/server/src/routes/keywords.js
https://github.com/usdigitalresponse/usdr-gost/issues/278
see https://github.com/usdigitalresponse/usdr-gost/issues/278
n/a
Updated automated tests, also did some manual verification
> 278: allow staff users to modify keywords and eligibility codes

- packages/client/src/components/GrantsTable.vue
I will wait to test on the UAT environment before merging, but am tee-ing this up while that one deploys.
> Prod Release

- NODE_UPGRADES.md
- README.md
Updates the README to be up to date with a change made in https://github.com/usdigitalresponse/usdr-gost/pull/294 and https://github.com/usdigitalresponse/usdr-gost/pull/319
Also links to the official nvm setup instructions because brew's install instructions for nvm didn't work correctly, and their webpage indicates it isn't officially supported by nvm (https://formulae.brew.sh/formula/nvm)
> Update out of date setup instructions

- packages/client/src/components/Layout.vue
- packages/client/src/views/Keywords.vue
- packages/server/src/routes/keywords.js
> 175: Remove debugging columns from Keywords page

- packages/client/src/components/Layout.vue
- packages/client/src/views/EligibilityCodes.vue
- packages/server/src/routes/eligibilityCodes.js
https://github.com/usdigitalresponse/usdr-gost/issues/174
- remove updated_at column in eligibility codes view
- remove updated_at and created_at properties from each eligibility code in payload
(includes commit [81cd622](https://github.com/usdigitalresponse/usdr-gost/pull/436/commits/81cd622ecc684989ebac474525571c8bcf386fa4) from main branch)
> 174 eligibility codes

- packages/server/src/arpa_reporter/services/generate-arpa-report.js
#385 
I was able to test/confirm some theories about how the Treasury csv parser works, and use that to correct an issue with how we were writing csv files that are technically legal, but don't work for Treasuries off-spec csv parser.
The root cause is that treasury doesn't handle quoted fields correctly. The csv spec says that any field can be escaped by surrounding it with a `"` character before and after the field. These quotes let you use special csv characters (like new lines and commas) in a field, and then the quotes shouldn't be included in the value that is parsed from the file.
The treasury parser incorrectly includes those quotes in the value it parses from the file. That means that while the spec says that you should be allowed to surround any field with quotes, doing so has …
> 385: Fix line ending handling that causes open-and-save bug

- docker-compose.yml
> chore: open debugger port

- packages/server/src/db/index.js
> fix: ensure table querying is not ambiguous

- packages/client/src/components/GrantsTable.vue
- packages/client/src/store/modules/grants.js
- packages/server/__tests__/api/grants.test.js
- packages/server/src/db/index.js
- packages/server/src/routes/grants.js
https://github.com/usdigitalresponse/usdr-gost/issues/425
Front end work to finish out issue
n/a
Manual
> 425: sort grants frontend

- packages/server/src/arpa_reporter/lib/audit-report.js
Reverts usdigitalresponse/usdr-gost#524
> Revert "#390 Print all possible KPI metrics to audit report projects tab"

- packages/server/src/arpa_reporter/lib/audit-report.js
This reverts commit d80c8c209d0ca87e7a651919300c4d52f7ff5fbe.
> Revert "Print all possible KPI metrics to audit report projects tab #524

- packages/client/src/components/Modals/GrantDetails.vue
https://github.com/usdigitalresponse/usdr-gost/issues/438
See ticket
n/a
Manual
> 438: change 'Interested Agencies' section title

- packages/server/src/static/email_templates/_grant_assigned_body.html
- packages/server/src/static/email_templates/_grant_detail.html
- packages/server/src/static/email_templates/base.html
- Adds base email template static assets.
Note: This PR only adds the html. Follow-up PRs will build the templates.
N/A
> feat: add static email templates

- packages/server/__tests__/db/db.test.js
- packages/server/__tests__/db/seeds/fixtures.js
- packages/server/src/db/index.js
- Adds a helper function that will be used to send grant-assigned emails.
Added unit testing
> feat: adds helper db function to send emails

- .github/workflows/build-api.yaml
- .github/workflows/release-api.yaml
- docker/production-api.Dockerfile
- package.json
This PR adds functionality to build and (conditionally) publish a new Docker image for the GOST API server within a GitHub Actions workflow. 
Summary of new/changed files:
- `package.json`: Somewhat out-of-scope – I noticed that the `test:server` script command was actually configured to run tests for `packages/client`, and decided to fix it here.
- `docker/production-api.Dockerfile`: Provides instructions for building a Docker image that includes and runs _only_ the GOST API server code maintained under `packages/server`.
- Just to be explicit about it: No client (frontend) code is included in the build.
- To keep image size down, only production dependencies are installed by yarn during the build process (i.e. `devDependencies` are ignored).
- `.github/workflows/build-api.yml`: Defines …
> 609: Build and publish Docker images for API server

- packages/client/src/components/GrantsTable.vue
https://github.com/usdigitalresponse/usdr-gost/issues/77
See issue
Need to reload my db to do local testing.
> 77 show grant dates in correct time zone

- packages/client/src/components/GrantsTable.vue
- packages/client/src/components/Modals/GrantDetails.vue
- packages/server/src/routes/grants.js
https://github.com/usdigitalresponse/usdr-gost/issues/77
Found the bug in two more places
n/a
Manual
> 77 fix time zone bug in two other places

- packages/client/package.json
- packages/client/public/arpa_reporter/index.html
- packages/client/public/index.html
- packages/client/src/arpa_reporter/main.js
- packages/client/src/arpa_reporter/store/index.js
- packages/client/src/arpa_reporter/views/Login.vue
- packages/client/src/arpa_reporter/views/NewTemplate.vue
- packages/client/src/arpa_reporter/views/NewUpload.vue
- packages/client/src/helpers/fetchApi.js
- packages/client/src/views/ArpaAnnualPerformanceReporter.vue
- packages/client/src/views/Login.vue
- packages/client/tests/unit/helpers/fetchApi.spec.js
- yarn.lock
So as to not bury the lede: **Once this PR is merged, all new API calls made by the client application need to ensure that the new `apiURL()` function is called before the API request is made.** Read on to learn why!
This PR introduces a few relatively minor changes that facilitate scenarios where the deployed client frontend application is hosted separately from the API server backend. In particular, it introduces a new helper function, `apiURL()`, within the `packages/client/src/helpers/fetchApi.js` module. When called with an endpoint path, `apiURL()` checks for a `window.apiURLForGOST` value and prepends it to the endpoint path. If `window.apiURLForGOST` is undefined or false-y, `apiURL()` will return the endpoint path after ensuring that it is an absolute path (begins with `/`). …
> 602: Decouple client/server hostnames

- packages/client/package.json
- packages/client/public/arpa_reporter/index.html
- packages/client/public/index.html
- packages/client/src/arpa_reporter/main.js
- packages/client/src/arpa_reporter/store/index.js
- packages/client/src/arpa_reporter/views/Login.vue
- packages/client/src/arpa_reporter/views/NewTemplate.vue
- packages/client/src/arpa_reporter/views/NewUpload.vue
- packages/client/src/components/GrantsTable.vue
- packages/client/src/components/Modals/GrantDetails.vue
- packages/client/src/helpers/fetchApi.js
- packages/client/src/views/ArpaAnnualPerformanceReporter.vue
- packages/client/src/views/Login.vue
- packages/client/tests/unit/helpers/fetchApi.spec.js
- packages/server/src/db/index.js
- packages/server/src/lib/grantscraper/index.js
- packages/server/src/routes/grants.js
- yarn.lock
> 53 merge _staging into 43-grants-filters in preparation for merge back to _staging

- packages/client/src/components/GrantsTable.vue
- packages/client/src/store/modules/grants.js
- packages/server/src/db/index.js
- packages/server/src/routes/grants.js
- yarn.lock
> 52 intermediate PR to update 52-change-grant-sync-params

- .github/workflows/build-website.yml
- packages/client/public/deploy-config.js.example
- packages/client/tests/unit/helpers/fetchApi.spec.js
This PR adds a new GitHub Actions workflow to the repository, which serves as a pipeline for building and releasing the GOST website. 
Pipeline behavior is as-follows:
- For pull requests: The pipeline will attempt to build a distributable bundle for the website. Builds will not be persisted or deployed.
- For pushes to `_staging`: The pipeline will attempt to build a distributable bundle for the website. Once built, the files will be synced with the (AWS) staging/QA environment. Finally the staging/QA environment's CDN cache will be invalidated.
- For pushes to `main`: Same as for `_staging`, but targets the (AWS) production environment instead.
Note that builds do not include any configuration parameters that are specific to the target environment. Although currently each pipeline …
> 626: Website build+release pipeline

- packages/server/.eslintrc.js
- packages/server/__tests__/email/email.test.js
- packages/server/package.json
- packages/server/src/lib/email/email-aws.js
- packages/server/src/lib/email/service-email.js
- yarn.lock
This PR updates the the library at `packages/server/src/lib/email` according to the recommendations outlined in #613. Specifically, the following behaviors have changed:
1. Whenever a `NODEMAILER_HOST` environment variable is set, the `email-nodemailer` facilities will be returned by `getTransport()`. Otherwise, `email-aws` will be used.
2. `email-aws` is used regardless of whether any/all of `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `SES_REGION` environment variables are set. Previously a preemptive error was thrown if any of those environment variables were missing when calling the `createTransport()` function provided by `email-aws.js`. 
3. The `SES_REGION` environment variable is only used to override the `region` of any instantiated SES client. Otherwise, the AWS SDK will …
> 613: Email transport library updates

- packages/server/package.json
- yarn.lock
Adds aws-sdk-mock to ensure there is a good way to test AWS libraries moving forward. https://www.npmjs.com/package/aws-sdk-mock
The decision to add this library is recorded here; https://github.com/usdigitalresponse/usdr-gost/pull/658#pullrequestreview-1202822902
N/A
N/A
> feat: adds aws-sdk-mock package

- packages/server/src/lib/email.js
> feat: adds flag to not send emails

- packages/server/__tests__/arpa_reporter/server/seeds/02_users.js
- packages/server/__tests__/arpa_reporter/server/services/validation-rules.spec.js
- packages/server/migrations/20221010175026_add_null_constraint_to_agency_id_on_user.js
- packages/server/migrations/20221024183840_arpa_new_subrecipient_uid.js
- packages/server/src/arpa_reporter/lib/arpa-ec-codes.js
- packages/server/src/arpa_reporter/routes/audit-report.js
- packages/server/src/arpa_reporter/services/records.js
- packages/server/src/arpa_reporter/services/validation-rules.js
- packages/server/src/db/helpers.js
- packages/server/src/index.js
- yarn.lock
> Bring up to date with _staging

- docker/production-api.Dockerfile
- packages/client/src/arpa_reporter/main.js
- packages/client/src/arpa_reporter/store/index.js
- packages/client/src/arpa_reporter/views/NewTemplate.vue
- packages/client/src/arpa_reporter/views/NewUpload.vue
- packages/server/seeds/dev/01_main.js
- packages/server/seeds/dev/ref/users.js
- packages/server/src/routes/sessions.js
This PR makes a few miscellaneous tweaks that are mostly follow-ups to changes introduced in #618 and #624. The ultimate goal here is to make GOST ready for testing in our new staging/QA environment.
Summary of changes:
1. Replaced in ARPA Reporter client certain direct calls to `apiURL` to use the relevant function provided by the `arpa_reporter/store/index` module. These functions are more appropriate for properly making API calls; in particular, they ensure that `fetch()` is called with proper authentication options.
2. When generating magic login links, set a preference to use the `API_DOMAIN` environment variable when set (else fall back to `WEBSITE_DOMAIN`, which was the previous behavior). This should not have any impact on Render environments, where both environment variables are …
> 609: Fix outstanding AWS blockers

- packages/server/src/arpa_reporter/services/records.js
See PR 704 https://github.com/usdigitalresponse/usdr-gost/pull/704/files
> Adds truman's bugfix from #704 _staging PR

- packages/server/src/arpa_reporter/services/validation-rules.js
#378 
Follow-up to https://github.com/usdigitalresponse/usdr-gost/pull/740
Now that we've tested the feature in the limited capacity of the first PR (see slack thread here: https://usdigitalresponse.slack.com/archives/C031R1Y49KL/p1671822556794339) we're ready to expand it to the rest of the fields that Joe listed.
See slack thread for test uploads
> #378 expand conditional requirement to 25 more fields

- packages/client/src/components/Modals/ProfileSettings.vue
- packages/server/src/lib/email.js
- packages/server/src/lib/redirect_validation.js
- packages/server/src/static/email_templates/_grant_detail.html
Fixes the following things:
1. Truncates long grant descriptions as per the figma requirements
2. Links to the appropriate My Grants or Browse Grants page
3. Changes the button verbiage depending on the type of email
- Local environment testing
> [ID] Email notification styling, verbiage, linking fixes

- packages/server/src/lib/email.js
There are two changes here:
1. Makes sure that emails are live in production
2. Fixes a typo in the email status field
N/A
N/A
> feat: make emails live

- packages/server/package.json
- yarn.lock
- Allows ability to batch send out async requests: https://anchortagdev.com/smarter-async-batching-in-javascript-node-js/
N/A
N/A
> feat: adds dependency for async tasks

- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/arpa_reporter/routes/audit-report.js
- Implements `asyncBatch` to make sure that the number of parallel threads stays constant even if the number of jobs increases
N/A
- Manually tested in local dev env.
> feat: implement async batch

- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/arpa_reporter/services/records.js
- Changes any `Promise.all` to `asyncBatch`
N/A
- Local testing
> feat: adds more async batching

- .vscode/extensions.json
- README.md
None
Fixes I found while trying to set up my machine for the first time.
https://github.com/usdigitalresponse/usdr-gost/blob/bfaf311cb987b03101baa72cb513a0a56a1bf957/README.md#L69-L76
I think this part is unnecessary, as you export .env later in step 5. Also, this fails because of comment lines in the .env files.
https://github.com/usdigitalresponse/usdr-gost/blob/bfaf311cb987b03101baa72cb513a0a56a1bf957/README.md#L109-L110
This comment is out of date. `01_main` does not exist any more, nor does `CHANGEME@gmail.com`. Changed to the correct email.
Added recommended extensions so that vscode will prompt install automatically.
N/A
N/A
> chore(documentation): fix issues found in first-time setup

- packages/client/src/views/Dashboard.vue
265
add description text for when there are no Recent Activity as well as no Upcoming Closing Dates
> 265: show message for user

- packages/client/public/arpa_reporter/index.html
883
Add google analytics manager to arpa reporter.  packages/client/public/arpa_reporter/index.html
Same script as the one found in the index file in client.
> #883 add google analytics script to arpa 

- packages/client/src/views/Dashboard.vue
- packages/server/__tests__/db/db.test.js
- packages/server/__tests__/db/seeds/fixtures.js
- packages/server/seeds/dev/ref/grants.js
#835
See ticket
Added a rejected grant with a time-dependent close date to the local db seed file. If you want to double-check, you will have to run `docker compose exec app yarn db:seed` to see that grant.
> 835 rejected grants not show in upcoming

- packages/client/src/components/Modals/AddKeyword.vue
handle dirty not dirty state for keyword input, reset form state when closed
> #173 handle dirty not dirty state for keyword input, reset form state when closed

- packages/client/src/components/Modals/GrantDetails.vue
#603
fix spacing, remove row styling element on some.
> style: fix spacing and move to same row

- packages/client/src/components/Modals/EditAgency.vue
- packages/server/src/lib/email.js
> 791: add missing self parent agency error

- .nycrc
- Unnecessary files are being captured by the Istanbul coverage report. This PR ensures we exclude these files from it.
```
=============================== Coverage summary ===============================
Statements   : 66.82% ( 3581/5359 )
Branches     : 32.52% ( 456/1402 )
Functions    : 66.51% ( 880/1323 )
Lines        : 67.17% ( 3489/5194 )
================================================================================
```
```
=============================== Coverage summary ===============================
Statements   : 47.18% ( 1459/3092 )
Branches     : 30.34% ( 400/1318 )
Functions    : 42.81% ( 271/633 )
Lines        : 47.76% ( 1433/3000 )
================================================================================
```
N/A
> feat: reduces test coverage noise

- packages/client/src/components/Modals/AddKeyword.vue
- packages/client/src/main.js
- packages/client/src/views/Keywords.vue
Vue expects env variables to have the prefix of `VUE_APP`. Fix previous commit to comply with this requirement.
> 961: update env variable to be VUE_APP_env

- .github/workflows/build-and-deploy.yml
- .github/workflows/dependabot-auto-approve.yml
- .github/workflows/terraform-ci.yml
This PR modifies a few of our Github Actions workflows:
- **Build and deploy GOST** 
- Updates the "Detect changes" job so that modifications to the `build-api.yml` workflow results in the job flagging that the API has changes.
- Update the "Detect changes" job so that modifications to the `build-website.yml` workflow results in the job flagging that the website has changes.
- **Terraform CI**
- Remove the `build-and-deploy.yml` filter from triggering this workflow – it should only run when something will actually affect its execution, such as a modification to the "Terraform CI" workflow file or any `terraform/**` path changes.
Observe the affected workflow executions [here](https://github.com/usdigitalresponse/usdr-gost/actions).
> 609: Update workflow triggers

- packages/server/migrations/20230219162719_migrate_varchar_columns_to_text.js
See ticket
n/a
See https://github.com/usdigitalresponse/usdr-gost/issues/877#issuecomment-1435398568
> 855 migrate varchar columns to text

- packages/server/__tests__/email/email.test.js
- packages/server/src/lib/email.js
Grants count in the digest email needs to be updated to 30 and this PR does exactly that.
N/A
This is hard to test manually and requires a lot of setup. Given the Unit test coverage here and my familiarity with the code I'm opting to ignore this step.
> feat: updates grant limit to 30

- terraform/production.s3.tfbackend
- terraform/production.tfvars
This PR add configuration for provisioning infrastructure in Terraform to our production environment on AWS.
> Configure terraform for production environment

- packages/client/.eslintrc.js
- packages/client/src/arpa_reporter/App.vue
- packages/client/src/arpa_reporter/components/DownloadTemplateBtn.vue
- packages/client/src/arpa_reporter/components/Navigation.vue
- packages/client/src/arpa_reporter/components/StandardForm.vue
- packages/client/src/arpa_reporter/store/index.js
- packages/client/src/arpa_reporter/views/Agency.vue
- packages/client/src/arpa_reporter/views/Home.vue
- packages/client/src/arpa_reporter/views/Login.vue
- packages/client/src/arpa_reporter/views/ReportingPeriod.vue
- packages/client/src/arpa_reporter/views/Subrecipient.vue
- packages/client/src/arpa_reporter/views/Subrecipients.vue
- packages/client/src/arpa_reporter/views/Upload.vue
- packages/client/src/arpa_reporter/views/Uploads.vue
- packages/client/src/arpa_reporter/views/User.vue
- packages/client/src/arpa_reporter/views/Users.vue
- packages/client/src/arpa_reporter/views/Validation.vue
This pull request removes ignore rules for the last remaining JavaScript and Vue files in the client package of this repository.
Note that all changes in this pull request were manually applied.  Everything that could be resolved via `eslint --fix` was committed in #1036.
BEFORE:
AFTER:
Test these changes by running `yarn lint` in the `packages/client` directory.
- ~Added Unit tests~
- ~Provided adequate test coverage for all new code~
> Fix remaining ESLint errors in client code!

- terraform/main.tf
This PR cherry-picks #1063 changes to production.
> RELEASE: Send emails from grants-notifications@website_domain (#1063)

- terraform/modules/gost_postgres/main.tf
The latest production deployment hit a snag during the terraform apply step. https://github.com/usdigitalresponse/usdr-gost/actions/runs/4474601357/jobs/7863234372
This PR aims to fix the issues identified in this step.
> fix: Align terraform with existing AWS environment

- packages/client/src/arpa_reporter/views/ReportingPeriods.vue
- packages/server/src/arpa_reporter/routes/reporting-periods.js
The following changes ensure:
1. Cookies are sent in the request to the API which contain auth information.
2. There is logging to debug further if the problem continues to happen.
> [ARPA][Bug] Fix issue with "Forbidden" error for closing reporting periods

- packages/client/src/arpa_reporter/views/ReportingPeriods.vue
When I merged #1126 I messed up the return values of the `post` method. This PR fixes and ensures we are handling the result correctly.
> fix: client error when certifying reporting period

- packages/client/vue.config.js
add title to vue.config.js file for seo title tag to say something other than client. 
run and check arpa_reporter as well as grants to make sure title text changed.
> 948 change title text

- packages/client/src/arpa_reporter/views/Home.vue
- packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
- packages/server/__tests__/arpa_reporter/server/routes/audit_report.spec.js
- packages/server/__tests__/email/email.test.js
- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/arpa_reporter/routes/audit-report.js
- packages/server/src/lib/email.js
- Adds email for the new audit-report generation
- Adds front-end to show an alert when email is sent successfully or if there is an error.
- Adds a button to send the audit report email asynchronously
- Allows the ability if needed to generate report synchronously through a known query-parameter
To do a happy path test:
1. Go to `localhost:8080/arpa_reporter`
2. Once logged in hit the "Send Audit report by email" button
To generate an error test:
Add `throw Error('invalid')` after line 18 in `/routes/audit-report.js`
Then do the same steps as above
> feat: adds wiring for async audit report generation

- packages/server/__tests__/api/grants.test.js
update 2 sec delay to 10sec in export test. I think this is right?
> fix: 2 seconds updated to 10 sec

- docker/README.md
This adds some additional documentation for using Docker and gives a few hints for blockers that someone may run into when first using it. Note: I did take a look through open issues and couldn't find one for any of these dev UX improvements, just opening this based on my experience getting started.
> Improvements to Docker documentation

- packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
- packages/server/src/arpa_reporter/lib/audit-report.js
> fix: add encryption algorithm s3

- packages/server/src/arpa_reporter/lib/audit-report.js
- Previously the URL was not getting generated properly. I tested this in Cloudshell and made sure to run this synchronously.
> fix: ensure url is signed synchronously

- terraform/main.tf
- terraform/modules/gost_website/cdn.tf
- terraform/modules/gost_website/variables.tf
- terraform/modules/gost_website/waf.tf
- terraform/staging.tfvars
- terraform/variables.tf
See title.  Only adding rules to staging right now until I can get a better idea of how they are going to affect production.
> feat: adding WAF to website Cloudfront CDN

- terraform/modules/gost_website/certificate.tf
- terraform/modules/gost_website/main.tf
- terraform/modules/gost_website/waf.tf
> fix: WAFv2 must be managed in us-east-1 if globally scoped

- packages/client/public/errors/403.html
- packages/client/public/errors/404.html
- terraform/modules/gost_website/cdn.tf
Reverts usdigitalresponse/usdr-gost#1190
> Revert "Revert "feat: adds a custom 404 and 403 page""

- packages/client/src/components/GrantsTable.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/usdr-gost-next/next-env.d.ts
parent component with close side panel action. Panel has been moved to the right but the close X button stays on the left. I don't want to fight the bootstrap css, so hope it's ok. 
footer also included with close button functional
> 1399 search side panel

- packages/server/__tests__/arpa_reporter/server/db/uploads.spec.js
- packages/server/__tests__/arpa_reporter/server/fixtures/fixtures.js
- packages/server/__tests__/arpa_reporter/server/routes/uploads.spec.js
- packages/server/__tests__/arpa_reporter/server/services/validate-upload.spec.js
- packages/server/migrations/20230619215513_add_exclude_for_uploads.js
- packages/server/src/arpa_reporter/db/uploads.js
- packages/server/src/arpa_reporter/routes/uploads.js
- packages/server/src/arpa_reporter/services/validate-upload.js
> fix: #1268  (#1570)

- docker/README.md
Adds some internal links to help highlight fixes to common issues for first time use of the app on docker.
> Docker readme update

- packages/server/src/arpa_reporter/services/records.js
The original PR has a subtle issue on arguments to async batch causing issues on the audit report.
Reverted the problematic call for now.
> fix: #1571 - fixed issue with the asyncbatch call

- packages/client/src/components/Layout.vue
- Removes Notification Banner
To test manually
- Run localhost:8080 and notice that banner has disappeared.
> feat: removes notifications banner

- packages/client/src/components/GrantsTable.vue
- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/components/SearchFilter.vue
- packages/client/src/store/modules/grants.js
- packages/server/src/lib/email.js
Continuation of #1638, applying to #1697. Note target branch.
Basically the same comments/logic as #1638, so not copying here (esp since this is draft). See comments in files.
> Apply search criteria to saved search frontend

- packages/client/src/components/GrantsTable.vue
- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Modals/SavedSearchPanel.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/components/SearchFilter.vue
- packages/client/src/store/modules/grants.js
- packages/client/src/views/Grants.vue
- packages/server/src/db/index.js
- packages/server/src/lib/email.js
- packages/server/src/routes/grantsSavedSearch.js
> feat: search front-end

- packages/server/src/arpa_reporter/services/persist-upload.js
Quick typo fix for an issue I introduced in #1732!
> Fix typo: tracer.tracer -> tracer.trace

- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Layout.vue
- packages/client/src/components/Modals/SavedSearchPanel.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/components/SearchFilter.vue
- packages/client/src/views/MyGrants.vue
Tweaks the table display, search filter controls, and loading per feedback and closes #1409. Also closes #1690 with design tweaks.
I confirmed that I had broken the search filter applies - this fixes that too (which closes #1730). 
List of tweaks/fixes:
1. header ribbon shouldn't be full width, should match table body
1. background color on search panel - should be white
- same with saved search
1. close button hover background looks odd
1. my saved searches - row hover state needs to be full width
- kebab menu should be full right, dark grey
1. my saved searches - row hover state needs to be full height
1. export csv - align to top of table
1. search title - also to top of table, in line with export csv
1. decrease spacing between search buttons 
1. pagination total looks like a button, …
> Design feedback, search fix

- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/components/SearchFilter.vue
Small fixes to My Grants edits:
- Don't change URL/route on edit and clear buttons
- Ensure table refreshes when saving changes to a search
- 
Confirm edit/clear still work as expected
Confirm saving an edit to a search triggers a refresh of table data
> Edit search fixes for #1797

- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Modals/GrantDetails.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/helpers/filters.js
- packages/client/src/store/modules/grants.js
- packages/client/src/views/RecentActivity.vue
- packages/server/__tests__/db/db.test.js
- packages/server/migrations/20230823203959_add-grants-ts-vectors.js
- packages/server/migrations/20230823204218_add-grants-columns.js
- packages/server/src/db/index.js
- packages/server/src/lib/grants-ingest.js
- packages/server/src/routes/grants.js
> fix: initial search adjustments 815 review

- packages/client/src/views/Dashboard.vue
> fix: ensure stats are hidden from dashboard

- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Modals/SearchPanel.vue
- Fixes border around the grants totals
- Eligibility multi-select
- Other unrelated errors
https://www.loom.com/share/d4f23b530e4f465fb7e5b5551d2f3750?sid=2318f9ee-1841-48b9-8c47-3a9cd81db7bf
N/A
> fix: various search bugs

- terraform/staging.tfvars
Makes the new search experience live by default in staging.
> chore: make new search experience live in staging

- packages/client/src/components/Modals/SavedSearchPanel.vue
- Move toast to bottom right for delete confirmation
- Add padding to kebab menu for saved search
- Clear current search if target of delete
> QA feedback

- packages/server/src/arpa_reporter/lib/audit-report.js
A quick typo fix for KPI sheet calculations!
> fix: Correct typo in KPI sheet calculation

- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/arpa_reporter/services/persist-upload.js
* Add datadog span traces to file I/O and XLSX parsing
* Add tracing spans to workbook write operations
> Add datadog spans for file I/O and XLSX parsing (#1732)

- packages/server/src/arpa_reporter/lib/audit-report.js
Original commit: dcf651e3970bbfdabc845752c3313fb895c9c044
> Cherry-pick only ARPA fix from #1831

- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Modals/SavedSearchPanel.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/helpers/constants.js
- packages/client/src/store/modules/grants.js
- packages/server/src/db/index.js
- packages/server/src/routes/grantsSavedSearch.js
Adds the following
- pagination to saved search
- fixes styling issues in multiselect component (note: required me to restructure the previously written css classes)
- removes review-status field
- Bill field as "Appropriations Bill"
- Added "All bills" option to the field
- Other spacing issues
> chore: design changes and bug fixes based on QA

- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/store/modules/grants.js
- Fixes: `Choosing "All Bills" returns zero results.`
> fix: ensure 'All Bills' option works

- packages/server/src/routes/grants.js
- Changes the CSV limit to 500 rows instead of the previous 300
> chore: change csv limit

- packages/server/migrations/20230915145941_grants-data-type-migration-add-temp-columns.js
- packages/server/migrations/20230915145942_grants-data-type-migration-move-data-to-temp-columns.js
- packages/server/migrations/20230915150001_grants-data-type-migration-rename-columns.js
- packages/server/migrations/20230915150014_grants-data-type-migration-drop-old-columns.js
- packages/server/package.json
> chore: add data-type migrations

- packages/server/__tests__/db/db.test.js
- packages/server/src/db/index.js
- packages/server/src/lib/email.js
- Fixes a bug in #1946 which does not allow `archived` status in opportunity-status
> Fix: Bug in search notifications which does not consider `archived` status as valid

- packages/client/src/components/Layout.vue
- Adds a training guide link to open in a new tab
N/A
> feat: adds training guide to user drop-down

- terraform/modules/gost_api/task.tf
- Goal is to add memory and test if this resolves some of the ARPA audit report generation issues.
- If we are still failing over the server, then we must close the audit-report generation endpoint and go back down to the old levels. #1959 
```
September 21, 2023 at 21:29 (UTC-4:00)	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.	3d6974bf25014c96ad19c6121924ccef	api
September 21, 2023 at 21:29 (UTC-4:00)	error Command failed with signal "SIGKILL".	3d6974bf25014c96ad19c6121924ccef	api
September 21, 2023 at 21:28 (UTC-4:00)	generate(175)	3d6974bf25014c96ad19c6121924ccef	api
September 21, 2023 at 21:28 (UTC-4:00)	::ffff:10.0.2.61 - - [22/Sep/2023:01:28:40 +0000] "GET /api/audit_report?async=true HTTP/1.1" 304 -	3d6974bf25014c96ad19c6121924ccef	api …
```
> chore: adds additional memory to Fargate task

- packages/server/__tests__/api/grantsSavedSearch.test.js
- packages/server/src/db/index.js
Unit tests for saved seach edits. Also, updates updated at time when updating
> fix: edit saved search unit tests

- packages/server/src/lib/gost-aws.js
> fix: lengthy log clutters datadog and cloudwatch

- packages/server/src/arpa_reporter/lib/audit-report.js
This PR adds a hack structured logging function to the `packages/server/src/arpa_reporter/lib/audit-report.js` module and utilizes it with a smattering of debug logs across the `generateAndSendEmail()` call path. This is meant as a temporary solution so that we can force a crash by requesting an ARPA audit report, and hopefully use the emitted logs to have a better sense of what's going on in the running node process.
In addition to a message and arbitrary key/value pairs, the logger also accumulates "sticky" key/value pairs. Since the accumulation happens in a global variable, log output is only useful if a single coroutine is using it (i.e. make sure not to kick off two audit reports simultaneously during testing). Finally, every call to `log()` emits CPU and RAM usage statistics for …
> ARPA audit report investigation: Round 1

- packages/server/src/arpa_reporter/routes/audit-report.js
Fixes an issue causing the SQS message body for ARPA audit report tasks to be an empty object.
> Fix JSON SQS message body for ARPA tasks

- terraform/main.tf
- terraform/modules/gost_api/outputs.tf
This PR updates the `arpa_audit_reports` ECS task policy with permissions to send email using SES.
> ARPA Audit Report tweaks: Round 4

- packages/client/src/components/GrantsTableNext.vue
- packages/client/src/components/Modals/SavedSearchPanel.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/components/SearchFilter.vue
Reverts usdigitalresponse/usdr-gost#2025
> Revert "fix: prevent changing search when results are loading"

- packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
- packages/server/package.json
- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/lib/logging.js
- packages/server/src/scripts/arpaAuditReport.js
- terraform/main.tf
- yarn.lock
This PR is the first (in what I expect to be a handful) pass at tuning the ARPA audit report generation. Now that it is able to execute successfully most of the time in Production, this PR includes:
- Improves to tracing and logging
- Concurrency limitations
- Infrastructure tweaks to avoid premature retry attempts due to a low message visibility timeout on the SQS source queue
- A few opportunistic optimizations and various code-cleanup tweaks
Verify that audit report generation succeeds in a local test and/or sandbox environment according to the path documented in the QA script.
> ARPA audit report tuning: Round 1

- packages/client/src/arpa_reporter/views/Uploads.vue
> fix: bug with show validated button

- packages/client/src/arpa_reporter/views/Home.vue
- terraform/modules/gost_api/task.tf
Reverts usdigitalresponse/usdr-gost#1959
> Revert "chore: add service-down page for report generation"

- packages/client/src/arpa_reporter/views/Home.vue
Partially Reverts usdigitalresponse/usdr-gost#2073
> Turn off Treasury Report generation for users

- packages/server/src/arpa_reporter/routes/exports.js
- packages/server/src/arpa_reporter/services/generate-arpa-report.js
- packages/server/src/scripts/arpaTreasuryReport.js
- terraform/datadog_monitors.tf
- terraform/main.tf
> Add Task queue for ARPA Treasury Reports

- packages/client/src/views/RecentActivity.vue
Update totalRows and label to use counts that are filtered or not filtered properly.
#949 Unusual display in "Recent Activity" grid
> fix: #949 update interested grants count labels

- packages/server/src/arpa_reporter/routes/exports.js
- packages/server/src/arpa_reporter/services/generate-arpa-report.js
- Fixes the queue message arguments
- Additional logging and datadog traces
- Makes main CSV generation process synchronous
> Treasury Report Updates - 1

- packages/client/src/components/Modals/SearchPanel.vue
> fix: update saved search default title to use date

- packages/server/src/arpa_reporter/routes/exports.js
- Previously the userId parameter was undefined now it passes the correct number
> fix: typo in message params

- packages/client/package.json
- packages/client/src/components/Modals/SearchPanel.vue
- yarn.lock
Add seconds to default search title
Tested manually.
- [ x] Provided ticket and description
- [x ] Added PR reviewers
> fix: #2064 Add seconds to default search title

- packages/client/src/arpa_reporter/views/Home.vue
Reverts usdigitalresponse/usdr-gost#2094
> Revert "Turn off Treasury Report generation for users"

- packages/client/src/components/GrantsTableNext.vue
- packages/server/__tests__/api/grants.test.js
- packages/server/src/routes/grants.js
Removing 'Award Floor' column from results table and CSV, as it is almost always empty.
Navigate to Browse Grants and observe that 'Award Floor' column is gone.
Export CSV and observe that 'Award Floor' column is gone.
> feat: remove Award Floor from results table & CSV export (#2132)

- packages/client/.nycrc
- packages/client/babel.config.js
- packages/client/package.json
- packages/client/src/arpa_reporter/views/Home.vue
- packages/client/src/views/Agencies.vue
- packages/client/tests/unit/arpa_reporter/views/Home.spec.js
- packages/client/tests/unit/views/Agencies.spec.js
- yarn.lock
N/A
Just adding some unit tests.
N/A
- [/] Added Unit tests
> Snodgrass adding some vue component tests

- packages/client/src/store/modules/users.js
- packages/client/src/views/MyProfile.vue
- packages/server/__tests__/api/users.test.js
- packages/server/migrations/20231103202457_update_email_subscriptions_notification_type.js
- packages/server/src/db/index.js
- packages/server/src/lib/email/constants.js
- packages/server/src/routes/users.js
Includes migration to add GRANT_FINDER_UPDATES to notification types in email subscription table. Updates My Profile component to support fetching and updating statuses.
https://github.com/usdigitalresponse/usdr-gost/assets/17172664/931ca9b6-0136-4390-b2fd-770234e0e35c
> Feature: My profile email notifications

- packages/client/src/components/GrantsTableNext.vue
https://github.com/usdigitalresponse/usdr-gost/assets/146878468/8f78d2cf-0b8c-4e96-aefd-62b4f4b5cc5a
Scroll the grants table with different sized search results
> fix: remove sticky header and scrollable table

- packages/client/src/components/Layout.vue
update size of logo to match profile badge size
Test that header size hasn't changed but height of logo matches profile logo.
- [x ] Provided ticket and description
- [x ] Provided testing information
- [x ] Added PR reviewers
> fix: #2306 update size of logo to match profile badge size

- docs/development.md
- packages/client/package.json
- packages/client/src/components/Layout.vue
- packages/client/src/main.js
- packages/client/src/router/index.js
- packages/client/src/views/Dashboard.vue
- packages/client/src/views/MyProfile.vue
- packages/client/src/views/NotFound.vue
- packages/client/tests/unit/router/routes.spec.js
- packages/client/vue.config.js
- packages/server/__tests__/api/sessions.test.js
- packages/server/__tests__/lib/redirect_validation.test.js
- packages/server/src/lib/email.js
- packages/server/src/lib/redirect_validation.js
- packages/server/src/routes/sessions.js
- yarn.lock
This PR should satisfy the first requirement in the associated ticket:
> GA4 page_view events fire on state changes that generate a unique URL
The second requirement (adding an "agency_name" parameter) will be handled in a separate PR.
Nothing in this PR refers directly to Google Analytics. The idea is that switching the router to use the HTML5 history API will automatically fix our Google Analytics problem, for reasons explained in [this PR](https://github.com/usdigitalresponse/usdr-gost/pull/2323). An additional benefit is that Grant Finder will have nicer URLs - instead of `https://grants.usdigitalresponse.org/#/my-grants`, the URL will be `https://grants.usdigitalresponse.org/my-grants`. To avoid breaking any existing bookmarks or emailed links, URL's with hashes will be redirected to …
> feat: switch grant finder to use history API for client-side routing

- packages/client/src/components/Layout.vue
> fix: ensure organizations tab is only viewed for usdr admins

- .github/release-drafter.yml
> fix: release naming issue

- .github/release-drafter.yml
> fix: make name explicit to 2024

- terraform/prod.tfvars
Enables both client and api feature flags in production for-
- new team terminology
- myProfile tab
N/A
Can only test in production
> chore: turn on myProfile feature

- packages/client/public/index.html
- terraform/modules/gost_website/tpl/deploy-config.js
https://github.com/usdigitalresponse/usdr-gost/pull/2441 broke staging because I missed some quote marks in the template for `deploy-config.js`, which resulted in invalid JS in the deployed version of `deploy-config.js`. This PR fixes the template.
Look at the output from "Validate and plan terraform" and note that there is a change to `window.APP_CONFIG.GOOGLE_TAG_ID`:
```shell
~ resource "aws_s3_object" "deploy-config" {
~ content                = <<-EOT
window.APP_CONFIG = window.APP_CONFIG || {};
window.APP_CONFIG.apiURLForGOST = 'https://api.staging.grants.usdr.dev/';
window.apiURLForGOST = window.APP_CONFIG.apiURLForGOST; // Legacy
window.APP_CONFIG.DD_RUM_ENABLED = true;
- window.APP_CONFIG.DD_RUM_CONFIG = {"allowedTracingUrls":["https://api.staging.grants.usdr.dev/"],"applicationId …
```
> Fix deployed version of deploy-config.js.

- packages/server/src/arpa_reporter/lib/arpa-ec-codes.js
Updates the text for EC1.4 as described in the linked ticket.
> fix: correct typo in EC1.4

- packages/client/src/arpa_reporter/views/Subrecipients.vue
Fixes a leftover console.log statement from #2164
> Clean up leftover console.log statement

- packages/client/src/views/GrantDetails.vue
Updates the copy icon on the new grant details page to match the design.
Visual inspection
> Use copy icon from design

- terraform/prod.tfvars
Enable the client-side flag for "Category of Funding Activity", which:
- Displays the new field on the Grant Details page (both the new and the old version)
- Adds the field to search
Can only be tested in production
> chore: turn on category of funding activity field in production

- packages/client/src/views/GrantDetails.vue
- Implement some print-specific styles to hide interactive elements like buttons that don't make sense in print
- Implement the copy link success transition on the copy button
Note: I've confirmed browser support in all evergreen browsers. But do we need target support for additional browsers beyond that? 
- Manually verified behavior of both print and copy on Chrome, Firefox, and Safari
- Confirmed support in all evergreen browsers on MDN
- [Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility)
- [Print](https://developer.mozilla.org/en-US/docs/Web/API/Window/print#browser_compatibility)
> Full implementation of print and copy actions on Grant Details page

- packages/client/src/views/GrantDetails.vue
Fix up Category of Funding Activity label and add colons to table
Follow up to fix truncated Category of Funding Activity label and add colons to the table
Turn on Grant Details Page feature flag and look at table to see colons in first column, and the complete Category of Funding Activity label
> Fix up Category of Funding Activity label and add colons to table

- packages/client/src/views/GrantDetails.vue
Adjust size and style of Grant Details buttons
Verify Apply button height matches the other buttons and that the Submit buttons have an outline style
- [ x] Provided ticket and description
- [x ] Provided testing information
- [ x] Added PR reviewers
> Adjust size and style of Grant Details buttons

- packages/client/src/views/GrantDetails.vue
updating left and right margins and right column width
Before:
After:
> updating left and right margins and right column width

- packages/client/public/deploy-config.js
- packages/client/src/components/Modals/GrantDetailsLegacy.vue
- packages/client/src/components/Modals/SearchPanel.vue
- packages/client/src/helpers/featureFlags/index.js
- terraform/prod.tfvars
- terraform/sandbox.tfvars
- terraform/staging.tfvars
The "Category of Funding Activity" feature has been active in production for 2 weeks now so I think it's safe to remove the feature flag.
> Remove the feature flag 'categoryOfFundingActivitySearchFieldEnabled'.

- docs/decisions/0007-adopt-vue-recommended-linting.md
ADR to discuss adopting stricter vue linting rules.
> [Decision] Adopt vue/recommended linting

- docs/setup-gmail.md
> Update setup-gmail.md to make docker rebuild explicit

- packages/client/src/components/Modals/GrantDetailsLegacy.vue
- packages/client/src/store/modules/grants.js
- packages/client/src/views/GrantDetails.vue
- packages/server/src/db/index.js
- packages/server/src/routes/grants.js
A code clean-up PR. See ticket for justification.
No visible changes.
Start the app up and check that the Grant Details page still loads.
> Delete code for obsolete SPOC PDF feature.

- packages/client/src/views/GrantDetails.vue
https://github.com/usdigitalresponse/usdr-gost/assets/485547/19bc2715-1860-44fa-bbbb-ccedfd8e4761
> Fix some styles and correct back text

- docs/decisions/0007-adopt-vue-recommended-linting.md
> Mark ADR 0007 "Adopt vue/recommended linting" as accepted

- packages/client/src/arpa_reporter/views/Home.vue
- packages/client/src/assets/adjust-vue-select.css
- packages/client/tests/unit/arpa_reporter/views/Home.spec.js
Reverts usdigitalresponse/usdr-gost#2657
> Revert "fix: #1801 - revert frontend change"

- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/arpa_reporter/services/records.js
* add a subaward tab for the audit report
* add sheets option for filtering records by project
Ran the test locally and checked the output.
Still need to add unit tests, but I wanted to push this for UAT testing ahead of unit tests as they will take time.
> fix: #2609 - audit report subaward

- packages/server/__tests__/arpa_reporter/server/lib/audit-report.spec.js
- packages/server/src/arpa_reporter/lib/audit-report.js
* sorted headers for the new tab
* adjusted the headers on the new tab
* fixed the test case
Ran the audit report locally and fixed a test case.
> fix: #2609 - audit subaward fixes

- packages/server/src/arpa_reporter/lib/audit-report.js
- packages/server/src/arpa_reporter/lib/format.js
* Added rounding to two decimal places for audit report
* Added round function that keeps number type
Ran the audit report locally
> fix: #2753 - Audit Report Round to 2 Decimal Places

- packages/server/src/lib/email.js
- terraform/main.tf
- terraform/modules/gost_api/task.tf
- terraform/modules/gost_api/variables.tf
- terraform/prod.tfvars
- terraform/sandbox.tfvars
- terraform/staging.tfvars
- terraform/variables.tf
I deleted the front-end feature flag in https://github.com/usdigitalresponse/usdr-gost/pull/2954 but missed the back-end flag.
N/A
Trigger the sending of a "Grant Assigned" email and check that the "Change notification preferences" link at the bottom of the email points to the "My Profile" page.
> Delete backend ENABLE_MY_PROFILE feature flag.

- .github/workflows/deploy-production.yml
This PR tweaks the `tar` command used to create the `Client website bundle` release artifact in the `deploy-production.yml` GHA workflow's "Update release" job. Currently (as of release [v2024.35](https://github.com/usdigitalresponse/usdr-gost/releases/tag/release%2F2024.35)) these artifacts include the contents of `packages/client/src` at the root of the tarball in addition to the nested `dist/` directory. Including the source files is unnecessary since this can simply be checked out as well as downloaded from the `Source code (zip)` and `Source code (tar.gz)` artifacts automatically included in releases. 
Since the purpose of this particular artifact is to provide an exact copy of the files deployed to the target (Production) environment, this PR limits the contents of the tarball to a …
> Trim `Client website bundle` release artifact

- .github/ISSUE_TEMPLATE/arpa_quarterly_checklist.yml
> 2980 create new quarterly GitHub issue template

- packages/server/src/arpa_reporter/services/validate-upload.js
Removed validation that is no longer necessary as described in the ticket.
Ran unit tests
> fix: #2987 - removed unnecessary validation

- docs/decisions/0008-migrate-to-vite.md
Marks the Vite decision as accepted
> Mark vite decision as accepted

- docs/decisions/0009-upgrade-to-vue-3.md
> Mark vue 3 decision accepted

- terraform/prod.tfvars
Flip `shareTerminologyEnabled` and `SHARE_TERMINOLOGY_ENABLED` to `true` in prod
> chore(Assign-to-Share): flip prod ff 

- packages/client/src/components/GrantActivity.vue
- Fix for prior PR (https://github.com/usdigitalresponse/usdr-gost/pull/3470)  to ensure correct display on bullet
> Bug fix: replace computed flag

- docs/releasing.md
- usdr-gost.code-workspace
These are two items I noticed while onboarding and doing my first PR
1. Vitest extension was not working correctly because I was using NVM and vitest extension was finding the wrong version of Node
2. Deployed my first PR to staging and didn't realize database migrations must be manually run
> Chore: Minor doc update for local dev and staging deployment

- packages/client/src/components/GrantsTable.vue
Grants table was not displaying any grants.  Grants data was getting returned from the api call.
console
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
at
at Array.map (<anonymous>)
at Proxy.formattedGrants ()
```
> fix(grants): check for null data and feature flag

- packages/server/__tests__/arpa_reporter/server/fixtures/fixtures.js
- packages/server/__tests__/arpa_reporter/server/services/full-file-export.spec.js
- packages/server/src/arpa_reporter/services/full-file-export.js
- Updates handling of `null` validation based on the requirements
N/A
Updated existing unit tests
> fix: ensures that files with null validation are handled appropriately

- terraform/prod.tfvars
- This PR enables full-file-export so the button is visible to our partners in production.
N/A
N/A
> chore: enable full file export in production

- terraform/main.tf
- terraform/prod.tfvars
- terraform/staging.tfvars
- terraform/variables.tf
This PR disables all notifications except for welcome (new user) and passcode (login). This will correspond to a Nava-side change that enables emails in their environments.
> Feat: Allow-list welcome and passcode emails
